package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 1 patched method(s), 17 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.google.javascript.jscomp.CodeGenerator|strEscape|java.lang.String,char,java.lang.String,java.lang.String,java.lang.String,java.nio.charset.CharsetEncoder|static",
        "M|com.google.javascript.jscomp.CodeGenerator|add|com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.CodeGenerator:com.google.javascript.jscomp.CodeConsumer",
        "M|com.google.javascript.jscomp.CodeGenerator|add|com.google.javascript.rhino.Node,com.google.javascript.jscomp.CodeGenerator$Context|new:com.google.javascript.jscomp.CodeGenerator:com.google.javascript.jscomp.CodeConsumer",
        "M|com.google.javascript.jscomp.CodeGenerator|add|java.lang.String|new:com.google.javascript.jscomp.CodeGenerator:com.google.javascript.jscomp.CodeConsumer",
        "M|com.google.javascript.jscomp.CodeGenerator|addAllSiblings|com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.CodeGenerator:com.google.javascript.jscomp.CodeConsumer",
        "M|com.google.javascript.jscomp.CodeGenerator|addArrayList|com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.CodeGenerator:com.google.javascript.jscomp.CodeConsumer",
        "M|com.google.javascript.jscomp.CodeGenerator|addCaseBody|com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.CodeGenerator:com.google.javascript.jscomp.CodeConsumer",
        "M|com.google.javascript.jscomp.CodeGenerator|addExpr|com.google.javascript.rhino.Node,int,com.google.javascript.jscomp.CodeGenerator$Context|new:com.google.javascript.jscomp.CodeGenerator:com.google.javascript.jscomp.CodeConsumer",
        "M|com.google.javascript.jscomp.CodeGenerator|addExpr|com.google.javascript.rhino.Node,int|new:com.google.javascript.jscomp.CodeGenerator:com.google.javascript.jscomp.CodeConsumer",
        "M|com.google.javascript.jscomp.CodeGenerator|addIdentifier|java.lang.String|new:com.google.javascript.jscomp.CodeGenerator:com.google.javascript.jscomp.CodeConsumer",
        "M|com.google.javascript.jscomp.CodeGenerator|addJsString|java.lang.String|new:com.google.javascript.jscomp.CodeGenerator:com.google.javascript.jscomp.CodeConsumer",
        "M|com.google.javascript.jscomp.CodeGenerator|addLeftExpr|com.google.javascript.rhino.Node,int,com.google.javascript.jscomp.CodeGenerator$Context|new:com.google.javascript.jscomp.CodeGenerator:com.google.javascript.jscomp.CodeConsumer",
        "M|com.google.javascript.jscomp.CodeGenerator|addList|com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.CodeGenerator:com.google.javascript.jscomp.CodeConsumer",
        "M|com.google.javascript.jscomp.CodeGenerator|addList|com.google.javascript.rhino.Node,boolean|new:com.google.javascript.jscomp.CodeGenerator:com.google.javascript.jscomp.CodeConsumer",
        "M|com.google.javascript.jscomp.CodeGenerator|addList|com.google.javascript.rhino.Node,boolean,com.google.javascript.jscomp.CodeGenerator$Context|new:com.google.javascript.jscomp.CodeGenerator:com.google.javascript.jscomp.CodeConsumer",
        "M|com.google.javascript.jscomp.CodeGenerator|addNonEmptyStatement|com.google.javascript.rhino.Node,com.google.javascript.jscomp.CodeGenerator$Context,boolean|new:com.google.javascript.jscomp.CodeGenerator:com.google.javascript.jscomp.CodeConsumer",
        "M|com.google.javascript.jscomp.CodeGenerator|strEscape|java.lang.String,char,java.lang.String,java.lang.String,java.lang.String,java.nio.charset.CharsetEncoder|static",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 16) int w0, @InRange(minInt = 0, maxInt = 16) int w1, @InRange(minInt = 0, maxInt = 16) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
