package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 1 patched method(s), 15 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.apache.commons.math.optimization.direct.BOBYQAOptimizer|prelim|[D,[D|new:org.apache.commons.math.optimization.direct.BOBYQAOptimizer:int",
        "M|org.apache.commons.math.optimization.direct.BOBYQAOptimizer|altmov|int,double|new:org.apache.commons.math.optimization.direct.BOBYQAOptimizer:int",
        "M|org.apache.commons.math.optimization.direct.BOBYQAOptimizer|bobyqa|[D,[D|new:org.apache.commons.math.optimization.direct.BOBYQAOptimizer:int",
        "M|org.apache.commons.math.optimization.direct.BOBYQAOptimizer|bobyqb|[D,[D|new:org.apache.commons.math.optimization.direct.BOBYQAOptimizer:int",
        "M|org.apache.commons.math.optimization.direct.BOBYQAOptimizer|caller|int|static",
        "M|org.apache.commons.math.optimization.direct.BOBYQAOptimizer|doOptimize||new:org.apache.commons.math.optimization.direct.BOBYQAOptimizer:int",
        "M|org.apache.commons.math.optimization.direct.BOBYQAOptimizer|fillNewArray|int,double|static",
        "M|org.apache.commons.math.optimization.direct.BOBYQAOptimizer|printMethod||static",
        "M|org.apache.commons.math.optimization.direct.BOBYQAOptimizer|printState|int|static",
        "M|org.apache.commons.math.optimization.direct.BOBYQAOptimizer|setup|[D,[D|new:org.apache.commons.math.optimization.direct.BOBYQAOptimizer:int",
        "M|org.apache.commons.math.optimization.direct.BOBYQAOptimizer|trsbox|double,org.apache.commons.math.linear.ArrayRealVector,org.apache.commons.math.linear.ArrayRealVector,org.apache.commons.math.linear.ArrayRealVector,org.apache.commons.math.linear.ArrayRealVector,org.apache.commons.math.linear.ArrayRealVector|new:org.apache.commons.math.optimization.direct.BOBYQAOptimizer:int",
        "M|org.apache.commons.math.optimization.direct.BOBYQAOptimizer|update|double,double,int|new:org.apache.commons.math.optimization.direct.BOBYQAOptimizer:int",
        "C|org.apache.commons.math.optimization.direct.BOBYQAOptimizer|<init>|int",
        "C|org.apache.commons.math.optimization.direct.BOBYQAOptimizer|<init>|int,double,double",
        "M|org.apache.commons.math.optimization.direct.BOBYQAOptimizer|prelim|[D,[D|new:org.apache.commons.math.optimization.direct.BOBYQAOptimizer:int",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 14) int w0, @InRange(minInt = 0, maxInt = 14) int w1, @InRange(minInt = 0, maxInt = 14) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
