package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 2 patched method(s), 18 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.fasterxml.jackson.databind.deser.impl.CreatorCollector|verifyNonDup|com.fasterxml.jackson.databind.introspect.AnnotatedWithParams,int|new:com.fasterxml.jackson.databind.deser.impl.CreatorCollector:com.fasterxml.jackson.databind.BeanDescription,boolean",
        "M|com.fasterxml.jackson.databind.deser.impl.CreatorCollector|verifyNonDup|com.fasterxml.jackson.databind.introspect.AnnotatedWithParams,int,boolean|new:com.fasterxml.jackson.databind.deser.impl.CreatorCollector:com.fasterxml.jackson.databind.BeanDescription,boolean",
        "M|com.fasterxml.jackson.databind.deser.impl.CreatorCollector|_fixAccess|com.fasterxml.jackson.databind.introspect.AnnotatedMember|new:com.fasterxml.jackson.databind.deser.impl.CreatorCollector:com.fasterxml.jackson.databind.BeanDescription,boolean",
        "M|com.fasterxml.jackson.databind.deser.impl.CreatorCollector|addBooleanCreator|com.fasterxml.jackson.databind.introspect.AnnotatedWithParams|new:com.fasterxml.jackson.databind.deser.impl.CreatorCollector:com.fasterxml.jackson.databind.BeanDescription,boolean",
        "M|com.fasterxml.jackson.databind.deser.impl.CreatorCollector|addBooleanCreator|com.fasterxml.jackson.databind.introspect.AnnotatedWithParams,boolean|new:com.fasterxml.jackson.databind.deser.impl.CreatorCollector:com.fasterxml.jackson.databind.BeanDescription,boolean",
        "M|com.fasterxml.jackson.databind.deser.impl.CreatorCollector|addDelegatingCreator|com.fasterxml.jackson.databind.introspect.AnnotatedWithParams,boolean,[Lcom.fasterxml.jackson.databind.deser.CreatorProperty;|new:com.fasterxml.jackson.databind.deser.impl.CreatorCollector:com.fasterxml.jackson.databind.BeanDescription,boolean",
        "M|com.fasterxml.jackson.databind.deser.impl.CreatorCollector|addDelegatingCreator|com.fasterxml.jackson.databind.introspect.AnnotatedWithParams,[Lcom.fasterxml.jackson.databind.deser.CreatorProperty;|new:com.fasterxml.jackson.databind.deser.impl.CreatorCollector:com.fasterxml.jackson.databind.BeanDescription,boolean",
        "M|com.fasterxml.jackson.databind.deser.impl.CreatorCollector|addDoubleCreator|com.fasterxml.jackson.databind.introspect.AnnotatedWithParams|new:com.fasterxml.jackson.databind.deser.impl.CreatorCollector:com.fasterxml.jackson.databind.BeanDescription,boolean",
        "M|com.fasterxml.jackson.databind.deser.impl.CreatorCollector|addDoubleCreator|com.fasterxml.jackson.databind.introspect.AnnotatedWithParams,boolean|new:com.fasterxml.jackson.databind.deser.impl.CreatorCollector:com.fasterxml.jackson.databind.BeanDescription,boolean",
        "M|com.fasterxml.jackson.databind.deser.impl.CreatorCollector|addIncompeteParameter|com.fasterxml.jackson.databind.introspect.AnnotatedParameter|new:com.fasterxml.jackson.databind.deser.impl.CreatorCollector:com.fasterxml.jackson.databind.BeanDescription,boolean",
        "M|com.fasterxml.jackson.databind.deser.impl.CreatorCollector|addIntCreator|com.fasterxml.jackson.databind.introspect.AnnotatedWithParams|new:com.fasterxml.jackson.databind.deser.impl.CreatorCollector:com.fasterxml.jackson.databind.BeanDescription,boolean",
        "M|com.fasterxml.jackson.databind.deser.impl.CreatorCollector|addIntCreator|com.fasterxml.jackson.databind.introspect.AnnotatedWithParams,boolean|new:com.fasterxml.jackson.databind.deser.impl.CreatorCollector:com.fasterxml.jackson.databind.BeanDescription,boolean",
        "M|com.fasterxml.jackson.databind.deser.impl.CreatorCollector|addLongCreator|com.fasterxml.jackson.databind.introspect.AnnotatedWithParams|new:com.fasterxml.jackson.databind.deser.impl.CreatorCollector:com.fasterxml.jackson.databind.BeanDescription,boolean",
        "M|com.fasterxml.jackson.databind.deser.impl.CreatorCollector|addLongCreator|com.fasterxml.jackson.databind.introspect.AnnotatedWithParams,boolean|new:com.fasterxml.jackson.databind.deser.impl.CreatorCollector:com.fasterxml.jackson.databind.BeanDescription,boolean",
        "M|com.fasterxml.jackson.databind.deser.impl.CreatorCollector|addPropertyCreator|com.fasterxml.jackson.databind.introspect.AnnotatedWithParams,boolean,[Lcom.fasterxml.jackson.databind.deser.CreatorProperty;|new:com.fasterxml.jackson.databind.deser.impl.CreatorCollector:com.fasterxml.jackson.databind.BeanDescription,boolean",
        "M|com.fasterxml.jackson.databind.deser.impl.CreatorCollector|addPropertyCreator|com.fasterxml.jackson.databind.introspect.AnnotatedWithParams,[Lcom.fasterxml.jackson.databind.deser.CreatorProperty;|new:com.fasterxml.jackson.databind.deser.impl.CreatorCollector:com.fasterxml.jackson.databind.BeanDescription,boolean",
        "M|com.fasterxml.jackson.databind.deser.impl.CreatorCollector|verifyNonDup|com.fasterxml.jackson.databind.introspect.AnnotatedWithParams,int|new:com.fasterxml.jackson.databind.deser.impl.CreatorCollector:com.fasterxml.jackson.databind.BeanDescription,boolean",
        "M|com.fasterxml.jackson.databind.deser.impl.CreatorCollector|verifyNonDup|com.fasterxml.jackson.databind.introspect.AnnotatedWithParams,int,boolean|new:com.fasterxml.jackson.databind.deser.impl.CreatorCollector:com.fasterxml.jackson.databind.BeanDescription,boolean",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 17) int w0, @InRange(minInt = 0, maxInt = 17) int w1, @InRange(minInt = 0, maxInt = 17) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
