package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 7 patched method(s), 23 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.fasterxml.jackson.databind.deser.CreatorProperty|withValueDeserializer|com.fasterxml.jackson.databind.JsonDeserializer|new:com.fasterxml.jackson.databind.deser.CreatorProperty:com.fasterxml.jackson.databind.deser.CreatorProperty,com.fasterxml.jackson.databind.PropertyName",
        "M|com.fasterxml.jackson.databind.deser.impl.FieldProperty|withValueDeserializer|com.fasterxml.jackson.databind.JsonDeserializer|new:com.fasterxml.jackson.databind.deser.impl.FieldProperty:com.fasterxml.jackson.databind.deser.impl.FieldProperty",
        "M|com.fasterxml.jackson.databind.deser.impl.MethodProperty|withValueDeserializer|com.fasterxml.jackson.databind.JsonDeserializer|new:com.fasterxml.jackson.databind.deser.impl.MethodProperty:com.fasterxml.jackson.databind.deser.impl.MethodProperty,java.lang.reflect.Method",
        "M|com.fasterxml.jackson.databind.deser.impl.ObjectIdReferenceProperty|withValueDeserializer|com.fasterxml.jackson.databind.JsonDeserializer|new:com.fasterxml.jackson.databind.deser.impl.ObjectIdReferenceProperty:com.fasterxml.jackson.databind.deser.impl.ObjectIdReferenceProperty,com.fasterxml.jackson.databind.PropertyName",
        "M|com.fasterxml.jackson.databind.deser.impl.ObjectIdValueProperty|withValueDeserializer|com.fasterxml.jackson.databind.JsonDeserializer|new:com.fasterxml.jackson.databind.deser.impl.ObjectIdValueProperty:com.fasterxml.jackson.databind.deser.impl.ObjectIdReader,com.fasterxml.jackson.databind.PropertyMetadata",
        "M|com.fasterxml.jackson.databind.deser.impl.SetterlessProperty|withValueDeserializer|com.fasterxml.jackson.databind.JsonDeserializer|new:com.fasterxml.jackson.databind.deser.impl.SetterlessProperty:com.fasterxml.jackson.databind.deser.impl.SetterlessProperty,com.fasterxml.jackson.databind.PropertyName",
        "M|com.fasterxml.jackson.databind.deser.std.AtomicReferenceDeserializer|getNullValue|com.fasterxml.jackson.databind.DeserializationContext|new:com.fasterxml.jackson.databind.deser.std.AtomicReferenceDeserializer:com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.deser.ValueInstantiator,com.fasterxml.jackson.databind.jsontype.TypeDeserializer,com.fasterxml.jackson.databind.JsonDeserializer",
        "M|com.fasterxml.jackson.databind.deser.CreatorProperty|_reportMissingSetter|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext|new:com.fasterxml.jackson.databind.deser.CreatorProperty:com.fasterxml.jackson.databind.deser.CreatorProperty,com.fasterxml.jackson.databind.PropertyName",
        "M|com.fasterxml.jackson.databind.deser.CreatorProperty|_verifySetter||new:com.fasterxml.jackson.databind.deser.CreatorProperty:com.fasterxml.jackson.databind.deser.CreatorProperty,com.fasterxml.jackson.databind.PropertyName",
        "M|com.fasterxml.jackson.databind.deser.CreatorProperty|deserializeAndSet|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,java.lang.Object|new:com.fasterxml.jackson.databind.deser.CreatorProperty:com.fasterxml.jackson.databind.deser.CreatorProperty,com.fasterxml.jackson.databind.PropertyName",
        "M|com.fasterxml.jackson.databind.deser.CreatorProperty|deserializeSetAndReturn|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,java.lang.Object|new:com.fasterxml.jackson.databind.deser.CreatorProperty:com.fasterxml.jackson.databind.deser.CreatorProperty,com.fasterxml.jackson.databind.PropertyName",
        "M|com.fasterxml.jackson.databind.deser.CreatorProperty|findInjectableValue|com.fasterxml.jackson.databind.DeserializationContext,java.lang.Object|new:com.fasterxml.jackson.databind.deser.CreatorProperty:com.fasterxml.jackson.databind.deser.CreatorProperty,com.fasterxml.jackson.databind.PropertyName",
        "M|com.fasterxml.jackson.databind.deser.CreatorProperty|fixAccess|com.fasterxml.jackson.databind.DeserializationConfig|new:com.fasterxml.jackson.databind.deser.CreatorProperty:com.fasterxml.jackson.databind.deser.CreatorProperty,com.fasterxml.jackson.databind.PropertyName",
        "M|com.fasterxml.jackson.databind.deser.CreatorProperty|getAnnotation|java.lang.Class|new:com.fasterxml.jackson.databind.deser.CreatorProperty:com.fasterxml.jackson.databind.deser.CreatorProperty,com.fasterxml.jackson.databind.PropertyName",
        "M|com.fasterxml.jackson.databind.deser.CreatorProperty|getCreatorIndex||new:com.fasterxml.jackson.databind.deser.CreatorProperty:com.fasterxml.jackson.databind.deser.CreatorProperty,com.fasterxml.jackson.databind.PropertyName",
        "M|com.fasterxml.jackson.databind.deser.CreatorProperty|getInjectableValueId||new:com.fasterxml.jackson.databind.deser.CreatorProperty:com.fasterxml.jackson.databind.deser.CreatorProperty,com.fasterxml.jackson.databind.PropertyName",
        "M|com.fasterxml.jackson.databind.deser.CreatorProperty|withValueDeserializer|com.fasterxml.jackson.databind.JsonDeserializer|new:com.fasterxml.jackson.databind.deser.CreatorProperty:com.fasterxml.jackson.databind.deser.CreatorProperty,com.fasterxml.jackson.databind.PropertyName",
        "M|com.fasterxml.jackson.databind.deser.impl.FieldProperty|withValueDeserializer|com.fasterxml.jackson.databind.JsonDeserializer|new:com.fasterxml.jackson.databind.deser.impl.FieldProperty:com.fasterxml.jackson.databind.deser.impl.FieldProperty",
        "M|com.fasterxml.jackson.databind.deser.impl.MethodProperty|withValueDeserializer|com.fasterxml.jackson.databind.JsonDeserializer|new:com.fasterxml.jackson.databind.deser.impl.MethodProperty:com.fasterxml.jackson.databind.deser.impl.MethodProperty,java.lang.reflect.Method",
        "M|com.fasterxml.jackson.databind.deser.impl.ObjectIdReferenceProperty|withValueDeserializer|com.fasterxml.jackson.databind.JsonDeserializer|new:com.fasterxml.jackson.databind.deser.impl.ObjectIdReferenceProperty:com.fasterxml.jackson.databind.deser.impl.ObjectIdReferenceProperty,com.fasterxml.jackson.databind.PropertyName",
        "M|com.fasterxml.jackson.databind.deser.impl.ObjectIdValueProperty|withValueDeserializer|com.fasterxml.jackson.databind.JsonDeserializer|new:com.fasterxml.jackson.databind.deser.impl.ObjectIdValueProperty:com.fasterxml.jackson.databind.deser.impl.ObjectIdReader,com.fasterxml.jackson.databind.PropertyMetadata",
        "M|com.fasterxml.jackson.databind.deser.impl.SetterlessProperty|withValueDeserializer|com.fasterxml.jackson.databind.JsonDeserializer|new:com.fasterxml.jackson.databind.deser.impl.SetterlessProperty:com.fasterxml.jackson.databind.deser.impl.SetterlessProperty,com.fasterxml.jackson.databind.PropertyName",
        "M|com.fasterxml.jackson.databind.deser.std.AtomicReferenceDeserializer|getNullValue|com.fasterxml.jackson.databind.DeserializationContext|new:com.fasterxml.jackson.databind.deser.std.AtomicReferenceDeserializer:com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.deser.ValueInstantiator,com.fasterxml.jackson.databind.jsontype.TypeDeserializer,com.fasterxml.jackson.databind.JsonDeserializer",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 22) int w0, @InRange(minInt = 0, maxInt = 22) int w1, @InRange(minInt = 0, maxInt = 22) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
