package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 1 patched method(s), 17 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.apache.commons.math3.geometry.euclidean.threed.Line|revert||new:org.apache.commons.math3.geometry.euclidean.threed.Line:org.apache.commons.math3.geometry.euclidean.threed.Line",
        "M|org.apache.commons.math3.geometry.euclidean.threed.Line|closestPoint|org.apache.commons.math3.geometry.euclidean.threed.Line|new:org.apache.commons.math3.geometry.euclidean.threed.Line:org.apache.commons.math3.geometry.euclidean.threed.Line",
        "M|org.apache.commons.math3.geometry.euclidean.threed.Line|contains|org.apache.commons.math3.geometry.euclidean.threed.Vector3D|new:org.apache.commons.math3.geometry.euclidean.threed.Line:org.apache.commons.math3.geometry.euclidean.threed.Line",
        "M|org.apache.commons.math3.geometry.euclidean.threed.Line|distance|org.apache.commons.math3.geometry.euclidean.threed.Line|new:org.apache.commons.math3.geometry.euclidean.threed.Line:org.apache.commons.math3.geometry.euclidean.threed.Line",
        "M|org.apache.commons.math3.geometry.euclidean.threed.Line|distance|org.apache.commons.math3.geometry.euclidean.threed.Vector3D|new:org.apache.commons.math3.geometry.euclidean.threed.Line:org.apache.commons.math3.geometry.euclidean.threed.Line",
        "M|org.apache.commons.math3.geometry.euclidean.threed.Line|getAbscissa|org.apache.commons.math3.geometry.euclidean.threed.Vector3D|new:org.apache.commons.math3.geometry.euclidean.threed.Line:org.apache.commons.math3.geometry.euclidean.threed.Line",
        "M|org.apache.commons.math3.geometry.euclidean.threed.Line|getDirection||new:org.apache.commons.math3.geometry.euclidean.threed.Line:org.apache.commons.math3.geometry.euclidean.threed.Line",
        "M|org.apache.commons.math3.geometry.euclidean.threed.Line|getOrigin||new:org.apache.commons.math3.geometry.euclidean.threed.Line:org.apache.commons.math3.geometry.euclidean.threed.Line",
        "M|org.apache.commons.math3.geometry.euclidean.threed.Line|intersection|org.apache.commons.math3.geometry.euclidean.threed.Line|new:org.apache.commons.math3.geometry.euclidean.threed.Line:org.apache.commons.math3.geometry.euclidean.threed.Line",
        "M|org.apache.commons.math3.geometry.euclidean.threed.Line|isSimilarTo|org.apache.commons.math3.geometry.euclidean.threed.Line|new:org.apache.commons.math3.geometry.euclidean.threed.Line:org.apache.commons.math3.geometry.euclidean.threed.Line",
        "M|org.apache.commons.math3.geometry.euclidean.threed.Line|pointAt|double|new:org.apache.commons.math3.geometry.euclidean.threed.Line:org.apache.commons.math3.geometry.euclidean.threed.Line",
        "M|org.apache.commons.math3.geometry.euclidean.threed.Line|reset|org.apache.commons.math3.geometry.euclidean.threed.Vector3D,org.apache.commons.math3.geometry.euclidean.threed.Vector3D|new:org.apache.commons.math3.geometry.euclidean.threed.Line:org.apache.commons.math3.geometry.euclidean.threed.Line",
        "M|org.apache.commons.math3.geometry.euclidean.threed.Line|toSpace|org.apache.commons.math3.geometry.Vector|new:org.apache.commons.math3.geometry.euclidean.threed.Line:org.apache.commons.math3.geometry.euclidean.threed.Line",
        "M|org.apache.commons.math3.geometry.euclidean.threed.Line|toSubSpace|org.apache.commons.math3.geometry.Vector|new:org.apache.commons.math3.geometry.euclidean.threed.Line:org.apache.commons.math3.geometry.euclidean.threed.Line",
        "M|org.apache.commons.math3.geometry.euclidean.threed.Line|wholeLine||new:org.apache.commons.math3.geometry.euclidean.threed.Line:org.apache.commons.math3.geometry.euclidean.threed.Line",
        "C|org.apache.commons.math3.geometry.euclidean.threed.Line|<init>|org.apache.commons.math3.geometry.euclidean.threed.Vector3D,org.apache.commons.math3.geometry.euclidean.threed.Vector3D",
        "M|org.apache.commons.math3.geometry.euclidean.threed.Line|revert||new:org.apache.commons.math3.geometry.euclidean.threed.Line:org.apache.commons.math3.geometry.euclidean.threed.Line",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 16) int w0, @InRange(minInt = 0, maxInt = 16) int w1, @InRange(minInt = 0, maxInt = 16) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
