package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 2 patched method(s), 18 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.fasterxml.jackson.databind.deser.ValueInstantiator|canInstantiate||new:com.fasterxml.jackson.databind.deser.ValueInstantiator$Base:java.lang.Class",
        "M|com.fasterxml.jackson.databind.deser.std.StdValueInstantiator|canInstantiate||new:com.fasterxml.jackson.databind.deser.std.StdValueInstantiator:com.fasterxml.jackson.databind.deser.std.StdValueInstantiator",
        "M|com.fasterxml.jackson.databind.deser.ValueInstantiator|_createFromStringFallbacks|com.fasterxml.jackson.databind.DeserializationContext,java.lang.String|new:com.fasterxml.jackson.databind.deser.ValueInstantiator$Base:java.lang.Class",
        "M|com.fasterxml.jackson.databind.deser.ValueInstantiator|canCreateFromBoolean||new:com.fasterxml.jackson.databind.deser.ValueInstantiator$Base:java.lang.Class",
        "M|com.fasterxml.jackson.databind.deser.ValueInstantiator|canCreateFromDouble||new:com.fasterxml.jackson.databind.deser.ValueInstantiator$Base:java.lang.Class",
        "M|com.fasterxml.jackson.databind.deser.ValueInstantiator|canCreateFromInt||new:com.fasterxml.jackson.databind.deser.ValueInstantiator$Base:java.lang.Class",
        "M|com.fasterxml.jackson.databind.deser.ValueInstantiator|canCreateFromLong||new:com.fasterxml.jackson.databind.deser.ValueInstantiator$Base:java.lang.Class",
        "M|com.fasterxml.jackson.databind.deser.ValueInstantiator|canCreateFromObjectWith||new:com.fasterxml.jackson.databind.deser.ValueInstantiator$Base:java.lang.Class",
        "M|com.fasterxml.jackson.databind.deser.ValueInstantiator|canCreateFromString||new:com.fasterxml.jackson.databind.deser.ValueInstantiator$Base:java.lang.Class",
        "M|com.fasterxml.jackson.databind.deser.ValueInstantiator|canCreateUsingArrayDelegate||new:com.fasterxml.jackson.databind.deser.ValueInstantiator$Base:java.lang.Class",
        "M|com.fasterxml.jackson.databind.deser.ValueInstantiator|canCreateUsingDefault||new:com.fasterxml.jackson.databind.deser.ValueInstantiator$Base:java.lang.Class",
        "M|com.fasterxml.jackson.databind.deser.ValueInstantiator|canCreateUsingDelegate||new:com.fasterxml.jackson.databind.deser.ValueInstantiator$Base:java.lang.Class",
        "M|com.fasterxml.jackson.databind.deser.ValueInstantiator|createFromBoolean|com.fasterxml.jackson.databind.DeserializationContext,boolean|new:com.fasterxml.jackson.databind.deser.ValueInstantiator$Base:java.lang.Class",
        "M|com.fasterxml.jackson.databind.deser.ValueInstantiator|createFromDouble|com.fasterxml.jackson.databind.DeserializationContext,double|new:com.fasterxml.jackson.databind.deser.ValueInstantiator$Base:java.lang.Class",
        "M|com.fasterxml.jackson.databind.deser.ValueInstantiator|createFromInt|com.fasterxml.jackson.databind.DeserializationContext,int|new:com.fasterxml.jackson.databind.deser.ValueInstantiator$Base:java.lang.Class",
        "M|com.fasterxml.jackson.databind.deser.ValueInstantiator|createFromLong|com.fasterxml.jackson.databind.DeserializationContext,long|new:com.fasterxml.jackson.databind.deser.ValueInstantiator$Base:java.lang.Class",
        "M|com.fasterxml.jackson.databind.deser.ValueInstantiator|canInstantiate||new:com.fasterxml.jackson.databind.deser.ValueInstantiator$Base:java.lang.Class",
        "M|com.fasterxml.jackson.databind.deser.std.StdValueInstantiator|canInstantiate||new:com.fasterxml.jackson.databind.deser.std.StdValueInstantiator:com.fasterxml.jackson.databind.deser.std.StdValueInstantiator",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 17) int w0, @InRange(minInt = 0, maxInt = 17) int w1, @InRange(minInt = 0, maxInt = 17) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
