package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 1 patched method(s), 17 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.mockito.internal.invocation.Invocation|callRealMethod||new:org.mockito.internal.invocation.Invocation:java.lang.Object,org.mockito.internal.invocation.MockitoMethod,[Ljava.lang.Object;,int,org.mockito.internal.invocation.realmethod.RealMethod",
        "M|org.mockito.internal.invocation.Invocation|argumentsToMatchers||new:org.mockito.internal.invocation.Invocation:java.lang.Object,org.mockito.internal.invocation.MockitoMethod,[Ljava.lang.Object;,int,org.mockito.internal.invocation.realmethod.RealMethod",
        "M|org.mockito.internal.invocation.Invocation|equalArguments|[Ljava.lang.Object;|new:org.mockito.internal.invocation.Invocation:java.lang.Object,org.mockito.internal.invocation.MockitoMethod,[Ljava.lang.Object;,int,org.mockito.internal.invocation.realmethod.RealMethod",
        "M|org.mockito.internal.invocation.Invocation|equals|java.lang.Object|new:org.mockito.internal.invocation.Invocation:java.lang.Object,org.mockito.internal.invocation.MockitoMethod,[Ljava.lang.Object;,int,org.mockito.internal.invocation.realmethod.RealMethod",
        "M|org.mockito.internal.invocation.Invocation|expandVarArgs|boolean,[Ljava.lang.Object;|static",
        "M|org.mockito.internal.invocation.Invocation|getArguments||new:org.mockito.internal.invocation.Invocation:java.lang.Object,org.mockito.internal.invocation.MockitoMethod,[Ljava.lang.Object;,int,org.mockito.internal.invocation.realmethod.RealMethod",
        "M|org.mockito.internal.invocation.Invocation|getArgumentsCount||new:org.mockito.internal.invocation.Invocation:java.lang.Object,org.mockito.internal.invocation.MockitoMethod,[Ljava.lang.Object;,int,org.mockito.internal.invocation.realmethod.RealMethod",
        "M|org.mockito.internal.invocation.Invocation|getLocation||new:org.mockito.internal.invocation.Invocation:java.lang.Object,org.mockito.internal.invocation.MockitoMethod,[Ljava.lang.Object;,int,org.mockito.internal.invocation.realmethod.RealMethod",
        "M|org.mockito.internal.invocation.Invocation|getMethod||new:org.mockito.internal.invocation.Invocation:java.lang.Object,org.mockito.internal.invocation.MockitoMethod,[Ljava.lang.Object;,int,org.mockito.internal.invocation.realmethod.RealMethod",
        "M|org.mockito.internal.invocation.Invocation|getMethodName||new:org.mockito.internal.invocation.Invocation:java.lang.Object,org.mockito.internal.invocation.MockitoMethod,[Ljava.lang.Object;,int,org.mockito.internal.invocation.realmethod.RealMethod",
        "M|org.mockito.internal.invocation.Invocation|getMock||new:org.mockito.internal.invocation.Invocation:java.lang.Object,org.mockito.internal.invocation.MockitoMethod,[Ljava.lang.Object;,int,org.mockito.internal.invocation.realmethod.RealMethod",
        "M|org.mockito.internal.invocation.Invocation|getRawArguments||new:org.mockito.internal.invocation.Invocation:java.lang.Object,org.mockito.internal.invocation.MockitoMethod,[Ljava.lang.Object;,int,org.mockito.internal.invocation.realmethod.RealMethod",
        "M|org.mockito.internal.invocation.Invocation|getSequenceNumber||new:org.mockito.internal.invocation.Invocation:java.lang.Object,org.mockito.internal.invocation.MockitoMethod,[Ljava.lang.Object;,int,org.mockito.internal.invocation.realmethod.RealMethod",
        "M|org.mockito.internal.invocation.Invocation|hashCode||new:org.mockito.internal.invocation.Invocation:java.lang.Object,org.mockito.internal.invocation.MockitoMethod,[Ljava.lang.Object;,int,org.mockito.internal.invocation.realmethod.RealMethod",
        "M|org.mockito.internal.invocation.Invocation|isToString|org.mockito.invocation.InvocationOnMock|static",
        "M|org.mockito.internal.invocation.Invocation|isValidException|java.lang.Throwable|new:org.mockito.internal.invocation.Invocation:java.lang.Object,org.mockito.internal.invocation.MockitoMethod,[Ljava.lang.Object;,int,org.mockito.internal.invocation.realmethod.RealMethod",
        "M|org.mockito.internal.invocation.Invocation|callRealMethod||new:org.mockito.internal.invocation.Invocation:java.lang.Object,org.mockito.internal.invocation.MockitoMethod,[Ljava.lang.Object;,int,org.mockito.internal.invocation.realmethod.RealMethod",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 16) int w0, @InRange(minInt = 0, maxInt = 16) int w1, @InRange(minInt = 0, maxInt = 16) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
