package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 7 patched method(s), 23 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|_delegateDeserializer||new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|deserializeFromArray|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext|new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|deserializeFromBoolean|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext|new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|deserializeFromDouble|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext|new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|deserializeFromNumber|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext|new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|deserializeFromObjectUsingNonDefault|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext|new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|deserializeFromString|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext|new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|_convertObjectId|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,java.lang.Object,com.fasterxml.jackson.databind.JsonDeserializer|new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|_deserializeUsingPropertyBased|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext|new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|_findDelegateDeserializer|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.introspect.AnnotatedWithParams|new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|_findSubclassDeserializer|com.fasterxml.jackson.databind.DeserializationContext,java.lang.Object,com.fasterxml.jackson.databind.util.TokenBuffer|new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|_handleTypedObjectId|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,java.lang.Object,java.lang.Object|new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|_resolveInnerClassValuedProperty|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.deser.SettableBeanProperty|new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|_resolveManagedReferenceProperty|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.deser.SettableBeanProperty|new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|_resolveUnwrappedProperty|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.deser.SettableBeanProperty|new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|_resolvedObjectIdProperty|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.deser.SettableBeanProperty|new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|_delegateDeserializer||new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|deserializeFromArray|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext|new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|deserializeFromBoolean|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext|new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|deserializeFromDouble|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext|new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|deserializeFromNumber|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext|new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|deserializeFromObjectUsingNonDefault|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext|new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerBase|deserializeFromString|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext|new:com.fasterxml.jackson.databind.deser.BeanDeserializer:com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 22) int w0, @InRange(minInt = 0, maxInt = 22) int w1, @InRange(minInt = 0, maxInt = 22) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
