package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 1 patched method(s), 17 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.apache.commons.collections.CollectionUtils|removeAll|java.util.Collection,java.util.Collection|static",
        "M|org.apache.commons.collections.CollectionUtils|addAll|java.util.Collection,[Ljava.lang.Object;|static",
        "M|org.apache.commons.collections.CollectionUtils|addAll|java.util.Collection,java.util.Enumeration|static",
        "M|org.apache.commons.collections.CollectionUtils|addAll|java.util.Collection,java.util.Iterator|static",
        "M|org.apache.commons.collections.CollectionUtils|addIgnoreNull|java.util.Collection,java.lang.Object|static",
        "M|org.apache.commons.collections.CollectionUtils|cardinality|java.lang.Object,java.util.Collection|static",
        "M|org.apache.commons.collections.CollectionUtils|collect|java.util.Collection,org.apache.commons.collections.Transformer|static",
        "M|org.apache.commons.collections.CollectionUtils|collect|java.util.Collection,org.apache.commons.collections.Transformer,java.util.Collection|static",
        "M|org.apache.commons.collections.CollectionUtils|collect|java.util.Iterator,org.apache.commons.collections.Transformer|static",
        "M|org.apache.commons.collections.CollectionUtils|collect|java.util.Iterator,org.apache.commons.collections.Transformer,java.util.Collection|static",
        "M|org.apache.commons.collections.CollectionUtils|containsAny|java.util.Collection,java.util.Collection|static",
        "M|org.apache.commons.collections.CollectionUtils|countMatches|java.util.Collection,org.apache.commons.collections.Predicate|static",
        "M|org.apache.commons.collections.CollectionUtils|disjunction|java.util.Collection,java.util.Collection|static",
        "M|org.apache.commons.collections.CollectionUtils|exists|java.util.Collection,org.apache.commons.collections.Predicate|static",
        "M|org.apache.commons.collections.CollectionUtils|filter|java.util.Collection,org.apache.commons.collections.Predicate|static",
        "M|org.apache.commons.collections.CollectionUtils|find|java.util.Collection,org.apache.commons.collections.Predicate|static",
        "M|org.apache.commons.collections.CollectionUtils|removeAll|java.util.Collection,java.util.Collection|static",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 16) int w0, @InRange(minInt = 0, maxInt = 16) int w1, @InRange(minInt = 0, maxInt = 16) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
