package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 8 patched method(s), 24 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.fasterxml.jackson.core.base.ParserBase|_reportTooLongIntegral|int,java.lang.String|new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserBase|convertNumberToInt||new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserMinimalBase|reportOverflowInt||new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserMinimalBase|reportOverflowInt|java.lang.String|new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserMinimalBase|reportOverflowInt|java.lang.String,com.fasterxml.jackson.core.JsonToken|new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserMinimalBase|reportOverflowLong||new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserMinimalBase|reportOverflowLong|java.lang.String|new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserMinimalBase|reportOverflowLong|java.lang.String,com.fasterxml.jackson.core.JsonToken|new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserBase|_checkStdFeatureChanges|int,int|new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserBase|_closeInput||new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserBase|_decodeBase64Escape|com.fasterxml.jackson.core.Base64Variant,char,int|new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserBase|_decodeBase64Escape|com.fasterxml.jackson.core.Base64Variant,int,int|new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserBase|_decodeEscaped||new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserBase|_eofAsNextChar||new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserBase|_finishString||new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserBase|_getByteArrayBuilder||new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserBase|_reportTooLongIntegral|int,java.lang.String|new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserBase|convertNumberToInt||new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserMinimalBase|reportOverflowInt||new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserMinimalBase|reportOverflowInt|java.lang.String|new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserMinimalBase|reportOverflowInt|java.lang.String,com.fasterxml.jackson.core.JsonToken|new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserMinimalBase|reportOverflowLong||new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserMinimalBase|reportOverflowLong|java.lang.String|new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
        "M|com.fasterxml.jackson.core.base.ParserMinimalBase|reportOverflowLong|java.lang.String,com.fasterxml.jackson.core.JsonToken|new:com.fasterxml.jackson.core.json.ReaderBasedJsonParser:com.fasterxml.jackson.core.io.IOContext,int,java.io.Reader,com.fasterxml.jackson.core.ObjectCodec,com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 23) int w0, @InRange(minInt = 0, maxInt = 23) int w1, @InRange(minInt = 0, maxInt = 23) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
