package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 1 patched method(s), 17 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.fasterxml.jackson.databind.deser.BasicDeserializerFactory|createKeyDeserializer|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JavaType|fld:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:instance",
        "M|com.fasterxml.jackson.databind.deser.BasicDeserializerFactory|_addDeserializerConstructors|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.BeanDescription,com.fasterxml.jackson.databind.introspect.VisibilityChecker,com.fasterxml.jackson.databind.AnnotationIntrospector,com.fasterxml.jackson.databind.deser.impl.CreatorCollector,java.util.Map|fld:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:instance",
        "M|com.fasterxml.jackson.databind.deser.BasicDeserializerFactory|_addDeserializerFactoryMethods|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.BeanDescription,com.fasterxml.jackson.databind.introspect.VisibilityChecker,com.fasterxml.jackson.databind.AnnotationIntrospector,com.fasterxml.jackson.databind.deser.impl.CreatorCollector,java.util.Map|fld:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:instance",
        "M|com.fasterxml.jackson.databind.deser.BasicDeserializerFactory|_checkIfCreatorPropertyBased|com.fasterxml.jackson.databind.AnnotationIntrospector,com.fasterxml.jackson.databind.introspect.AnnotatedWithParams,com.fasterxml.jackson.databind.introspect.BeanPropertyDefinition|fld:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:instance",
        "M|com.fasterxml.jackson.databind.deser.BasicDeserializerFactory|_checkImplicitlyNamedConstructors|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.BeanDescription,com.fasterxml.jackson.databind.introspect.VisibilityChecker,com.fasterxml.jackson.databind.AnnotationIntrospector,com.fasterxml.jackson.databind.deser.impl.CreatorCollector,java.util.List|fld:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:instance",
        "M|com.fasterxml.jackson.databind.deser.BasicDeserializerFactory|_constructDefaultValueInstantiator|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.BeanDescription|fld:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:instance",
        "M|com.fasterxml.jackson.databind.deser.BasicDeserializerFactory|_createEnumKeyDeserializer|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JavaType|fld:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:instance",
        "M|com.fasterxml.jackson.databind.deser.BasicDeserializerFactory|_findCreatorsFromProperties|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.BeanDescription|fld:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:instance",
        "M|com.fasterxml.jackson.databind.deser.BasicDeserializerFactory|_findCustomArrayDeserializer|com.fasterxml.jackson.databind.type.ArrayType,com.fasterxml.jackson.databind.DeserializationConfig,com.fasterxml.jackson.databind.BeanDescription,com.fasterxml.jackson.databind.jsontype.TypeDeserializer,com.fasterxml.jackson.databind.JsonDeserializer|fld:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:instance",
        "M|com.fasterxml.jackson.databind.deser.BasicDeserializerFactory|_findCustomBeanDeserializer|com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.DeserializationConfig,com.fasterxml.jackson.databind.BeanDescription|fld:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:instance",
        "M|com.fasterxml.jackson.databind.deser.BasicDeserializerFactory|_findCustomCollectionDeserializer|com.fasterxml.jackson.databind.type.CollectionType,com.fasterxml.jackson.databind.DeserializationConfig,com.fasterxml.jackson.databind.BeanDescription,com.fasterxml.jackson.databind.jsontype.TypeDeserializer,com.fasterxml.jackson.databind.JsonDeserializer|fld:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:instance",
        "M|com.fasterxml.jackson.databind.deser.BasicDeserializerFactory|_findCustomCollectionLikeDeserializer|com.fasterxml.jackson.databind.type.CollectionLikeType,com.fasterxml.jackson.databind.DeserializationConfig,com.fasterxml.jackson.databind.BeanDescription,com.fasterxml.jackson.databind.jsontype.TypeDeserializer,com.fasterxml.jackson.databind.JsonDeserializer|fld:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:instance",
        "M|com.fasterxml.jackson.databind.deser.BasicDeserializerFactory|_findCustomEnumDeserializer|java.lang.Class,com.fasterxml.jackson.databind.DeserializationConfig,com.fasterxml.jackson.databind.BeanDescription|fld:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:instance",
        "M|com.fasterxml.jackson.databind.deser.BasicDeserializerFactory|_findCustomMapDeserializer|com.fasterxml.jackson.databind.type.MapType,com.fasterxml.jackson.databind.DeserializationConfig,com.fasterxml.jackson.databind.BeanDescription,com.fasterxml.jackson.databind.KeyDeserializer,com.fasterxml.jackson.databind.jsontype.TypeDeserializer,com.fasterxml.jackson.databind.JsonDeserializer|fld:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:instance",
        "M|com.fasterxml.jackson.databind.deser.BasicDeserializerFactory|_findCustomMapLikeDeserializer|com.fasterxml.jackson.databind.type.MapLikeType,com.fasterxml.jackson.databind.DeserializationConfig,com.fasterxml.jackson.databind.BeanDescription,com.fasterxml.jackson.databind.KeyDeserializer,com.fasterxml.jackson.databind.jsontype.TypeDeserializer,com.fasterxml.jackson.databind.JsonDeserializer|fld:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:instance",
        "M|com.fasterxml.jackson.databind.deser.BasicDeserializerFactory|_findCustomReferenceDeserializer|com.fasterxml.jackson.databind.type.ReferenceType,com.fasterxml.jackson.databind.DeserializationConfig,com.fasterxml.jackson.databind.BeanDescription,com.fasterxml.jackson.databind.jsontype.TypeDeserializer,com.fasterxml.jackson.databind.JsonDeserializer|fld:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:instance",
        "M|com.fasterxml.jackson.databind.deser.BasicDeserializerFactory|createKeyDeserializer|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JavaType|fld:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:instance",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 16) int w0, @InRange(minInt = 0, maxInt = 16) int w1, @InRange(minInt = 0, maxInt = 16) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
