package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 5 patched method(s), 21 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.fasterxml.jackson.databind.MappingIterator|_resync||new:com.fasterxml.jackson.databind.MappingIterator:com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JsonDeserializer,boolean,java.lang.Object",
        "M|com.fasterxml.jackson.databind.MappingIterator|close||new:com.fasterxml.jackson.databind.MappingIterator:com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JsonDeserializer,boolean,java.lang.Object",
        "M|com.fasterxml.jackson.databind.MappingIterator|hasNextValue||new:com.fasterxml.jackson.databind.MappingIterator:com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JsonDeserializer,boolean,java.lang.Object",
        "M|com.fasterxml.jackson.databind.MappingIterator|nextValue||new:com.fasterxml.jackson.databind.MappingIterator:com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JsonDeserializer,boolean,java.lang.Object",
        "C|com.fasterxml.jackson.databind.MappingIterator|<init>|com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JsonDeserializer,boolean,java.lang.Object",
        "M|com.fasterxml.jackson.databind.MappingIterator|_handleIOException|java.io.IOException|new:com.fasterxml.jackson.databind.MappingIterator:com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JsonDeserializer,boolean,java.lang.Object",
        "M|com.fasterxml.jackson.databind.MappingIterator|_handleMappingException|com.fasterxml.jackson.databind.JsonMappingException|new:com.fasterxml.jackson.databind.MappingIterator:com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JsonDeserializer,boolean,java.lang.Object",
        "M|com.fasterxml.jackson.databind.MappingIterator|_throwNoSuchElement||new:com.fasterxml.jackson.databind.MappingIterator:com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JsonDeserializer,boolean,java.lang.Object",
        "M|com.fasterxml.jackson.databind.MappingIterator|emptyIterator||static",
        "M|com.fasterxml.jackson.databind.MappingIterator|getCurrentLocation||new:com.fasterxml.jackson.databind.MappingIterator:com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JsonDeserializer,boolean,java.lang.Object",
        "M|com.fasterxml.jackson.databind.MappingIterator|getParser||new:com.fasterxml.jackson.databind.MappingIterator:com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JsonDeserializer,boolean,java.lang.Object",
        "M|com.fasterxml.jackson.databind.MappingIterator|getParserSchema||new:com.fasterxml.jackson.databind.MappingIterator:com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JsonDeserializer,boolean,java.lang.Object",
        "M|com.fasterxml.jackson.databind.MappingIterator|hasNext||new:com.fasterxml.jackson.databind.MappingIterator:com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JsonDeserializer,boolean,java.lang.Object",
        "M|com.fasterxml.jackson.databind.MappingIterator|next||new:com.fasterxml.jackson.databind.MappingIterator:com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JsonDeserializer,boolean,java.lang.Object",
        "M|com.fasterxml.jackson.databind.MappingIterator|readAll|java.util.Collection|new:com.fasterxml.jackson.databind.MappingIterator:com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JsonDeserializer,boolean,java.lang.Object",
        "M|com.fasterxml.jackson.databind.MappingIterator|readAll||new:com.fasterxml.jackson.databind.MappingIterator:com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JsonDeserializer,boolean,java.lang.Object",
        "M|com.fasterxml.jackson.databind.MappingIterator|_resync||new:com.fasterxml.jackson.databind.MappingIterator:com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JsonDeserializer,boolean,java.lang.Object",
        "M|com.fasterxml.jackson.databind.MappingIterator|close||new:com.fasterxml.jackson.databind.MappingIterator:com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JsonDeserializer,boolean,java.lang.Object",
        "M|com.fasterxml.jackson.databind.MappingIterator|hasNextValue||new:com.fasterxml.jackson.databind.MappingIterator:com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JsonDeserializer,boolean,java.lang.Object",
        "M|com.fasterxml.jackson.databind.MappingIterator|nextValue||new:com.fasterxml.jackson.databind.MappingIterator:com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JsonDeserializer,boolean,java.lang.Object",
        "C|com.fasterxml.jackson.databind.MappingIterator|<init>|com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JsonDeserializer,boolean,java.lang.Object",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 20) int w0, @InRange(minInt = 0, maxInt = 20) int w1, @InRange(minInt = 0, maxInt = 20) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
