package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 5 patched method(s), 21 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.fasterxml.jackson.databind.type.TypeFactory|constructType|com.fasterxml.jackson.core.type.TypeReference|new:com.fasterxml.jackson.databind.type.TypeFactory:",
        "M|com.fasterxml.jackson.databind.type.TypeFactory|constructType|java.lang.reflect.Type|new:com.fasterxml.jackson.databind.type.TypeFactory:",
        "M|com.fasterxml.jackson.databind.type.TypeFactory|constructType|java.lang.reflect.Type,com.fasterxml.jackson.databind.JavaType|new:com.fasterxml.jackson.databind.type.TypeFactory:",
        "M|com.fasterxml.jackson.databind.type.TypeFactory|constructType|java.lang.reflect.Type,com.fasterxml.jackson.databind.type.TypeBindings|new:com.fasterxml.jackson.databind.type.TypeFactory:",
        "M|com.fasterxml.jackson.databind.type.TypeFactory|constructType|java.lang.reflect.Type,java.lang.Class|new:com.fasterxml.jackson.databind.type.TypeFactory:",
        "M|com.fasterxml.jackson.databind.type.TypeFactory|_collectionType|java.lang.Class,com.fasterxml.jackson.databind.type.TypeBindings,com.fasterxml.jackson.databind.JavaType,[Lcom.fasterxml.jackson.databind.JavaType;|new:com.fasterxml.jackson.databind.type.TypeFactory:",
        "M|com.fasterxml.jackson.databind.type.TypeFactory|_constructSimple|java.lang.Class,com.fasterxml.jackson.databind.type.TypeBindings,com.fasterxml.jackson.databind.JavaType,[Lcom.fasterxml.jackson.databind.JavaType;|new:com.fasterxml.jackson.databind.type.TypeFactory:",
        "M|com.fasterxml.jackson.databind.type.TypeFactory|_findPrimitive|java.lang.String|new:com.fasterxml.jackson.databind.type.TypeFactory:",
        "M|com.fasterxml.jackson.databind.type.TypeFactory|_findWellKnownSimple|java.lang.Class|new:com.fasterxml.jackson.databind.type.TypeFactory:",
        "M|com.fasterxml.jackson.databind.type.TypeFactory|_fromAny|com.fasterxml.jackson.databind.type.ClassStack,java.lang.reflect.Type,com.fasterxml.jackson.databind.type.TypeBindings|new:com.fasterxml.jackson.databind.type.TypeFactory:",
        "M|com.fasterxml.jackson.databind.type.TypeFactory|_fromArrayType|com.fasterxml.jackson.databind.type.ClassStack,java.lang.reflect.GenericArrayType,com.fasterxml.jackson.databind.type.TypeBindings|new:com.fasterxml.jackson.databind.type.TypeFactory:",
        "M|com.fasterxml.jackson.databind.type.TypeFactory|_fromClass|com.fasterxml.jackson.databind.type.ClassStack,java.lang.Class,com.fasterxml.jackson.databind.type.TypeBindings|new:com.fasterxml.jackson.databind.type.TypeFactory:",
        "M|com.fasterxml.jackson.databind.type.TypeFactory|_fromParamType|com.fasterxml.jackson.databind.type.ClassStack,java.lang.reflect.ParameterizedType,com.fasterxml.jackson.databind.type.TypeBindings|new:com.fasterxml.jackson.databind.type.TypeFactory:",
        "M|com.fasterxml.jackson.databind.type.TypeFactory|_fromVariable|com.fasterxml.jackson.databind.type.ClassStack,java.lang.reflect.TypeVariable,com.fasterxml.jackson.databind.type.TypeBindings|new:com.fasterxml.jackson.databind.type.TypeFactory:",
        "M|com.fasterxml.jackson.databind.type.TypeFactory|_fromWellKnownClass|com.fasterxml.jackson.databind.type.ClassStack,java.lang.Class,com.fasterxml.jackson.databind.type.TypeBindings,com.fasterxml.jackson.databind.JavaType,[Lcom.fasterxml.jackson.databind.JavaType;|new:com.fasterxml.jackson.databind.type.TypeFactory:",
        "M|com.fasterxml.jackson.databind.type.TypeFactory|_fromWellKnownInterface|com.fasterxml.jackson.databind.type.ClassStack,java.lang.Class,com.fasterxml.jackson.databind.type.TypeBindings,com.fasterxml.jackson.databind.JavaType,[Lcom.fasterxml.jackson.databind.JavaType;|new:com.fasterxml.jackson.databind.type.TypeFactory:",
        "M|com.fasterxml.jackson.databind.type.TypeFactory|constructType|com.fasterxml.jackson.core.type.TypeReference|new:com.fasterxml.jackson.databind.type.TypeFactory:",
        "M|com.fasterxml.jackson.databind.type.TypeFactory|constructType|java.lang.reflect.Type|new:com.fasterxml.jackson.databind.type.TypeFactory:",
        "M|com.fasterxml.jackson.databind.type.TypeFactory|constructType|java.lang.reflect.Type,com.fasterxml.jackson.databind.JavaType|new:com.fasterxml.jackson.databind.type.TypeFactory:",
        "M|com.fasterxml.jackson.databind.type.TypeFactory|constructType|java.lang.reflect.Type,com.fasterxml.jackson.databind.type.TypeBindings|new:com.fasterxml.jackson.databind.type.TypeFactory:",
        "M|com.fasterxml.jackson.databind.type.TypeFactory|constructType|java.lang.reflect.Type,java.lang.Class|new:com.fasterxml.jackson.databind.type.TypeFactory:",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 20) int w0, @InRange(minInt = 0, maxInt = 20) int w1, @InRange(minInt = 0, maxInt = 20) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
