package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 0 patched method(s), 14 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.jsoup.parser.Token|asCharacter||new:org.jsoup.parser.Token$Character:",
        "M|org.jsoup.parser.Token|asComment||new:org.jsoup.parser.Token$Character:",
        "M|org.jsoup.parser.Token|asDoctype||new:org.jsoup.parser.Token$Character:",
        "M|org.jsoup.parser.Token|asEndTag||new:org.jsoup.parser.Token$Character:",
        "M|org.jsoup.parser.Token|asStartTag||new:org.jsoup.parser.Token$Character:",
        "M|org.jsoup.parser.Token|isCharacter||new:org.jsoup.parser.Token$Character:",
        "M|org.jsoup.parser.Token|isComment||new:org.jsoup.parser.Token$Character:",
        "M|org.jsoup.parser.Token|isDoctype||new:org.jsoup.parser.Token$Character:",
        "M|org.jsoup.parser.Token|isEOF||new:org.jsoup.parser.Token$Character:",
        "M|org.jsoup.parser.Token|isEndTag||new:org.jsoup.parser.Token$Character:",
        "M|org.jsoup.parser.Token|isStartTag||new:org.jsoup.parser.Token$Character:",
        "M|org.jsoup.parser.Token|reset||new:org.jsoup.parser.Token$Character:",
        "M|org.jsoup.parser.Token|reset|java.lang.StringBuilder|static",
        "M|org.jsoup.parser.Token|tokenType||new:org.jsoup.parser.Token$Character:",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 13) int w0, @InRange(minInt = 0, maxInt = 13) int w1, @InRange(minInt = 0, maxInt = 13) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
