package zestd4j;

import java.lang.reflect.*;
import java.nio.file.*;
import java.util.*;
import java.util.regex.*;

/**
 * Auto-generates a Zest fuzz driver for a Defects4J bug.
 *
 * Candidates = public static methods of the modified classes that take ONE String/CharSequence.
 * Methods touched by the bug-fix patch are preferred; if none qualify, all candidates of the
 * modified classes are used (so the class is still fuzzed and coverage/mutation are measured).
 *
 * Usage: DriverGen <out/AutoFuzz.java> <fixed src root> <changed-lines file> <Cls1,Cls2,...>
 *   changed-lines file: one "fq.ClassName lineNo" per line (line numbers in the FIXED source)
 * Prints the method spec "Cls#m,Cls#m" on stdout; exit code 2 = no usable method.
 */
public class DriverGen {
    static final int MAX_METHODS = 12;
    static final Pattern SIG = Pattern.compile(
        "^\\s*(?:(?:public|protected|private|static|final|synchronized|native|abstract|strictfp)\\s+)*"
        + "(?:<[^>]+>\\s+)?[\\w.$<>\\[\\],?\\s]+?\\s+(\\w+)\\s*\\(");
    static final Set<String> NOT_METHODS = new HashSet<>(Arrays.asList(
        "if", "for", "while", "switch", "catch", "return", "new", "throw", "else", "synchronized", "do", "try"));

    public static void main(String[] a) throws Exception {
        Path out = Paths.get(a[0]);
        Path srcRoot = Paths.get(a[1]);
        Map<String, Set<Integer>> changed = new HashMap<>();
        for (String l : Files.readAllLines(Paths.get(a[2]))) {
            String[] p = l.trim().split("\\s+");
            if (p.length == 2) changed.computeIfAbsent(p[0], k -> new TreeSet<>()).add(Integer.parseInt(p[1]));
        }

        List<Method> patched = new ArrayList<>(), others = new ArrayList<>();
        for (String cn : a[3].split(",")) {
            cn = cn.trim(); if (cn.isEmpty()) continue;
            Class<?> c;
            try { c = Class.forName(cn, false, DriverGen.class.getClassLoader()); }
            catch (Throwable e) { System.err.println("cannot load " + cn + ": " + e); continue; }
            if (!Modifier.isPublic(c.getModifiers())) { System.err.println("not public: " + cn); continue; }
            Set<String> touched = touchedMethods(srcRoot, cn, changed.getOrDefault(cn, Collections.emptySet()));
            System.err.println(cn + " patched methods: " + touched);
            List<Method> ms = new ArrayList<>(Arrays.asList(c.getDeclaredMethods()));
            // deterministic order; String overload before CharSequence
            ms.sort(Comparator.comparing(Method::getName).thenComparing(Method::toString, Comparator.reverseOrder()));
            for (Method m : ms) {
                int mod = m.getModifiers();
                if (!Modifier.isPublic(mod) || !Modifier.isStatic(mod) || m.isSynthetic() || m.getParameterCount() != 1) continue;
                Class<?> pt = m.getParameterTypes()[0];
                if (pt != String.class && pt != CharSequence.class) continue;
                if (containsName(patched, others, m)) continue; // overloads String/CharSequence: keep one
                (touched.contains(m.getName()) ? patched : others).add(m);
            }
        }
        List<Method> chosen = !patched.isEmpty() ? patched : others;
        if (chosen.size() > MAX_METHODS) chosen = chosen.subList(0, MAX_METHODS);
        if (chosen.isEmpty()) {
            System.err.println("no public static method with a single String/CharSequence parameter");
            System.exit(2);
        }
        System.err.println((patched.isEmpty() ? "no patched method is fuzzable; using class methods: " : "fuzzing patched methods: ")
            + names(chosen));

        StringBuilder sb = new StringBuilder();
        sb.append("package zestd4j;\n\n")
          .append("import com.pholser.junit.quickcheck.generator.InRange;\n")
          .append("import edu.berkeley.cs.jqf.fuzz.Fuzz;\n")
          .append("import edu.berkeley.cs.jqf.fuzz.JQF;\n")
          .append("import org.junit.runner.RunWith;\n")
          .append("import static org.junit.Assume.assumeTrue;\n\n")
          .append("// AUTO-GENERATED by DriverGen (").append(patched.isEmpty() ? "class methods" : "patched methods").append(")\n")
          .append("@RunWith(JQF.class)\npublic class AutoFuzz {\n")
          .append("    @Fuzz\n    public void fuzz(@InRange(minInt = 0, maxInt = ").append(chosen.size() - 1)
          .append(") int which, String s) throws Throwable {\n")
          .append("        InputLog.record(which, s);\n")
          .append("        try {\n            switch (which) {\n");
        for (int i = 0; i < chosen.size(); i++) {
            Method m = chosen.get(i);
            sb.append("                case ").append(i).append(": ")
              .append(m.getDeclaringClass().getName().replace('$', '.')).append('.').append(m.getName())
              .append("(s); break;\n");
        }
        sb.append("            }\n")
          .append("        } catch (IllegalArgumentException e) {   // incl. NumberFormatException: invalid input\n")
          .append("            assumeTrue(false);\n")
          .append("        }\n    }\n}\n");
        Files.createDirectories(out.getParent());
        Files.write(out, sb.toString().getBytes("UTF-8"));
        System.out.println(spec(chosen));
    }

    static boolean containsName(List<Method> a, List<Method> b, Method m) {
        for (Method x : a) if (same(x, m)) return true;
        for (Method x : b) if (same(x, m)) return true;
        return false;
    }
    static boolean same(Method x, Method m) { return x.getName().equals(m.getName()) && x.getDeclaringClass() == m.getDeclaringClass(); }
    static String names(List<Method> ms) { StringBuilder b = new StringBuilder(); for (Method m : ms) b.append(m.getName()).append(' '); return b.toString().trim(); }
    static String spec(List<Method> ms) {
        StringBuilder b = new StringBuilder();
        for (Method m : ms) { if (b.length() > 0) b.append(','); b.append(m.getDeclaringClass().getName()).append('#').append(m.getName()); }
        return b.toString();
    }

    /** Names of methods whose body contains one of the changed lines (heuristic, brace counting). */
    static Set<String> touchedMethods(Path srcRoot, String cn, Set<Integer> lines) {
        Set<String> res = new HashSet<>();
        if (lines.isEmpty()) return res;
        String top = cn.contains("$") ? cn.substring(0, cn.indexOf('$')) : cn;
        Path f = srcRoot.resolve(top.replace('.', '/') + ".java");
        List<String> src;
        try { src = Files.readAllLines(f); } catch (Exception e) {
            try { src = Files.readAllLines(f, java.nio.charset.StandardCharsets.ISO_8859_1); } catch (Exception e2) { return res; }
        }
        String current = null; int depthAtStart = -1, depth = 0; boolean inBlockComment = false;
        String pending = null;
        for (int i = 0; i < src.size(); i++) {
            String raw = src.get(i);
            String code = stripComments(raw, inBlockComment);
            inBlockComment = endsInBlockComment(raw, inBlockComment);
            if (current == null) {
                Matcher mm = SIG.matcher(code);
                if (mm.find() && !NOT_METHODS.contains(mm.group(1)) && !code.contains("=") && !code.trim().endsWith(";")) pending = mm.group(1);
            }
            for (char ch : code.toCharArray()) {
                if (ch == '{') {
                    if (current == null && pending != null) { current = pending; depthAtStart = depth; pending = null; }
                    depth++;
                } else if (ch == '}') {
                    depth--;
                    if (current != null && depth == depthAtStart) { if (lines.contains(i + 1)) res.add(current); current = null; }
                } else if (ch == ';' && current == null) pending = null;
            }
            if (current != null && lines.contains(i + 1)) res.add(current);
        }
        return res;
    }
    static String stripComments(String s, boolean inBlock) {
        StringBuilder b = new StringBuilder(); boolean blk = inBlock, str = false; char q = 0;
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i), n = i + 1 < s.length() ? s.charAt(i + 1) : 0;
            if (blk) { if (c == '*' && n == '/') { blk = false; i++; } continue; }
            if (str) { if (c == '\\') { i++; continue; } if (c == q) str = false; continue; }
            if (c == '"' || c == '\'') { str = true; q = c; b.append(' '); continue; }
            if (c == '/' && n == '/') break;
            if (c == '/' && n == '*') { blk = true; i++; continue; }
            b.append(c);
        }
        return b.toString();
    }
    static boolean endsInBlockComment(String s, boolean inBlock) {
        boolean blk = inBlock, str = false; char q = 0;
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i), n = i + 1 < s.length() ? s.charAt(i + 1) : 0;
            if (blk) { if (c == '*' && n == '/') { blk = false; i++; } continue; }
            if (str) { if (c == '\\') { i++; continue; } if (c == q) str = false; continue; }
            if (c == '"' || c == '\'') { str = true; q = c; continue; }
            if (c == '/' && n == '/') return false;
            if (c == '/' && n == '*') { blk = true; i++; }
        }
        return blk;
    }
}
