package zestd4j;

import java.io.File;
import java.lang.reflect.*;
import java.nio.file.*;
import java.util.*;

/**
 * Generic Zest driver generator: works for any method signature.
 * Targets = methods/constructors of the modified classes (patched ones first, then the rest),
 * static or instance (receiver built by constructor, static factory, static field or subclass),
 * any visibility, any parameter types (see Harness.arg; unsupported types get null).
 *
 * Usage: DriverGen2 <outDir> <fixed src root> <changed-lines file> <Cls1,Cls2> <project classes dir>
 * Writes outDir/AutoFuzz.java and outDir/targets.txt; prints the number of targets.
 */
public class DriverGen2 {
    static final int MAX_TARGETS = 16;

    public static void main(String[] a) throws Exception {
        Path outDir = Paths.get(a[0]);
        Path srcRoot = Paths.get(a[1]);
        Map<String, Set<Integer>> changed = new HashMap<>();
        for (String l : Files.readAllLines(Paths.get(a[2]))) {
            String[] p = l.trim().split("\\s+");
            if (p.length == 2) changed.computeIfAbsent(p[0], k -> new TreeSet<>()).add(Integer.parseInt(p[1]));
        }
        List<String> project = listClasses(new File(a[4]));
        ClassLoader cl = DriverGen2.class.getClassLoader();

        List<String> patched = new ArrayList<>(), others = new ArrayList<>();
        for (String cn : a[3].split(",")) {
            cn = cn.trim(); if (cn.isEmpty()) continue;
            Class<?> c;
            try { c = Class.forName(cn, false, cl); } catch (Throwable e) { System.err.println("cannot load " + cn); continue; }
            Set<String> touched = DriverGen.touchedMethods(srcRoot, cn, changed.getOrDefault(cn, Collections.emptySet()));
            System.err.println(cn + " patched: " + touched);
            String recv = receiver(c, project, cl);
            System.err.println(cn + " receiver: " + recv);

            List<Method> ms = new ArrayList<>(Arrays.asList(c.getDeclaredMethods()));
            ms.sort(Comparator.comparing(Method::getName).thenComparing(Method::toString));
            for (Method m : ms) {
                if (m.isSynthetic() || m.isBridge() || m.getName().contains("$")) continue;
                boolean st = Modifier.isStatic(m.getModifiers());
                if (!st && recv == null) continue;
                String d = "M|" + c.getName() + "|" + m.getName() + "|" + types(m.getParameterTypes()) + "|" + (st ? "static" : recv);
                (touched.contains(m.getName()) ? patched : others).add(d);
            }
            if (!Modifier.isAbstract(c.getModifiers()) && !c.isInterface() && !c.isEnum() && !innerNonStatic(c)) {
                for (Constructor<?> k : c.getDeclaredConstructors()) {
                    if (k.isSynthetic()) continue;
                    String d = "C|" + c.getName() + "|<init>|" + types(k.getParameterTypes());
                    (touched.contains(c.getSimpleName()) ? patched : others).add(d);
                }
            }
        }
        // patched targets first (listed twice so the fuzzer picks them more often), then others
        List<String> t = new ArrayList<>();
        for (String d : patched) if (t.size() < MAX_TARGETS) t.add(d);
        for (String d : others)  if (t.size() < MAX_TARGETS) t.add(d);
        if (!patched.isEmpty()) for (String d : patched) if (t.size() < MAX_TARGETS + patched.size()) t.add(d);
        if (t.isEmpty()) { System.err.println("no callable member found"); System.exit(2); }

        Files.createDirectories(outDir);
        Files.write(outDir.resolve("targets.txt"), t);
        StringBuilder sb = new StringBuilder();
        sb.append("package zestd4j;\n\n")
          .append("import com.pholser.junit.quickcheck.generator.InRange;\n")
          .append("import edu.berkeley.cs.jqf.fuzz.Fuzz;\n")
          .append("import edu.berkeley.cs.jqf.fuzz.JQF;\n")
          .append("import org.junit.runner.RunWith;\n")
          .append("import static org.junit.Assume.assumeTrue;\n\n")
          .append("// AUTO-GENERATED by DriverGen2: ").append(patched.size()).append(" patched method(s), ")
          .append(t.size()).append(" target entries\n")
          .append("@RunWith(JQF.class)\npublic class AutoFuzz {\n    static final String[] T = {\n");
        for (String d : t) sb.append("        \"").append(d.replace("\\", "\\\\").replace("\"", "\\\"")).append("\",\n");
        int k = t.size() - 1;
        sb.append("    };\n\n    @Fuzz\n    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,\n")
          .append("            @InRange(minInt = 0, maxInt = ").append(k).append(") int w0, @InRange(minInt = 0, maxInt = ").append(k)
          .append(") int w1, @InRange(minInt = 0, maxInt = ").append(k).append(") int w2,\n")
          .append("            String s0, String s1, String s2,\n")
          .append("            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,\n")
          .append("            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,\n")
          .append("            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {\n")
          .append("        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);\n")
          .append("        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);\n")
          .append("        assumeTrue(!Harness.invalid);\n    }\n}\n");
        Files.write(outDir.resolve("AutoFuzz.java"), sb.toString().getBytes("UTF-8"));
        System.out.println(t.size());
    }

    static boolean innerNonStatic(Class<?> c) { return c.isMemberClass() && !Modifier.isStatic(c.getModifiers()); }

    static String types(Class<?>[] ps) {
        StringBuilder b = new StringBuilder();
        for (Class<?> p : ps) { if (b.length() > 0) b.append(','); b.append(p.getName()); }
        return b.toString();
    }

    /** How to get an instance of c: constructor, static factory, static field, or concrete subclass. */
    static String receiver(Class<?> c, List<String> project, ClassLoader cl) {
        if (!Modifier.isAbstract(c.getModifiers()) && !c.isInterface() && !c.isEnum() && !innerNonStatic(c)) {
            Constructor<?> best = null;
            for (Constructor<?> k : c.getDeclaredConstructors())
                if (!k.isSynthetic() && (best == null || score(k) < score(best))) best = k;
            if (best != null) return "new:" + c.getName() + ":" + types(best.getParameterTypes());
        }
        Method fac = null;
        for (Method m : c.getDeclaredMethods())
            if (Modifier.isStatic(m.getModifiers()) && !m.isSynthetic() && c.isAssignableFrom(m.getReturnType())
                && m.getReturnType() != Object.class && (fac == null || m.getParameterCount() < fac.getParameterCount()))
                fac = m;
        if (fac != null) return "fac:" + c.getName() + ":" + fac.getName() + ":" + types(fac.getParameterTypes());
        if (c.isEnum()) {
            Object[] v = c.getEnumConstants();
            if (v != null && v.length > 0) return "fld:" + c.getName() + ":" + ((Enum<?>) v[0]).name();
        }
        String fld = staticField(c, c);
        if (fld != null) return fld;
        for (String pn : project) {                     // static fields elsewhere, then subclasses
            try {
                Class<?> o = Class.forName(pn, false, cl);
                if (o == c) continue;
                fld = staticField(o, c);
                if (fld != null) return fld;
            } catch (Throwable ignored) {}
        }
        for (String pn : project) {
            try {
                Class<?> o = Class.forName(pn, false, cl);
                if (o != c && c.isAssignableFrom(o) && !Modifier.isAbstract(o.getModifiers()) && !o.isInterface()
                    && !innerNonStatic(o) && !o.isAnonymousClass()) {
                    Constructor<?> best = null;
                    for (Constructor<?> k : o.getDeclaredConstructors())
                        if (!k.isSynthetic() && (best == null || score(k) < score(best))) best = k;
                    if (best != null) return "new:" + o.getName() + ":" + types(best.getParameterTypes());
                }
            } catch (Throwable ignored) {}
        }
        return null;
    }

    static int score(Constructor<?> k) {
        return k.getParameterCount() * 2 + (Modifier.isPublic(k.getModifiers()) ? 0 : 1);
    }

    static String staticField(Class<?> owner, Class<?> type) {
        try {
            Field[] fs = owner.getDeclaredFields();
            Arrays.sort(fs, Comparator.comparing(Field::getName));
            for (Field f : fs)
                if (Modifier.isStatic(f.getModifiers()) && !f.isSynthetic() && type.isAssignableFrom(f.getType())
                    && f.getType() != Object.class)
                    return "fld:" + owner.getName() + ":" + f.getName();
        } catch (Throwable ignored) {}
        return null;
    }

    static List<String> listClasses(File root) {
        List<String> r = new ArrayList<>();
        walk(root, root, r);
        Collections.sort(r);
        return r;
    }
    static void walk(File root, File f, List<String> r) {
        File[] fs = f.listFiles();
        if (fs == null) return;
        for (File x : fs) {
            if (x.isDirectory()) walk(root, x, r);
            else if (x.getName().endsWith(".class")) {
                String rel = root.toPath().relativize(x.toPath()).toString();
                r.add(rel.substring(0, rel.length() - 6).replace(File.separatorChar, '.'));
            }
        }
    }
}
