package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 3 patched method(s), 19 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.apache.commons.jxpath.ri.compiler.CoreFunction|functionCeiling|org.apache.commons.jxpath.ri.EvalContext|new:org.apache.commons.jxpath.ri.compiler.CoreFunction:int,[Lorg.apache.commons.jxpath.ri.compiler.Expression;",
        "M|org.apache.commons.jxpath.ri.compiler.CoreFunction|functionFloor|org.apache.commons.jxpath.ri.EvalContext|new:org.apache.commons.jxpath.ri.compiler.CoreFunction:int,[Lorg.apache.commons.jxpath.ri.compiler.Expression;",
        "M|org.apache.commons.jxpath.ri.compiler.CoreFunction|functionRound|org.apache.commons.jxpath.ri.EvalContext|new:org.apache.commons.jxpath.ri.compiler.CoreFunction:int,[Lorg.apache.commons.jxpath.ri.compiler.Expression;",
        "M|org.apache.commons.jxpath.ri.compiler.CoreFunction|assertArgCount|int|new:org.apache.commons.jxpath.ri.compiler.CoreFunction:int,[Lorg.apache.commons.jxpath.ri.compiler.Expression;",
        "M|org.apache.commons.jxpath.ri.compiler.CoreFunction|assertArgRange|int,int|new:org.apache.commons.jxpath.ri.compiler.CoreFunction:int,[Lorg.apache.commons.jxpath.ri.compiler.Expression;",
        "M|org.apache.commons.jxpath.ri.compiler.CoreFunction|compute|org.apache.commons.jxpath.ri.EvalContext|new:org.apache.commons.jxpath.ri.compiler.CoreFunction:int,[Lorg.apache.commons.jxpath.ri.compiler.Expression;",
        "M|org.apache.commons.jxpath.ri.compiler.CoreFunction|computeContextDependent||new:org.apache.commons.jxpath.ri.compiler.CoreFunction:int,[Lorg.apache.commons.jxpath.ri.compiler.Expression;",
        "M|org.apache.commons.jxpath.ri.compiler.CoreFunction|computeValue|org.apache.commons.jxpath.ri.EvalContext|new:org.apache.commons.jxpath.ri.compiler.CoreFunction:int,[Lorg.apache.commons.jxpath.ri.compiler.Expression;",
        "M|org.apache.commons.jxpath.ri.compiler.CoreFunction|functionBoolean|org.apache.commons.jxpath.ri.EvalContext|new:org.apache.commons.jxpath.ri.compiler.CoreFunction:int,[Lorg.apache.commons.jxpath.ri.compiler.Expression;",
        "M|org.apache.commons.jxpath.ri.compiler.CoreFunction|functionConcat|org.apache.commons.jxpath.ri.EvalContext|new:org.apache.commons.jxpath.ri.compiler.CoreFunction:int,[Lorg.apache.commons.jxpath.ri.compiler.Expression;",
        "M|org.apache.commons.jxpath.ri.compiler.CoreFunction|functionContains|org.apache.commons.jxpath.ri.EvalContext|new:org.apache.commons.jxpath.ri.compiler.CoreFunction:int,[Lorg.apache.commons.jxpath.ri.compiler.Expression;",
        "M|org.apache.commons.jxpath.ri.compiler.CoreFunction|functionCount|org.apache.commons.jxpath.ri.EvalContext|new:org.apache.commons.jxpath.ri.compiler.CoreFunction:int,[Lorg.apache.commons.jxpath.ri.compiler.Expression;",
        "M|org.apache.commons.jxpath.ri.compiler.CoreFunction|functionFalse|org.apache.commons.jxpath.ri.EvalContext|new:org.apache.commons.jxpath.ri.compiler.CoreFunction:int,[Lorg.apache.commons.jxpath.ri.compiler.Expression;",
        "M|org.apache.commons.jxpath.ri.compiler.CoreFunction|functionFormatNumber|org.apache.commons.jxpath.ri.EvalContext|new:org.apache.commons.jxpath.ri.compiler.CoreFunction:int,[Lorg.apache.commons.jxpath.ri.compiler.Expression;",
        "M|org.apache.commons.jxpath.ri.compiler.CoreFunction|functionID|org.apache.commons.jxpath.ri.EvalContext|new:org.apache.commons.jxpath.ri.compiler.CoreFunction:int,[Lorg.apache.commons.jxpath.ri.compiler.Expression;",
        "M|org.apache.commons.jxpath.ri.compiler.CoreFunction|functionKey|org.apache.commons.jxpath.ri.EvalContext|new:org.apache.commons.jxpath.ri.compiler.CoreFunction:int,[Lorg.apache.commons.jxpath.ri.compiler.Expression;",
        "M|org.apache.commons.jxpath.ri.compiler.CoreFunction|functionCeiling|org.apache.commons.jxpath.ri.EvalContext|new:org.apache.commons.jxpath.ri.compiler.CoreFunction:int,[Lorg.apache.commons.jxpath.ri.compiler.Expression;",
        "M|org.apache.commons.jxpath.ri.compiler.CoreFunction|functionFloor|org.apache.commons.jxpath.ri.EvalContext|new:org.apache.commons.jxpath.ri.compiler.CoreFunction:int,[Lorg.apache.commons.jxpath.ri.compiler.Expression;",
        "M|org.apache.commons.jxpath.ri.compiler.CoreFunction|functionRound|org.apache.commons.jxpath.ri.EvalContext|new:org.apache.commons.jxpath.ri.compiler.CoreFunction:int,[Lorg.apache.commons.jxpath.ri.compiler.Expression;",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 18) int w0, @InRange(minInt = 0, maxInt = 18) int w1, @InRange(minInt = 0, maxInt = 18) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
