package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen (class methods)
@RunWith(JQF.class)
public class AutoFuzz {
    @Fuzz
    public void fuzz(@InRange(minInt = 0, maxInt = 2) int which, String s) throws Throwable {
        InputLog.record(which, s);
        try {
            switch (which) {
                case 0: org.apache.commons.lang.LocaleUtils.countriesByLanguage(s); break;
                case 1: org.apache.commons.lang.LocaleUtils.languagesByCountry(s); break;
                case 2: org.apache.commons.lang.LocaleUtils.toLocale(s); break;
            }
        } catch (IllegalArgumentException e) {   // incl. NumberFormatException: invalid input
            assumeTrue(false);
        }
    }
}
