package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 2 patched method(s), 18 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.fasterxml.jackson.databind.util.TokenBuffer|writeObject|java.lang.Object|new:com.fasterxml.jackson.databind.util.TokenBuffer:com.fasterxml.jackson.core.ObjectCodec",
        "M|com.fasterxml.jackson.databind.util.TokenBuffer|writeTree|com.fasterxml.jackson.core.TreeNode|new:com.fasterxml.jackson.databind.util.TokenBuffer:com.fasterxml.jackson.core.ObjectCodec",
        "M|com.fasterxml.jackson.databind.util.TokenBuffer|_append|com.fasterxml.jackson.core.JsonToken|new:com.fasterxml.jackson.databind.util.TokenBuffer:com.fasterxml.jackson.core.ObjectCodec",
        "M|com.fasterxml.jackson.databind.util.TokenBuffer|_append|com.fasterxml.jackson.core.JsonToken,java.lang.Object|new:com.fasterxml.jackson.databind.util.TokenBuffer:com.fasterxml.jackson.core.ObjectCodec",
        "M|com.fasterxml.jackson.databind.util.TokenBuffer|_appendNativeIds|java.lang.StringBuilder|new:com.fasterxml.jackson.databind.util.TokenBuffer:com.fasterxml.jackson.core.ObjectCodec",
        "M|com.fasterxml.jackson.databind.util.TokenBuffer|_appendRaw|int,java.lang.Object|new:com.fasterxml.jackson.databind.util.TokenBuffer:com.fasterxml.jackson.core.ObjectCodec",
        "M|com.fasterxml.jackson.databind.util.TokenBuffer|_checkNativeIds|com.fasterxml.jackson.core.JsonParser|new:com.fasterxml.jackson.databind.util.TokenBuffer:com.fasterxml.jackson.core.ObjectCodec",
        "M|com.fasterxml.jackson.databind.util.TokenBuffer|_reportUnsupportedOperation||new:com.fasterxml.jackson.databind.util.TokenBuffer:com.fasterxml.jackson.core.ObjectCodec",
        "M|com.fasterxml.jackson.databind.util.TokenBuffer|append|com.fasterxml.jackson.databind.util.TokenBuffer|new:com.fasterxml.jackson.databind.util.TokenBuffer:com.fasterxml.jackson.core.ObjectCodec",
        "M|com.fasterxml.jackson.databind.util.TokenBuffer|asParser||new:com.fasterxml.jackson.databind.util.TokenBuffer:com.fasterxml.jackson.core.ObjectCodec",
        "M|com.fasterxml.jackson.databind.util.TokenBuffer|asParser|com.fasterxml.jackson.core.JsonParser|new:com.fasterxml.jackson.databind.util.TokenBuffer:com.fasterxml.jackson.core.ObjectCodec",
        "M|com.fasterxml.jackson.databind.util.TokenBuffer|asParser|com.fasterxml.jackson.core.ObjectCodec|new:com.fasterxml.jackson.databind.util.TokenBuffer:com.fasterxml.jackson.core.ObjectCodec",
        "M|com.fasterxml.jackson.databind.util.TokenBuffer|canWriteBinaryNatively||new:com.fasterxml.jackson.databind.util.TokenBuffer:com.fasterxml.jackson.core.ObjectCodec",
        "M|com.fasterxml.jackson.databind.util.TokenBuffer|canWriteObjectId||new:com.fasterxml.jackson.databind.util.TokenBuffer:com.fasterxml.jackson.core.ObjectCodec",
        "M|com.fasterxml.jackson.databind.util.TokenBuffer|canWriteTypeId||new:com.fasterxml.jackson.databind.util.TokenBuffer:com.fasterxml.jackson.core.ObjectCodec",
        "M|com.fasterxml.jackson.databind.util.TokenBuffer|close||new:com.fasterxml.jackson.databind.util.TokenBuffer:com.fasterxml.jackson.core.ObjectCodec",
        "M|com.fasterxml.jackson.databind.util.TokenBuffer|writeObject|java.lang.Object|new:com.fasterxml.jackson.databind.util.TokenBuffer:com.fasterxml.jackson.core.ObjectCodec",
        "M|com.fasterxml.jackson.databind.util.TokenBuffer|writeTree|com.fasterxml.jackson.core.TreeNode|new:com.fasterxml.jackson.databind.util.TokenBuffer:com.fasterxml.jackson.core.ObjectCodec",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 17) int w0, @InRange(minInt = 0, maxInt = 17) int w1, @InRange(minInt = 0, maxInt = 17) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
