package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 7 patched method(s), 23 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.jsoup.helper.DataUtil|parseByteData|java.nio.ByteBuffer,java.lang.String,java.lang.String,org.jsoup.parser.Parser|static",
        "M|org.jsoup.nodes.XmlDeclaration|getWholeDeclaration||new:org.jsoup.nodes.XmlDeclaration:java.lang.String,java.lang.String,boolean",
        "M|org.jsoup.nodes.XmlDeclaration|outerHtmlHead|java.lang.Appendable,int,org.jsoup.nodes.Document$OutputSettings|new:org.jsoup.nodes.XmlDeclaration:java.lang.String,java.lang.String,boolean",
        "M|org.jsoup.parser.XmlTreeBuilder|insert|org.jsoup.parser.Token$StartTag|new:org.jsoup.parser.XmlTreeBuilder:",
        "M|org.jsoup.parser.XmlTreeBuilder|insert|org.jsoup.parser.Token$Character|new:org.jsoup.parser.XmlTreeBuilder:",
        "M|org.jsoup.parser.XmlTreeBuilder|insert|org.jsoup.parser.Token$Comment|new:org.jsoup.parser.XmlTreeBuilder:",
        "M|org.jsoup.parser.XmlTreeBuilder|insert|org.jsoup.parser.Token$Doctype|new:org.jsoup.parser.XmlTreeBuilder:",
        "M|org.jsoup.helper.DataUtil|crossStreams|java.io.InputStream,java.io.OutputStream|static",
        "M|org.jsoup.helper.DataUtil|detectCharsetFromBom|java.nio.ByteBuffer,java.lang.String|static",
        "M|org.jsoup.helper.DataUtil|emptyByteBuffer||static",
        "M|org.jsoup.helper.DataUtil|getCharsetFromContentType|java.lang.String|static",
        "M|org.jsoup.helper.DataUtil|load|java.io.File,java.lang.String,java.lang.String|static",
        "M|org.jsoup.helper.DataUtil|load|java.io.InputStream,java.lang.String,java.lang.String|static",
        "M|org.jsoup.helper.DataUtil|load|java.io.InputStream,java.lang.String,java.lang.String,org.jsoup.parser.Parser|static",
        "M|org.jsoup.helper.DataUtil|mimeBoundary||static",
        "M|org.jsoup.helper.DataUtil|readFileToByteBuffer|java.io.File|static",
        "M|org.jsoup.helper.DataUtil|parseByteData|java.nio.ByteBuffer,java.lang.String,java.lang.String,org.jsoup.parser.Parser|static",
        "M|org.jsoup.nodes.XmlDeclaration|getWholeDeclaration||new:org.jsoup.nodes.XmlDeclaration:java.lang.String,java.lang.String,boolean",
        "M|org.jsoup.nodes.XmlDeclaration|outerHtmlHead|java.lang.Appendable,int,org.jsoup.nodes.Document$OutputSettings|new:org.jsoup.nodes.XmlDeclaration:java.lang.String,java.lang.String,boolean",
        "M|org.jsoup.parser.XmlTreeBuilder|insert|org.jsoup.parser.Token$StartTag|new:org.jsoup.parser.XmlTreeBuilder:",
        "M|org.jsoup.parser.XmlTreeBuilder|insert|org.jsoup.parser.Token$Character|new:org.jsoup.parser.XmlTreeBuilder:",
        "M|org.jsoup.parser.XmlTreeBuilder|insert|org.jsoup.parser.Token$Comment|new:org.jsoup.parser.XmlTreeBuilder:",
        "M|org.jsoup.parser.XmlTreeBuilder|insert|org.jsoup.parser.Token$Doctype|new:org.jsoup.parser.XmlTreeBuilder:",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 22) int w0, @InRange(minInt = 0, maxInt = 22) int w1, @InRange(minInt = 0, maxInt = 22) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
