package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 2 patched method(s), 18 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.apache.commons.csv.CSVPrinter|print|java.lang.Object,java.lang.CharSequence,int,int|new:org.apache.commons.csv.CSVPrinter:java.lang.Appendable,org.apache.commons.csv.CSVFormat",
        "M|org.apache.commons.csv.CSVPrinter|print|java.lang.Object|new:org.apache.commons.csv.CSVPrinter:java.lang.Appendable,org.apache.commons.csv.CSVFormat",
        "M|org.apache.commons.csv.CSVFormat|equals|java.lang.Object|new:org.apache.commons.csv.CSVFormat:char,java.lang.Character,org.apache.commons.csv.QuoteMode,java.lang.Character,java.lang.Character,boolean,boolean,java.lang.String,java.lang.String,[Ljava.lang.Object;,[Ljava.lang.String;,boolean,boolean,boolean",
        "M|org.apache.commons.csv.CSVFormat|format|[Ljava.lang.Object;|new:org.apache.commons.csv.CSVFormat:char,java.lang.Character,org.apache.commons.csv.QuoteMode,java.lang.Character,java.lang.Character,boolean,boolean,java.lang.String,java.lang.String,[Ljava.lang.Object;,[Ljava.lang.String;,boolean,boolean,boolean",
        "M|org.apache.commons.csv.CSVFormat|getAllowMissingColumnNames||new:org.apache.commons.csv.CSVFormat:char,java.lang.Character,org.apache.commons.csv.QuoteMode,java.lang.Character,java.lang.Character,boolean,boolean,java.lang.String,java.lang.String,[Ljava.lang.Object;,[Ljava.lang.String;,boolean,boolean,boolean",
        "M|org.apache.commons.csv.CSVFormat|getCommentMarker||new:org.apache.commons.csv.CSVFormat:char,java.lang.Character,org.apache.commons.csv.QuoteMode,java.lang.Character,java.lang.Character,boolean,boolean,java.lang.String,java.lang.String,[Ljava.lang.Object;,[Ljava.lang.String;,boolean,boolean,boolean",
        "M|org.apache.commons.csv.CSVFormat|getDelimiter||new:org.apache.commons.csv.CSVFormat:char,java.lang.Character,org.apache.commons.csv.QuoteMode,java.lang.Character,java.lang.Character,boolean,boolean,java.lang.String,java.lang.String,[Ljava.lang.Object;,[Ljava.lang.String;,boolean,boolean,boolean",
        "M|org.apache.commons.csv.CSVFormat|getEscapeCharacter||new:org.apache.commons.csv.CSVFormat:char,java.lang.Character,org.apache.commons.csv.QuoteMode,java.lang.Character,java.lang.Character,boolean,boolean,java.lang.String,java.lang.String,[Ljava.lang.Object;,[Ljava.lang.String;,boolean,boolean,boolean",
        "M|org.apache.commons.csv.CSVFormat|getHeader||new:org.apache.commons.csv.CSVFormat:char,java.lang.Character,org.apache.commons.csv.QuoteMode,java.lang.Character,java.lang.Character,boolean,boolean,java.lang.String,java.lang.String,[Ljava.lang.Object;,[Ljava.lang.String;,boolean,boolean,boolean",
        "M|org.apache.commons.csv.CSVFormat|getHeaderComments||new:org.apache.commons.csv.CSVFormat:char,java.lang.Character,org.apache.commons.csv.QuoteMode,java.lang.Character,java.lang.Character,boolean,boolean,java.lang.String,java.lang.String,[Ljava.lang.Object;,[Ljava.lang.String;,boolean,boolean,boolean",
        "M|org.apache.commons.csv.CSVFormat|getIgnoreEmptyLines||new:org.apache.commons.csv.CSVFormat:char,java.lang.Character,org.apache.commons.csv.QuoteMode,java.lang.Character,java.lang.Character,boolean,boolean,java.lang.String,java.lang.String,[Ljava.lang.Object;,[Ljava.lang.String;,boolean,boolean,boolean",
        "M|org.apache.commons.csv.CSVFormat|getIgnoreHeaderCase||new:org.apache.commons.csv.CSVFormat:char,java.lang.Character,org.apache.commons.csv.QuoteMode,java.lang.Character,java.lang.Character,boolean,boolean,java.lang.String,java.lang.String,[Ljava.lang.Object;,[Ljava.lang.String;,boolean,boolean,boolean",
        "M|org.apache.commons.csv.CSVFormat|getIgnoreSurroundingSpaces||new:org.apache.commons.csv.CSVFormat:char,java.lang.Character,org.apache.commons.csv.QuoteMode,java.lang.Character,java.lang.Character,boolean,boolean,java.lang.String,java.lang.String,[Ljava.lang.Object;,[Ljava.lang.String;,boolean,boolean,boolean",
        "M|org.apache.commons.csv.CSVFormat|getNullString||new:org.apache.commons.csv.CSVFormat:char,java.lang.Character,org.apache.commons.csv.QuoteMode,java.lang.Character,java.lang.Character,boolean,boolean,java.lang.String,java.lang.String,[Ljava.lang.Object;,[Ljava.lang.String;,boolean,boolean,boolean",
        "M|org.apache.commons.csv.CSVFormat|getQuoteCharacter||new:org.apache.commons.csv.CSVFormat:char,java.lang.Character,org.apache.commons.csv.QuoteMode,java.lang.Character,java.lang.Character,boolean,boolean,java.lang.String,java.lang.String,[Ljava.lang.Object;,[Ljava.lang.String;,boolean,boolean,boolean",
        "M|org.apache.commons.csv.CSVFormat|getQuoteMode||new:org.apache.commons.csv.CSVFormat:char,java.lang.Character,org.apache.commons.csv.QuoteMode,java.lang.Character,java.lang.Character,boolean,boolean,java.lang.String,java.lang.String,[Ljava.lang.Object;,[Ljava.lang.String;,boolean,boolean,boolean",
        "M|org.apache.commons.csv.CSVPrinter|print|java.lang.Object,java.lang.CharSequence,int,int|new:org.apache.commons.csv.CSVPrinter:java.lang.Appendable,org.apache.commons.csv.CSVFormat",
        "M|org.apache.commons.csv.CSVPrinter|print|java.lang.Object|new:org.apache.commons.csv.CSVPrinter:java.lang.Appendable,org.apache.commons.csv.CSVFormat",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 17) int w0, @InRange(minInt = 0, maxInt = 17) int w1, @InRange(minInt = 0, maxInt = 17) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
