package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 0 patched method(s), 16 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.apache.commons.collections.map.Flat3Map|clear||new:org.apache.commons.collections.map.Flat3Map:",
        "M|org.apache.commons.collections.map.Flat3Map|clone||new:org.apache.commons.collections.map.Flat3Map:",
        "M|org.apache.commons.collections.map.Flat3Map|containsKey|java.lang.Object|new:org.apache.commons.collections.map.Flat3Map:",
        "M|org.apache.commons.collections.map.Flat3Map|containsValue|java.lang.Object|new:org.apache.commons.collections.map.Flat3Map:",
        "M|org.apache.commons.collections.map.Flat3Map|convertToMap||new:org.apache.commons.collections.map.Flat3Map:",
        "M|org.apache.commons.collections.map.Flat3Map|createDelegateMap||new:org.apache.commons.collections.map.Flat3Map:",
        "M|org.apache.commons.collections.map.Flat3Map|entrySet||new:org.apache.commons.collections.map.Flat3Map:",
        "M|org.apache.commons.collections.map.Flat3Map|equals|java.lang.Object|new:org.apache.commons.collections.map.Flat3Map:",
        "M|org.apache.commons.collections.map.Flat3Map|get|java.lang.Object|new:org.apache.commons.collections.map.Flat3Map:",
        "M|org.apache.commons.collections.map.Flat3Map|hashCode||new:org.apache.commons.collections.map.Flat3Map:",
        "M|org.apache.commons.collections.map.Flat3Map|isEmpty||new:org.apache.commons.collections.map.Flat3Map:",
        "M|org.apache.commons.collections.map.Flat3Map|keySet||new:org.apache.commons.collections.map.Flat3Map:",
        "M|org.apache.commons.collections.map.Flat3Map|mapIterator||new:org.apache.commons.collections.map.Flat3Map:",
        "M|org.apache.commons.collections.map.Flat3Map|put|java.lang.Object,java.lang.Object|new:org.apache.commons.collections.map.Flat3Map:",
        "M|org.apache.commons.collections.map.Flat3Map|putAll|java.util.Map|new:org.apache.commons.collections.map.Flat3Map:",
        "M|org.apache.commons.collections.map.Flat3Map|readObject|java.io.ObjectInputStream|new:org.apache.commons.collections.map.Flat3Map:",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 15) int w0, @InRange(minInt = 0, maxInt = 15) int w1, @InRange(minInt = 0, maxInt = 15) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
