package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 1 patched method(s), 17 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.google.javascript.jscomp.TypeInference|traverseNew|com.google.javascript.rhino.Node,com.google.javascript.jscomp.type.FlowScope|new:com.google.javascript.jscomp.TypeInference:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ControlFlowGraph,com.google.javascript.jscomp.type.ReverseAbstractInterpreter,com.google.javascript.jscomp.Scope,java.util.Map",
        "M|com.google.javascript.jscomp.TypeInference|backwardsInferenceFromCallSite|com.google.javascript.rhino.Node,com.google.javascript.rhino.jstype.FunctionType|new:com.google.javascript.jscomp.TypeInference:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ControlFlowGraph,com.google.javascript.jscomp.type.ReverseAbstractInterpreter,com.google.javascript.jscomp.Scope,java.util.Map",
        "M|com.google.javascript.jscomp.TypeInference|branchedFlowThrough|com.google.javascript.rhino.Node,com.google.javascript.jscomp.type.FlowScope|new:com.google.javascript.jscomp.TypeInference:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ControlFlowGraph,com.google.javascript.jscomp.type.ReverseAbstractInterpreter,com.google.javascript.jscomp.Scope,java.util.Map",
        "M|com.google.javascript.jscomp.TypeInference|createEntryLattice||new:com.google.javascript.jscomp.TypeInference:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ControlFlowGraph,com.google.javascript.jscomp.type.ReverseAbstractInterpreter,com.google.javascript.jscomp.Scope,java.util.Map",
        "M|com.google.javascript.jscomp.TypeInference|createInitialEstimateLattice||new:com.google.javascript.jscomp.TypeInference:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ControlFlowGraph,com.google.javascript.jscomp.type.ReverseAbstractInterpreter,com.google.javascript.jscomp.Scope,java.util.Map",
        "M|com.google.javascript.jscomp.TypeInference|dereferencePointer|com.google.javascript.rhino.Node,com.google.javascript.jscomp.type.FlowScope|new:com.google.javascript.jscomp.TypeInference:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ControlFlowGraph,com.google.javascript.jscomp.type.ReverseAbstractInterpreter,com.google.javascript.jscomp.Scope,java.util.Map",
        "M|com.google.javascript.jscomp.TypeInference|ensurePropertyDeclared|com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.TypeInference:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ControlFlowGraph,com.google.javascript.jscomp.type.ReverseAbstractInterpreter,com.google.javascript.jscomp.Scope,java.util.Map",
        "M|com.google.javascript.jscomp.TypeInference|ensurePropertyDeclaredHelper|com.google.javascript.rhino.Node,com.google.javascript.rhino.jstype.ObjectType|new:com.google.javascript.jscomp.TypeInference:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ControlFlowGraph,com.google.javascript.jscomp.type.ReverseAbstractInterpreter,com.google.javascript.jscomp.Scope,java.util.Map",
        "M|com.google.javascript.jscomp.TypeInference|ensurePropertyDefined|com.google.javascript.rhino.Node,com.google.javascript.rhino.jstype.JSType|new:com.google.javascript.jscomp.TypeInference:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ControlFlowGraph,com.google.javascript.jscomp.type.ReverseAbstractInterpreter,com.google.javascript.jscomp.Scope,java.util.Map",
        "M|com.google.javascript.jscomp.TypeInference|flowThrough|com.google.javascript.rhino.Node,com.google.javascript.jscomp.type.FlowScope|new:com.google.javascript.jscomp.TypeInference:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ControlFlowGraph,com.google.javascript.jscomp.type.ReverseAbstractInterpreter,com.google.javascript.jscomp.Scope,java.util.Map",
        "M|com.google.javascript.jscomp.TypeInference|getBooleanOutcomePair|com.google.javascript.jscomp.TypeInference$BooleanOutcomePair,com.google.javascript.jscomp.TypeInference$BooleanOutcomePair,boolean|new:com.google.javascript.jscomp.TypeInference:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ControlFlowGraph,com.google.javascript.jscomp.type.ReverseAbstractInterpreter,com.google.javascript.jscomp.Scope,java.util.Map",
        "M|com.google.javascript.jscomp.TypeInference|getBooleanOutcomes|com.google.javascript.rhino.jstype.BooleanLiteralSet,com.google.javascript.rhino.jstype.BooleanLiteralSet,boolean|static",
        "M|com.google.javascript.jscomp.TypeInference|getJSType|com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.TypeInference:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ControlFlowGraph,com.google.javascript.jscomp.type.ReverseAbstractInterpreter,com.google.javascript.jscomp.Scope,java.util.Map",
        "M|com.google.javascript.jscomp.TypeInference|getNativeType|com.google.javascript.rhino.jstype.JSTypeNative|new:com.google.javascript.jscomp.TypeInference:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ControlFlowGraph,com.google.javascript.jscomp.type.ReverseAbstractInterpreter,com.google.javascript.jscomp.Scope,java.util.Map",
        "M|com.google.javascript.jscomp.TypeInference|getPropertyType|com.google.javascript.rhino.jstype.JSType,java.lang.String,com.google.javascript.rhino.Node,com.google.javascript.jscomp.type.FlowScope|new:com.google.javascript.jscomp.TypeInference:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ControlFlowGraph,com.google.javascript.jscomp.type.ReverseAbstractInterpreter,com.google.javascript.jscomp.Scope,java.util.Map",
        "M|com.google.javascript.jscomp.TypeInference|inferPropertyTypesToMatchConstraint|com.google.javascript.rhino.jstype.JSType,com.google.javascript.rhino.jstype.JSType|new:com.google.javascript.jscomp.TypeInference:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ControlFlowGraph,com.google.javascript.jscomp.type.ReverseAbstractInterpreter,com.google.javascript.jscomp.Scope,java.util.Map",
        "M|com.google.javascript.jscomp.TypeInference|traverseNew|com.google.javascript.rhino.Node,com.google.javascript.jscomp.type.FlowScope|new:com.google.javascript.jscomp.TypeInference:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ControlFlowGraph,com.google.javascript.jscomp.type.ReverseAbstractInterpreter,com.google.javascript.jscomp.Scope,java.util.Map",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 16) int w0, @InRange(minInt = 0, maxInt = 16) int w1, @InRange(minInt = 0, maxInt = 16) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
