package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 1 patched method(s), 10 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.apache.commons.math.stat.clustering.KMeansPlusPlusClusterer|chooseInitialCenters|java.util.Collection,int,java.util.Random|static",
        "M|org.apache.commons.math.stat.clustering.KMeansPlusPlusClusterer|assignPointsToClusters|java.util.Collection,java.util.Collection|static",
        "M|org.apache.commons.math.stat.clustering.KMeansPlusPlusClusterer|cluster|java.util.Collection,int,int|new:org.apache.commons.math.stat.clustering.KMeansPlusPlusClusterer:java.util.Random",
        "M|org.apache.commons.math.stat.clustering.KMeansPlusPlusClusterer|getFarthestPoint|java.util.Collection|new:org.apache.commons.math.stat.clustering.KMeansPlusPlusClusterer:java.util.Random",
        "M|org.apache.commons.math.stat.clustering.KMeansPlusPlusClusterer|getNearestCluster|java.util.Collection,org.apache.commons.math.stat.clustering.Clusterable|static",
        "M|org.apache.commons.math.stat.clustering.KMeansPlusPlusClusterer|getPointFromLargestNumberCluster|java.util.Collection|new:org.apache.commons.math.stat.clustering.KMeansPlusPlusClusterer:java.util.Random",
        "M|org.apache.commons.math.stat.clustering.KMeansPlusPlusClusterer|getPointFromLargestVarianceCluster|java.util.Collection|new:org.apache.commons.math.stat.clustering.KMeansPlusPlusClusterer:java.util.Random",
        "C|org.apache.commons.math.stat.clustering.KMeansPlusPlusClusterer|<init>|java.util.Random",
        "C|org.apache.commons.math.stat.clustering.KMeansPlusPlusClusterer|<init>|java.util.Random,org.apache.commons.math.stat.clustering.KMeansPlusPlusClusterer$EmptyClusterStrategy",
        "M|org.apache.commons.math.stat.clustering.KMeansPlusPlusClusterer|chooseInitialCenters|java.util.Collection,int,java.util.Random|static",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 9) int w0, @InRange(minInt = 0, maxInt = 9) int w1, @InRange(minInt = 0, maxInt = 9) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
