package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 1 patched method(s), 17 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp|unixTimeToZipLong|long|static",
        "M|org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp|clone||new:org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp:",
        "M|org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp|dateToZipLong|java.util.Date|static",
        "M|org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp|equals|java.lang.Object|new:org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp:",
        "M|org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp|getAccessJavaTime||new:org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp:",
        "M|org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp|getAccessTime||new:org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp:",
        "M|org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp|getCentralDirectoryData||new:org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp:",
        "M|org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp|getCentralDirectoryLength||new:org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp:",
        "M|org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp|getCreateJavaTime||new:org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp:",
        "M|org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp|getCreateTime||new:org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp:",
        "M|org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp|getFlags||new:org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp:",
        "M|org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp|getHeaderId||new:org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp:",
        "M|org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp|getLocalFileDataData||new:org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp:",
        "M|org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp|getLocalFileDataLength||new:org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp:",
        "M|org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp|getModifyJavaTime||new:org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp:",
        "M|org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp|getModifyTime||new:org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp:",
        "M|org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp|unixTimeToZipLong|long|static",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 16) int w0, @InRange(minInt = 0, maxInt = 16) int w1, @InRange(minInt = 0, maxInt = 16) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
