package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 1 patched method(s), 17 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.fasterxml.jackson.databind.ser.BeanPropertyWriter|serializeAsColumn|java.lang.Object,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider|new:com.fasterxml.jackson.databind.ser.BeanPropertyWriter:com.fasterxml.jackson.databind.ser.BeanPropertyWriter",
        "M|com.fasterxml.jackson.databind.ser.BeanPropertyWriter|_findAndAddDynamic|com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap,java.lang.Class,com.fasterxml.jackson.databind.SerializerProvider|new:com.fasterxml.jackson.databind.ser.BeanPropertyWriter:com.fasterxml.jackson.databind.ser.BeanPropertyWriter",
        "M|com.fasterxml.jackson.databind.ser.BeanPropertyWriter|_handleSelfReference|java.lang.Object,com.fasterxml.jackson.databind.JsonSerializer|new:com.fasterxml.jackson.databind.ser.BeanPropertyWriter:com.fasterxml.jackson.databind.ser.BeanPropertyWriter",
        "M|com.fasterxml.jackson.databind.ser.BeanPropertyWriter|assignNullSerializer|com.fasterxml.jackson.databind.JsonSerializer|new:com.fasterxml.jackson.databind.ser.BeanPropertyWriter:com.fasterxml.jackson.databind.ser.BeanPropertyWriter",
        "M|com.fasterxml.jackson.databind.ser.BeanPropertyWriter|assignSerializer|com.fasterxml.jackson.databind.JsonSerializer|new:com.fasterxml.jackson.databind.ser.BeanPropertyWriter:com.fasterxml.jackson.databind.ser.BeanPropertyWriter",
        "M|com.fasterxml.jackson.databind.ser.BeanPropertyWriter|depositSchemaProperty|com.fasterxml.jackson.databind.jsonFormatVisitors.JsonObjectFormatVisitor|new:com.fasterxml.jackson.databind.ser.BeanPropertyWriter:com.fasterxml.jackson.databind.ser.BeanPropertyWriter",
        "M|com.fasterxml.jackson.databind.ser.BeanPropertyWriter|depositSchemaProperty|com.fasterxml.jackson.databind.node.ObjectNode,com.fasterxml.jackson.databind.SerializerProvider|new:com.fasterxml.jackson.databind.ser.BeanPropertyWriter:com.fasterxml.jackson.databind.ser.BeanPropertyWriter",
        "M|com.fasterxml.jackson.databind.ser.BeanPropertyWriter|get|java.lang.Object|new:com.fasterxml.jackson.databind.ser.BeanPropertyWriter:com.fasterxml.jackson.databind.ser.BeanPropertyWriter",
        "M|com.fasterxml.jackson.databind.ser.BeanPropertyWriter|getAnnotation|java.lang.Class|new:com.fasterxml.jackson.databind.ser.BeanPropertyWriter:com.fasterxml.jackson.databind.ser.BeanPropertyWriter",
        "M|com.fasterxml.jackson.databind.ser.BeanPropertyWriter|getContextAnnotation|java.lang.Class|new:com.fasterxml.jackson.databind.ser.BeanPropertyWriter:com.fasterxml.jackson.databind.ser.BeanPropertyWriter",
        "M|com.fasterxml.jackson.databind.ser.BeanPropertyWriter|getGenericPropertyType||new:com.fasterxml.jackson.databind.ser.BeanPropertyWriter:com.fasterxml.jackson.databind.ser.BeanPropertyWriter",
        "M|com.fasterxml.jackson.databind.ser.BeanPropertyWriter|getInternalSetting|java.lang.Object|new:com.fasterxml.jackson.databind.ser.BeanPropertyWriter:com.fasterxml.jackson.databind.ser.BeanPropertyWriter",
        "M|com.fasterxml.jackson.databind.ser.BeanPropertyWriter|getMember||new:com.fasterxml.jackson.databind.ser.BeanPropertyWriter:com.fasterxml.jackson.databind.ser.BeanPropertyWriter",
        "M|com.fasterxml.jackson.databind.ser.BeanPropertyWriter|getName||new:com.fasterxml.jackson.databind.ser.BeanPropertyWriter:com.fasterxml.jackson.databind.ser.BeanPropertyWriter",
        "M|com.fasterxml.jackson.databind.ser.BeanPropertyWriter|getPropertyType||new:com.fasterxml.jackson.databind.ser.BeanPropertyWriter:com.fasterxml.jackson.databind.ser.BeanPropertyWriter",
        "M|com.fasterxml.jackson.databind.ser.BeanPropertyWriter|getRawSerializationType||new:com.fasterxml.jackson.databind.ser.BeanPropertyWriter:com.fasterxml.jackson.databind.ser.BeanPropertyWriter",
        "M|com.fasterxml.jackson.databind.ser.BeanPropertyWriter|serializeAsColumn|java.lang.Object,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider|new:com.fasterxml.jackson.databind.ser.BeanPropertyWriter:com.fasterxml.jackson.databind.ser.BeanPropertyWriter",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 16) int w0, @InRange(minInt = 0, maxInt = 16) int w1, @InRange(minInt = 0, maxInt = 16) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
