package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 1 patched method(s), 17 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.google.javascript.jscomp.FunctionInjector|canInlineReferenceDirectly|com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.FunctionInjector:com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier,boolean,boolean,boolean",
        "M|com.google.javascript.jscomp.FunctionInjector|callMeetsBlockInliningRequirements|com.google.javascript.jscomp.NodeTraversal,com.google.javascript.rhino.Node,com.google.javascript.rhino.Node,java.util.Set|new:com.google.javascript.jscomp.FunctionInjector:com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier,boolean,boolean,boolean",
        "M|com.google.javascript.jscomp.FunctionInjector|canInlineReferenceAsStatementBlock|com.google.javascript.jscomp.NodeTraversal,com.google.javascript.rhino.Node,com.google.javascript.rhino.Node,java.util.Set|new:com.google.javascript.jscomp.FunctionInjector:com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier,boolean,boolean,boolean",
        "M|com.google.javascript.jscomp.FunctionInjector|canInlineReferenceToFunction|com.google.javascript.jscomp.NodeTraversal,com.google.javascript.rhino.Node,com.google.javascript.rhino.Node,java.util.Set,com.google.javascript.jscomp.FunctionInjector$InliningMode,boolean,boolean|new:com.google.javascript.jscomp.FunctionInjector:com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier,boolean,boolean,boolean",
        "M|com.google.javascript.jscomp.FunctionInjector|classifyCallSite|com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.FunctionInjector:com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier,boolean,boolean,boolean",
        "M|com.google.javascript.jscomp.FunctionInjector|doesFunctionMeetMinimumRequirements|java.lang.String,com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.FunctionInjector:com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier,boolean,boolean,boolean",
        "M|com.google.javascript.jscomp.FunctionInjector|doesLowerCost|com.google.javascript.rhino.Node,int,int,int,int,int,boolean|new:com.google.javascript.jscomp.FunctionInjector:com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier,boolean,boolean,boolean",
        "M|com.google.javascript.jscomp.FunctionInjector|estimateCallCost|com.google.javascript.rhino.Node,boolean|static",
        "M|com.google.javascript.jscomp.FunctionInjector|getDecomposer||new:com.google.javascript.jscomp.FunctionInjector:com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier,boolean,boolean,boolean",
        "M|com.google.javascript.jscomp.FunctionInjector|inline|com.google.javascript.rhino.Node,java.lang.String,com.google.javascript.rhino.Node,com.google.javascript.jscomp.FunctionInjector$InliningMode|new:com.google.javascript.jscomp.FunctionInjector:com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier,boolean,boolean,boolean",
        "M|com.google.javascript.jscomp.FunctionInjector|inlineCostDelta|com.google.javascript.rhino.Node,java.util.Set,com.google.javascript.jscomp.FunctionInjector$InliningMode|static",
        "M|com.google.javascript.jscomp.FunctionInjector|inlineFunction|com.google.javascript.rhino.Node,com.google.javascript.rhino.Node,java.lang.String|new:com.google.javascript.jscomp.FunctionInjector:com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier,boolean,boolean,boolean",
        "M|com.google.javascript.jscomp.FunctionInjector|inlineReturnValue|com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.FunctionInjector:com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier,boolean,boolean,boolean",
        "M|com.google.javascript.jscomp.FunctionInjector|inliningLowersCost|com.google.javascript.jscomp.JSModule,com.google.javascript.rhino.Node,java.util.Collection,java.util.Set,boolean,boolean|new:com.google.javascript.jscomp.FunctionInjector:com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier,boolean,boolean,boolean",
        "M|com.google.javascript.jscomp.FunctionInjector|isDirectCallNodeReplacementPossible|com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.FunctionInjector:com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier,boolean,boolean,boolean",
        "M|com.google.javascript.jscomp.FunctionInjector|isSupportedCallType|com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.FunctionInjector:com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier,boolean,boolean,boolean",
        "M|com.google.javascript.jscomp.FunctionInjector|canInlineReferenceDirectly|com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.FunctionInjector:com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier,boolean,boolean,boolean",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 16) int w0, @InRange(minInt = 0, maxInt = 16) int w1, @InRange(minInt = 0, maxInt = 16) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
