package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 0 patched method(s), 11 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.google.javascript.jscomp.DisambiguateProperties|addInvalidatingType|com.google.javascript.rhino.jstype.JSType,com.google.javascript.jscomp.JSError|new:com.google.javascript.jscomp.DisambiguateProperties:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.DisambiguateProperties$TypeSystem,java.util.Map",
        "M|com.google.javascript.jscomp.DisambiguateProperties|buildPropNames|com.google.javascript.jscomp.graph.UnionFind,java.lang.String|new:com.google.javascript.jscomp.DisambiguateProperties:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.DisambiguateProperties$TypeSystem,java.util.Map",
        "M|com.google.javascript.jscomp.DisambiguateProperties|forConcreteTypeSystem|com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.TightenTypes,java.util.Map|static",
        "M|com.google.javascript.jscomp.DisambiguateProperties|forJSTypeSystem|com.google.javascript.jscomp.AbstractCompiler,java.util.Map|static",
        "M|com.google.javascript.jscomp.DisambiguateProperties|getProperty|java.lang.String|new:com.google.javascript.jscomp.DisambiguateProperties:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.DisambiguateProperties$TypeSystem,java.util.Map",
        "M|com.google.javascript.jscomp.DisambiguateProperties|getRenamedTypesForTesting||new:com.google.javascript.jscomp.DisambiguateProperties:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.DisambiguateProperties$TypeSystem,java.util.Map",
        "M|com.google.javascript.jscomp.DisambiguateProperties|getTypeWithProperty|java.lang.String,java.lang.Object|new:com.google.javascript.jscomp.DisambiguateProperties:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.DisambiguateProperties$TypeSystem,java.util.Map",
        "M|com.google.javascript.jscomp.DisambiguateProperties|process|com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.DisambiguateProperties:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.DisambiguateProperties$TypeSystem,java.util.Map",
        "M|com.google.javascript.jscomp.DisambiguateProperties|recordInvalidationError|com.google.javascript.rhino.jstype.JSType,com.google.javascript.jscomp.JSError|new:com.google.javascript.jscomp.DisambiguateProperties:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.DisambiguateProperties$TypeSystem,java.util.Map",
        "M|com.google.javascript.jscomp.DisambiguateProperties|renameProperties||new:com.google.javascript.jscomp.DisambiguateProperties:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.DisambiguateProperties$TypeSystem,java.util.Map",
        "C|com.google.javascript.jscomp.DisambiguateProperties|<init>|com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.DisambiguateProperties$TypeSystem,java.util.Map",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 10) int w0, @InRange(minInt = 0, maxInt = 10) int w1, @InRange(minInt = 0, maxInt = 10) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
