package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 0 patched method(s), 13 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.google.javascript.jscomp.ReferenceCollectingCallback|addReference|com.google.javascript.jscomp.Scope$Var,com.google.javascript.jscomp.ReferenceCollectingCallback$Reference|new:com.google.javascript.jscomp.ReferenceCollectingCallback:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ReferenceCollectingCallback$Behavior",
        "M|com.google.javascript.jscomp.ReferenceCollectingCallback|enterScope|com.google.javascript.jscomp.NodeTraversal|new:com.google.javascript.jscomp.ReferenceCollectingCallback:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ReferenceCollectingCallback$Behavior",
        "M|com.google.javascript.jscomp.ReferenceCollectingCallback|exitScope|com.google.javascript.jscomp.NodeTraversal|new:com.google.javascript.jscomp.ReferenceCollectingCallback:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ReferenceCollectingCallback$Behavior",
        "M|com.google.javascript.jscomp.ReferenceCollectingCallback|getAllSymbols||new:com.google.javascript.jscomp.ReferenceCollectingCallback:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ReferenceCollectingCallback$Behavior",
        "M|com.google.javascript.jscomp.ReferenceCollectingCallback|getReferences|com.google.javascript.jscomp.Scope$Var|new:com.google.javascript.jscomp.ReferenceCollectingCallback:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ReferenceCollectingCallback$Behavior",
        "M|com.google.javascript.jscomp.ReferenceCollectingCallback|getScope|com.google.javascript.jscomp.Scope$Var|new:com.google.javascript.jscomp.ReferenceCollectingCallback:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ReferenceCollectingCallback$Behavior",
        "M|com.google.javascript.jscomp.ReferenceCollectingCallback|hotSwapScript|com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.ReferenceCollectingCallback:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ReferenceCollectingCallback$Behavior",
        "M|com.google.javascript.jscomp.ReferenceCollectingCallback|isBlockBoundary|com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|static",
        "M|com.google.javascript.jscomp.ReferenceCollectingCallback|process|com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.ReferenceCollectingCallback:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ReferenceCollectingCallback$Behavior",
        "M|com.google.javascript.jscomp.ReferenceCollectingCallback|shouldTraverse|com.google.javascript.jscomp.NodeTraversal,com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.ReferenceCollectingCallback:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ReferenceCollectingCallback$Behavior",
        "M|com.google.javascript.jscomp.ReferenceCollectingCallback|visit|com.google.javascript.jscomp.NodeTraversal,com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.ReferenceCollectingCallback:com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ReferenceCollectingCallback$Behavior",
        "C|com.google.javascript.jscomp.ReferenceCollectingCallback|<init>|com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ReferenceCollectingCallback$Behavior,com.google.common.base.Predicate",
        "C|com.google.javascript.jscomp.ReferenceCollectingCallback|<init>|com.google.javascript.jscomp.AbstractCompiler,com.google.javascript.jscomp.ReferenceCollectingCallback$Behavior",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 12) int w0, @InRange(minInt = 0, maxInt = 12) int w1, @InRange(minInt = 0, maxInt = 12) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
