package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 6 patched method(s), 22 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.jfree.chart.util.ShapeUtilities|equal|java.awt.Polygon,java.awt.Polygon|static",
        "M|org.jfree.chart.util.ShapeUtilities|equal|java.awt.Shape,java.awt.Shape|static",
        "M|org.jfree.chart.util.ShapeUtilities|equal|java.awt.geom.Arc2D,java.awt.geom.Arc2D|static",
        "M|org.jfree.chart.util.ShapeUtilities|equal|java.awt.geom.Ellipse2D,java.awt.geom.Ellipse2D|static",
        "M|org.jfree.chart.util.ShapeUtilities|equal|java.awt.geom.GeneralPath,java.awt.geom.GeneralPath|static",
        "M|org.jfree.chart.util.ShapeUtilities|equal|java.awt.geom.Line2D,java.awt.geom.Line2D|static",
        "M|org.jfree.chart.util.ShapeUtilities|clone|java.awt.Shape|static",
        "M|org.jfree.chart.util.ShapeUtilities|contains|java.awt.geom.Rectangle2D,java.awt.geom.Rectangle2D|static",
        "M|org.jfree.chart.util.ShapeUtilities|createDiagonalCross|float,float|static",
        "M|org.jfree.chart.util.ShapeUtilities|createDiamond|float|static",
        "M|org.jfree.chart.util.ShapeUtilities|createDownTriangle|float|static",
        "M|org.jfree.chart.util.ShapeUtilities|createLineRegion|java.awt.geom.Line2D,float|static",
        "M|org.jfree.chart.util.ShapeUtilities|createRegularCross|float,float|static",
        "M|org.jfree.chart.util.ShapeUtilities|createTranslatedShape|java.awt.Shape,double,double|static",
        "M|org.jfree.chart.util.ShapeUtilities|createTranslatedShape|java.awt.Shape,org.jfree.chart.util.RectangleAnchor,double,double|static",
        "M|org.jfree.chart.util.ShapeUtilities|createUpTriangle|float|static",
        "M|org.jfree.chart.util.ShapeUtilities|equal|java.awt.Polygon,java.awt.Polygon|static",
        "M|org.jfree.chart.util.ShapeUtilities|equal|java.awt.Shape,java.awt.Shape|static",
        "M|org.jfree.chart.util.ShapeUtilities|equal|java.awt.geom.Arc2D,java.awt.geom.Arc2D|static",
        "M|org.jfree.chart.util.ShapeUtilities|equal|java.awt.geom.Ellipse2D,java.awt.geom.Ellipse2D|static",
        "M|org.jfree.chart.util.ShapeUtilities|equal|java.awt.geom.GeneralPath,java.awt.geom.GeneralPath|static",
        "M|org.jfree.chart.util.ShapeUtilities|equal|java.awt.geom.Line2D,java.awt.geom.Line2D|static",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 21) int w0, @InRange(minInt = 0, maxInt = 21) int w1, @InRange(minInt = 0, maxInt = 21) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
