package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 3 patched method(s), 19 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.apache.commons.codec.language.Caverphone|caverphone|java.lang.String|new:org.apache.commons.codec.language.Caverphone:",
        "M|org.apache.commons.codec.language.Metaphone|metaphone|java.lang.String|new:org.apache.commons.codec.language.Metaphone:",
        "M|org.apache.commons.codec.language.SoundexUtils|clean|java.lang.String|static",
        "M|org.apache.commons.codec.language.Caverphone|encode|java.lang.Object|new:org.apache.commons.codec.language.Caverphone:",
        "M|org.apache.commons.codec.language.Caverphone|encode|java.lang.String|new:org.apache.commons.codec.language.Caverphone:",
        "M|org.apache.commons.codec.language.Caverphone|isCaverphoneEqual|java.lang.String,java.lang.String|new:org.apache.commons.codec.language.Caverphone:",
        "C|org.apache.commons.codec.language.Caverphone|<init>|",
        "M|org.apache.commons.codec.language.Metaphone|encode|java.lang.Object|new:org.apache.commons.codec.language.Metaphone:",
        "M|org.apache.commons.codec.language.Metaphone|encode|java.lang.String|new:org.apache.commons.codec.language.Metaphone:",
        "M|org.apache.commons.codec.language.Metaphone|getMaxCodeLen||new:org.apache.commons.codec.language.Metaphone:",
        "M|org.apache.commons.codec.language.Metaphone|isLastChar|int,int|new:org.apache.commons.codec.language.Metaphone:",
        "M|org.apache.commons.codec.language.Metaphone|isMetaphoneEqual|java.lang.String,java.lang.String|new:org.apache.commons.codec.language.Metaphone:",
        "M|org.apache.commons.codec.language.Metaphone|isNextChar|java.lang.StringBuffer,int,char|new:org.apache.commons.codec.language.Metaphone:",
        "M|org.apache.commons.codec.language.Metaphone|isPreviousChar|java.lang.StringBuffer,int,char|new:org.apache.commons.codec.language.Metaphone:",
        "M|org.apache.commons.codec.language.Metaphone|isVowel|java.lang.StringBuffer,int|new:org.apache.commons.codec.language.Metaphone:",
        "M|org.apache.commons.codec.language.Metaphone|regionMatch|java.lang.StringBuffer,int,java.lang.String|new:org.apache.commons.codec.language.Metaphone:",
        "M|org.apache.commons.codec.language.Caverphone|caverphone|java.lang.String|new:org.apache.commons.codec.language.Caverphone:",
        "M|org.apache.commons.codec.language.Metaphone|metaphone|java.lang.String|new:org.apache.commons.codec.language.Metaphone:",
        "M|org.apache.commons.codec.language.SoundexUtils|clean|java.lang.String|static",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 18) int w0, @InRange(minInt = 0, maxInt = 18) int w1, @InRange(minInt = 0, maxInt = 18) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
