package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 4 patched method(s), 20 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.apache.commons.math.linear.OpenMapRealVector|ebeDivide|[D|new:org.apache.commons.math.linear.OpenMapRealVector:",
        "M|org.apache.commons.math.linear.OpenMapRealVector|ebeDivide|org.apache.commons.math.linear.RealVector|new:org.apache.commons.math.linear.OpenMapRealVector:",
        "M|org.apache.commons.math.linear.OpenMapRealVector|ebeMultiply|[D|new:org.apache.commons.math.linear.OpenMapRealVector:",
        "M|org.apache.commons.math.linear.OpenMapRealVector|ebeMultiply|org.apache.commons.math.linear.RealVector|new:org.apache.commons.math.linear.OpenMapRealVector:",
        "M|org.apache.commons.math.linear.OpenMapRealVector|add|org.apache.commons.math.linear.OpenMapRealVector|new:org.apache.commons.math.linear.OpenMapRealVector:",
        "M|org.apache.commons.math.linear.OpenMapRealVector|add|org.apache.commons.math.linear.RealVector|new:org.apache.commons.math.linear.OpenMapRealVector:",
        "M|org.apache.commons.math.linear.OpenMapRealVector|append|double|new:org.apache.commons.math.linear.OpenMapRealVector:",
        "M|org.apache.commons.math.linear.OpenMapRealVector|append|[D|new:org.apache.commons.math.linear.OpenMapRealVector:",
        "M|org.apache.commons.math.linear.OpenMapRealVector|append|org.apache.commons.math.linear.OpenMapRealVector|new:org.apache.commons.math.linear.OpenMapRealVector:",
        "M|org.apache.commons.math.linear.OpenMapRealVector|append|org.apache.commons.math.linear.RealVector|new:org.apache.commons.math.linear.OpenMapRealVector:",
        "M|org.apache.commons.math.linear.OpenMapRealVector|copy||new:org.apache.commons.math.linear.OpenMapRealVector:",
        "M|org.apache.commons.math.linear.OpenMapRealVector|dotProduct|org.apache.commons.math.linear.OpenMapRealVector|new:org.apache.commons.math.linear.OpenMapRealVector:",
        "M|org.apache.commons.math.linear.OpenMapRealVector|dotProduct|org.apache.commons.math.linear.RealVector|new:org.apache.commons.math.linear.OpenMapRealVector:",
        "M|org.apache.commons.math.linear.OpenMapRealVector|equals|java.lang.Object|new:org.apache.commons.math.linear.OpenMapRealVector:",
        "M|org.apache.commons.math.linear.OpenMapRealVector|getData||new:org.apache.commons.math.linear.OpenMapRealVector:",
        "M|org.apache.commons.math.linear.OpenMapRealVector|getDimension||new:org.apache.commons.math.linear.OpenMapRealVector:",
        "M|org.apache.commons.math.linear.OpenMapRealVector|ebeDivide|[D|new:org.apache.commons.math.linear.OpenMapRealVector:",
        "M|org.apache.commons.math.linear.OpenMapRealVector|ebeDivide|org.apache.commons.math.linear.RealVector|new:org.apache.commons.math.linear.OpenMapRealVector:",
        "M|org.apache.commons.math.linear.OpenMapRealVector|ebeMultiply|[D|new:org.apache.commons.math.linear.OpenMapRealVector:",
        "M|org.apache.commons.math.linear.OpenMapRealVector|ebeMultiply|org.apache.commons.math.linear.RealVector|new:org.apache.commons.math.linear.OpenMapRealVector:",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 19) int w0, @InRange(minInt = 0, maxInt = 19) int w1, @InRange(minInt = 0, maxInt = 19) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
