package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 1 patched method(s), 17 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.apache.commons.math3.optimization.general.AbstractLeastSquaresOptimizer|squareRoot|org.apache.commons.math3.linear.RealMatrix|new:org.apache.commons.math3.optimization.general.GaussNewtonOptimizer:",
        "M|org.apache.commons.math3.optimization.general.AbstractLeastSquaresOptimizer|computeCost|[D|new:org.apache.commons.math3.optimization.general.GaussNewtonOptimizer:",
        "M|org.apache.commons.math3.optimization.general.AbstractLeastSquaresOptimizer|computeCovariances|[D,double|new:org.apache.commons.math3.optimization.general.GaussNewtonOptimizer:",
        "M|org.apache.commons.math3.optimization.general.AbstractLeastSquaresOptimizer|computeResiduals|[D|new:org.apache.commons.math3.optimization.general.GaussNewtonOptimizer:",
        "M|org.apache.commons.math3.optimization.general.AbstractLeastSquaresOptimizer|computeSigma|[D,double|new:org.apache.commons.math3.optimization.general.GaussNewtonOptimizer:",
        "M|org.apache.commons.math3.optimization.general.AbstractLeastSquaresOptimizer|computeWeightedJacobian|[D|new:org.apache.commons.math3.optimization.general.GaussNewtonOptimizer:",
        "M|org.apache.commons.math3.optimization.general.AbstractLeastSquaresOptimizer|getChiSquare||new:org.apache.commons.math3.optimization.general.GaussNewtonOptimizer:",
        "M|org.apache.commons.math3.optimization.general.AbstractLeastSquaresOptimizer|getCovariances||new:org.apache.commons.math3.optimization.general.GaussNewtonOptimizer:",
        "M|org.apache.commons.math3.optimization.general.AbstractLeastSquaresOptimizer|getCovariances|double|new:org.apache.commons.math3.optimization.general.GaussNewtonOptimizer:",
        "M|org.apache.commons.math3.optimization.general.AbstractLeastSquaresOptimizer|getJacobianEvaluations||new:org.apache.commons.math3.optimization.general.GaussNewtonOptimizer:",
        "M|org.apache.commons.math3.optimization.general.AbstractLeastSquaresOptimizer|getRMS||new:org.apache.commons.math3.optimization.general.GaussNewtonOptimizer:",
        "M|org.apache.commons.math3.optimization.general.AbstractLeastSquaresOptimizer|getWeightSquareRoot||new:org.apache.commons.math3.optimization.general.GaussNewtonOptimizer:",
        "M|org.apache.commons.math3.optimization.general.AbstractLeastSquaresOptimizer|guessParametersErrors||new:org.apache.commons.math3.optimization.general.GaussNewtonOptimizer:",
        "M|org.apache.commons.math3.optimization.general.AbstractLeastSquaresOptimizer|optimize|int,org.apache.commons.math3.analysis.DifferentiableMultivariateVectorFunction,[D,[D,[D|new:org.apache.commons.math3.optimization.general.GaussNewtonOptimizer:",
        "M|org.apache.commons.math3.optimization.general.AbstractLeastSquaresOptimizer|optimize|int,org.apache.commons.math3.analysis.differentiation.MultivariateDifferentiableVectorFunction,[D,[D,[D|new:org.apache.commons.math3.optimization.general.GaussNewtonOptimizer:",
        "M|org.apache.commons.math3.optimization.general.AbstractLeastSquaresOptimizer|optimizeInternal|int,org.apache.commons.math3.analysis.differentiation.MultivariateDifferentiableVectorFunction,[Lorg.apache.commons.math3.optimization.OptimizationData;|new:org.apache.commons.math3.optimization.general.GaussNewtonOptimizer:",
        "M|org.apache.commons.math3.optimization.general.AbstractLeastSquaresOptimizer|squareRoot|org.apache.commons.math3.linear.RealMatrix|new:org.apache.commons.math3.optimization.general.GaussNewtonOptimizer:",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 16) int w0, @InRange(minInt = 0, maxInt = 16) int w1, @InRange(minInt = 0, maxInt = 16) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
