package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 3 patched method(s), 19 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.google.javascript.rhino.IR|blockUnchecked|com.google.javascript.rhino.Node|static",
        "M|com.google.javascript.rhino.IR|tryCatch|com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|static",
        "M|com.google.javascript.rhino.IR|tryFinally|com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|static",
        "M|com.google.javascript.rhino.IR|add|com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|static",
        "M|com.google.javascript.rhino.IR|and|com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|static",
        "M|com.google.javascript.rhino.IR|arraylit|[Lcom.google.javascript.rhino.Node;|static",
        "M|com.google.javascript.rhino.IR|assign|com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|static",
        "M|com.google.javascript.rhino.IR|binaryOp|int,com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|static",
        "M|com.google.javascript.rhino.IR|block||static",
        "M|com.google.javascript.rhino.IR|block|com.google.javascript.rhino.Node|static",
        "M|com.google.javascript.rhino.IR|block|[Lcom.google.javascript.rhino.Node;|static",
        "M|com.google.javascript.rhino.IR|breakNode||static",
        "M|com.google.javascript.rhino.IR|breakNode|com.google.javascript.rhino.Node|static",
        "M|com.google.javascript.rhino.IR|call|com.google.javascript.rhino.Node,[Lcom.google.javascript.rhino.Node;|static",
        "M|com.google.javascript.rhino.IR|caseNode|com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|static",
        "M|com.google.javascript.rhino.IR|catchNode|com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|static",
        "M|com.google.javascript.rhino.IR|blockUnchecked|com.google.javascript.rhino.Node|static",
        "M|com.google.javascript.rhino.IR|tryCatch|com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|static",
        "M|com.google.javascript.rhino.IR|tryFinally|com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|static",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 18) int w0, @InRange(minInt = 0, maxInt = 18) int w1, @InRange(minInt = 0, maxInt = 18) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
