package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 2 patched method(s), 18 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|checkIllegalTypes|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.BeanDescription|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|createBeanDeserializer|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.BeanDescription|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|addBeanProps|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.BeanDescription,com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|addInjectables|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.BeanDescription,com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|addObjectIdReader|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.BeanDescription,com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|addReferenceProperties|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.BeanDescription,com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|buildBeanDeserializer|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.BeanDescription|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|buildBuilderBasedDeserializer|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.BeanDescription|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|buildThrowableDeserializer|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.BeanDescription|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|constructAnySetter|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.BeanDescription,com.fasterxml.jackson.databind.introspect.AnnotatedMethod|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|constructBeanDeserializerBuilder|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.BeanDescription|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|constructSettableProperty|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.BeanDescription,com.fasterxml.jackson.databind.introspect.BeanPropertyDefinition,com.fasterxml.jackson.databind.JavaType|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|constructSetterlessProperty|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.BeanDescription,com.fasterxml.jackson.databind.introspect.BeanPropertyDefinition|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|createBuilderBasedDeserializer|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.BeanDescription,java.lang.Class|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|filterBeanProps|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.BeanDescription,com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder,java.util.List,java.util.Set|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|findStdDeserializer|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.BeanDescription|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|checkIllegalTypes|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.BeanDescription|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|createBeanDeserializer|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.BeanDescription|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 17) int w0, @InRange(minInt = 0, maxInt = 17) int w1, @InRange(minInt = 0, maxInt = 17) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
