package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 1 patched method(s), 10 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer|_deserializeTypedUsingDefaultImpl|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.util.TokenBuffer|new:com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer:com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer,com.fasterxml.jackson.databind.BeanProperty",
        "M|com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer|_deserializeTypedForId|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.util.TokenBuffer|new:com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer:com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer,com.fasterxml.jackson.databind.BeanProperty",
        "M|com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer|deserializeTypedFromAny|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext|new:com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer:com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer,com.fasterxml.jackson.databind.BeanProperty",
        "M|com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer|deserializeTypedFromObject|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext|new:com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer:com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer,com.fasterxml.jackson.databind.BeanProperty",
        "M|com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer|forProperty|com.fasterxml.jackson.databind.BeanProperty|new:com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer:com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer,com.fasterxml.jackson.databind.BeanProperty",
        "M|com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer|getTypeInclusion||new:com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer:com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer,com.fasterxml.jackson.databind.BeanProperty",
        "C|com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer|<init>|com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer,com.fasterxml.jackson.databind.BeanProperty",
        "C|com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer|<init>|com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.jsontype.TypeIdResolver,java.lang.String,boolean,com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.annotation.JsonTypeInfo$As",
        "C|com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer|<init>|com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.jsontype.TypeIdResolver,java.lang.String,boolean,com.fasterxml.jackson.databind.JavaType",
        "M|com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer|_deserializeTypedUsingDefaultImpl|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.util.TokenBuffer|new:com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer:com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer,com.fasterxml.jackson.databind.BeanProperty",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 9) int w0, @InRange(minInt = 0, maxInt = 9) int w1, @InRange(minInt = 0, maxInt = 9) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
