package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 29 patched method(s), 45 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.fasterxml.jackson.databind.DatabindContext|resolveSubType|com.fasterxml.jackson.databind.JavaType,java.lang.String|new:com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl:com.fasterxml.jackson.databind.deser.DeserializerFactory",
        "M|com.fasterxml.jackson.databind.DeserializationContext|instantiationException|java.lang.Class,java.lang.String|new:com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl:com.fasterxml.jackson.databind.deser.DeserializerFactory",
        "M|com.fasterxml.jackson.databind.DeserializationContext|instantiationException|java.lang.Class,java.lang.Throwable|new:com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl:com.fasterxml.jackson.databind.deser.DeserializerFactory",
        "M|com.fasterxml.jackson.databind.DeserializationContext|parseDate|java.lang.String|new:com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl:com.fasterxml.jackson.databind.deser.DeserializerFactory",
        "M|com.fasterxml.jackson.databind.JsonMappingException|fromUnexpectedIOE|java.io.IOException|static",
        "M|com.fasterxml.jackson.databind.JsonMappingException|wrapWithPath|java.lang.Throwable,com.fasterxml.jackson.databind.JsonMappingException$Reference|static",
        "M|com.fasterxml.jackson.databind.JsonMappingException|wrapWithPath|java.lang.Throwable,java.lang.Object,int|static",
        "M|com.fasterxml.jackson.databind.JsonMappingException|wrapWithPath|java.lang.Throwable,java.lang.Object,java.lang.String|static",
        "M|com.fasterxml.jackson.databind.SerializerProvider|_createAndCacheUntypedSerializer|com.fasterxml.jackson.databind.JavaType|new:com.fasterxml.jackson.databind.ser.DefaultSerializerProvider$Impl:",
        "M|com.fasterxml.jackson.databind.SerializerProvider|_createAndCacheUntypedSerializer|java.lang.Class|new:com.fasterxml.jackson.databind.ser.DefaultSerializerProvider$Impl:",
        "M|com.fasterxml.jackson.databind.deser.BasicDeserializerFactory|findTypeDeserializer|com.fasterxml.jackson.databind.DeserializationConfig,com.fasterxml.jackson.databind.JavaType|fld:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:instance",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|buildBeanDeserializer|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.BeanDescription|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|buildBuilderBasedDeserializer|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.BeanDescription|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
        "M|com.fasterxml.jackson.databind.deser.DeserializerCache|_createAndCache2|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.deser.DeserializerFactory,com.fasterxml.jackson.databind.JavaType|new:com.fasterxml.jackson.databind.deser.DeserializerCache:",
        "M|com.fasterxml.jackson.databind.deser.SettableAnyProperty|_throwAsIOE|java.lang.Exception,java.lang.Object,java.lang.Object|new:com.fasterxml.jackson.databind.deser.SettableAnyProperty:com.fasterxml.jackson.databind.BeanProperty,com.fasterxml.jackson.databind.introspect.AnnotatedMember,com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.JsonDeserializer,com.fasterxml.jackson.databind.jsontype.TypeDeserializer",
        "M|com.fasterxml.jackson.databind.deser.SettableBeanProperty|_throwAsIOE|com.fasterxml.jackson.core.JsonParser,java.lang.Exception|new:com.fasterxml.jackson.databind.deser.CreatorProperty:com.fasterxml.jackson.databind.deser.CreatorProperty,com.fasterxml.jackson.databind.PropertyName",
        "M|com.fasterxml.jackson.databind.DatabindContext|resolveSubType|com.fasterxml.jackson.databind.JavaType,java.lang.String|new:com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl:com.fasterxml.jackson.databind.deser.DeserializerFactory",
        "M|com.fasterxml.jackson.databind.DeserializationContext|instantiationException|java.lang.Class,java.lang.String|new:com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl:com.fasterxml.jackson.databind.deser.DeserializerFactory",
        "M|com.fasterxml.jackson.databind.DeserializationContext|instantiationException|java.lang.Class,java.lang.Throwable|new:com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl:com.fasterxml.jackson.databind.deser.DeserializerFactory",
        "M|com.fasterxml.jackson.databind.DeserializationContext|parseDate|java.lang.String|new:com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl:com.fasterxml.jackson.databind.deser.DeserializerFactory",
        "M|com.fasterxml.jackson.databind.JsonMappingException|fromUnexpectedIOE|java.io.IOException|static",
        "M|com.fasterxml.jackson.databind.JsonMappingException|wrapWithPath|java.lang.Throwable,com.fasterxml.jackson.databind.JsonMappingException$Reference|static",
        "M|com.fasterxml.jackson.databind.JsonMappingException|wrapWithPath|java.lang.Throwable,java.lang.Object,int|static",
        "M|com.fasterxml.jackson.databind.JsonMappingException|wrapWithPath|java.lang.Throwable,java.lang.Object,java.lang.String|static",
        "M|com.fasterxml.jackson.databind.SerializerProvider|_createAndCacheUntypedSerializer|com.fasterxml.jackson.databind.JavaType|new:com.fasterxml.jackson.databind.ser.DefaultSerializerProvider$Impl:",
        "M|com.fasterxml.jackson.databind.SerializerProvider|_createAndCacheUntypedSerializer|java.lang.Class|new:com.fasterxml.jackson.databind.ser.DefaultSerializerProvider$Impl:",
        "M|com.fasterxml.jackson.databind.deser.BasicDeserializerFactory|findTypeDeserializer|com.fasterxml.jackson.databind.DeserializationConfig,com.fasterxml.jackson.databind.JavaType|fld:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:instance",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|buildBeanDeserializer|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.BeanDescription|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
        "M|com.fasterxml.jackson.databind.deser.BeanDeserializerFactory|buildBuilderBasedDeserializer|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.BeanDescription|new:com.fasterxml.jackson.databind.deser.BeanDeserializerFactory:com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
        "M|com.fasterxml.jackson.databind.deser.DeserializerCache|_createAndCache2|com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.deser.DeserializerFactory,com.fasterxml.jackson.databind.JavaType|new:com.fasterxml.jackson.databind.deser.DeserializerCache:",
        "M|com.fasterxml.jackson.databind.deser.SettableAnyProperty|_throwAsIOE|java.lang.Exception,java.lang.Object,java.lang.Object|new:com.fasterxml.jackson.databind.deser.SettableAnyProperty:com.fasterxml.jackson.databind.BeanProperty,com.fasterxml.jackson.databind.introspect.AnnotatedMember,com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.JsonDeserializer,com.fasterxml.jackson.databind.jsontype.TypeDeserializer",
        "M|com.fasterxml.jackson.databind.deser.SettableBeanProperty|_throwAsIOE|com.fasterxml.jackson.core.JsonParser,java.lang.Exception|new:com.fasterxml.jackson.databind.deser.CreatorProperty:com.fasterxml.jackson.databind.deser.CreatorProperty,com.fasterxml.jackson.databind.PropertyName",
        "M|com.fasterxml.jackson.databind.deser.SettableBeanProperty|_throwAsIOE|java.lang.Exception|new:com.fasterxml.jackson.databind.deser.CreatorProperty:com.fasterxml.jackson.databind.deser.CreatorProperty,com.fasterxml.jackson.databind.PropertyName",
        "M|com.fasterxml.jackson.databind.deser.SettableBeanProperty|_throwAsIOE|com.fasterxml.jackson.core.JsonParser,java.lang.Exception,java.lang.Object|new:com.fasterxml.jackson.databind.deser.CreatorProperty:com.fasterxml.jackson.databind.deser.CreatorProperty,com.fasterxml.jackson.databind.PropertyName",
        "M|com.fasterxml.jackson.databind.deser.SettableBeanProperty|_throwAsIOE|java.lang.Exception,java.lang.Object|new:com.fasterxml.jackson.databind.deser.CreatorProperty:com.fasterxml.jackson.databind.deser.CreatorProperty,com.fasterxml.jackson.databind.PropertyName",
        "M|com.fasterxml.jackson.databind.deser.std.StdDeserializer|_parseDate|com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext|fld:com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer:instance",
        "M|com.fasterxml.jackson.databind.deser.std.StdDeserializer|_parseDate|java.lang.String,com.fasterxml.jackson.databind.DeserializationContext|fld:com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer:instance",
        "M|com.fasterxml.jackson.databind.deser.std.StdKeyDeserializer|_weirdKey|com.fasterxml.jackson.databind.DeserializationContext,java.lang.String,java.lang.Exception|new:com.fasterxml.jackson.databind.deser.std.StdKeyDeserializer:int,java.lang.Class",
        "M|com.fasterxml.jackson.databind.deser.std.StdKeyDeserializer|deserializeKey|java.lang.String,com.fasterxml.jackson.databind.DeserializationContext|new:com.fasterxml.jackson.databind.deser.std.StdKeyDeserializer:int,java.lang.Class",
        "M|com.fasterxml.jackson.databind.deser.std.StdValueInstantiator|wrapException|java.lang.Throwable|new:com.fasterxml.jackson.databind.deser.std.StdValueInstantiator:com.fasterxml.jackson.databind.deser.std.StdValueInstantiator",
        "M|com.fasterxml.jackson.databind.introspect.BasicBeanDescription|instantiateBean|boolean|new:com.fasterxml.jackson.databind.introspect.BasicBeanDescription:com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector",
        "M|com.fasterxml.jackson.databind.ser.DefaultSerializerProvider|_wrapAsIOE|com.fasterxml.jackson.core.JsonGenerator,java.lang.Exception|new:com.fasterxml.jackson.databind.ser.DefaultSerializerProvider$Impl:",
        "M|com.fasterxml.jackson.databind.ser.DefaultSerializerProvider|includeFilterSuppressNulls|java.lang.Object|new:com.fasterxml.jackson.databind.ser.DefaultSerializerProvider$Impl:",
        "M|com.fasterxml.jackson.databind.ser.PropertyBuilder|buildWriter|com.fasterxml.jackson.databind.SerializerProvider,com.fasterxml.jackson.databind.introspect.BeanPropertyDefinition,com.fasterxml.jackson.databind.JavaType,com.fasterxml.jackson.databind.JsonSerializer,com.fasterxml.jackson.databind.jsontype.TypeSerializer,com.fasterxml.jackson.databind.jsontype.TypeSerializer,com.fasterxml.jackson.databind.introspect.AnnotatedMember,boolean|new:com.fasterxml.jackson.databind.ser.PropertyBuilder:com.fasterxml.jackson.databind.SerializationConfig,com.fasterxml.jackson.databind.BeanDescription",
        "M|com.fasterxml.jackson.databind.util.ClassUtil|exceptionMessage|java.lang.Throwable|static",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 44) int w0, @InRange(minInt = 0, maxInt = 44) int w1, @InRange(minInt = 0, maxInt = 44) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
