package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 1 patched method(s), 17 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.google.javascript.jscomp.CollapseProperties|updateSimpleDeclaration|java.lang.String,com.google.javascript.jscomp.GlobalNamespace$Name,com.google.javascript.jscomp.GlobalNamespace$Ref|new:com.google.javascript.jscomp.CollapseProperties:com.google.javascript.jscomp.AbstractCompiler,boolean,boolean",
        "M|com.google.javascript.jscomp.CollapseProperties|addStubsForUndeclaredProperties|com.google.javascript.jscomp.GlobalNamespace$Name,java.lang.String,com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.CollapseProperties:com.google.javascript.jscomp.AbstractCompiler,boolean,boolean",
        "M|com.google.javascript.jscomp.CollapseProperties|appendPropForAlias|java.lang.String,java.lang.String|static",
        "M|com.google.javascript.jscomp.CollapseProperties|checkForHosedThisReferences|com.google.javascript.rhino.Node,com.google.javascript.rhino.JSDocInfo,com.google.javascript.jscomp.GlobalNamespace$Name|new:com.google.javascript.jscomp.CollapseProperties:com.google.javascript.jscomp.AbstractCompiler,boolean,boolean",
        "M|com.google.javascript.jscomp.CollapseProperties|checkNamespaces||new:com.google.javascript.jscomp.CollapseProperties:com.google.javascript.jscomp.AbstractCompiler,boolean,boolean",
        "M|com.google.javascript.jscomp.CollapseProperties|collapseDeclarationOfNameAndDescendants|com.google.javascript.jscomp.GlobalNamespace$Name,java.lang.String|new:com.google.javascript.jscomp.CollapseProperties:com.google.javascript.jscomp.AbstractCompiler,boolean,boolean",
        "M|com.google.javascript.jscomp.CollapseProperties|declareVarsForObjLitValues|com.google.javascript.jscomp.GlobalNamespace$Name,java.lang.String,com.google.javascript.rhino.Node,com.google.javascript.rhino.Node,com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.CollapseProperties:com.google.javascript.jscomp.AbstractCompiler,boolean,boolean",
        "M|com.google.javascript.jscomp.CollapseProperties|flattenNameRef|java.lang.String,com.google.javascript.rhino.Node,com.google.javascript.rhino.Node,java.lang.String|new:com.google.javascript.jscomp.CollapseProperties:com.google.javascript.jscomp.AbstractCompiler,boolean,boolean",
        "M|com.google.javascript.jscomp.CollapseProperties|flattenNameRefAtDepth|java.lang.String,com.google.javascript.rhino.Node,int,java.lang.String|new:com.google.javascript.jscomp.CollapseProperties:com.google.javascript.jscomp.AbstractCompiler,boolean,boolean",
        "M|com.google.javascript.jscomp.CollapseProperties|flattenPrefixes|java.lang.String,com.google.javascript.jscomp.GlobalNamespace$Name,int|new:com.google.javascript.jscomp.CollapseProperties:com.google.javascript.jscomp.AbstractCompiler,boolean,boolean",
        "M|com.google.javascript.jscomp.CollapseProperties|flattenReferencesTo|com.google.javascript.jscomp.GlobalNamespace$Name,java.lang.String|new:com.google.javascript.jscomp.CollapseProperties:com.google.javascript.jscomp.AbstractCompiler,boolean,boolean",
        "M|com.google.javascript.jscomp.CollapseProperties|flattenReferencesToCollapsibleDescendantNames|com.google.javascript.jscomp.GlobalNamespace$Name,java.lang.String|new:com.google.javascript.jscomp.CollapseProperties:com.google.javascript.jscomp.AbstractCompiler,boolean,boolean",
        "M|com.google.javascript.jscomp.CollapseProperties|inlineAliasIfPossible|com.google.javascript.jscomp.GlobalNamespace$Ref,com.google.javascript.jscomp.GlobalNamespace|new:com.google.javascript.jscomp.CollapseProperties:com.google.javascript.jscomp.AbstractCompiler,boolean,boolean",
        "M|com.google.javascript.jscomp.CollapseProperties|inlineAliases|com.google.javascript.jscomp.GlobalNamespace|new:com.google.javascript.jscomp.CollapseProperties:com.google.javascript.jscomp.AbstractCompiler,boolean,boolean",
        "M|com.google.javascript.jscomp.CollapseProperties|process|com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.CollapseProperties:com.google.javascript.jscomp.AbstractCompiler,boolean,boolean",
        "M|com.google.javascript.jscomp.CollapseProperties|updateFunctionDeclarationAtFunctionNode|com.google.javascript.jscomp.GlobalNamespace$Name|new:com.google.javascript.jscomp.CollapseProperties:com.google.javascript.jscomp.AbstractCompiler,boolean,boolean",
        "M|com.google.javascript.jscomp.CollapseProperties|updateSimpleDeclaration|java.lang.String,com.google.javascript.jscomp.GlobalNamespace$Name,com.google.javascript.jscomp.GlobalNamespace$Ref|new:com.google.javascript.jscomp.CollapseProperties:com.google.javascript.jscomp.AbstractCompiler,boolean,boolean",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 16) int w0, @InRange(minInt = 0, maxInt = 16) int w1, @InRange(minInt = 0, maxInt = 16) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
