package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 11 patched method(s), 27 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.jsoup.nodes.Element|append|java.lang.String|new:org.jsoup.nodes.Element:org.jsoup.parser.Tag,java.lang.String",
        "M|org.jsoup.nodes.Element|prepend|java.lang.String|new:org.jsoup.nodes.Element:org.jsoup.parser.Tag,java.lang.String",
        "M|org.jsoup.nodes.Element|wrap|java.lang.String|new:org.jsoup.nodes.Element:org.jsoup.parser.Tag,java.lang.String",
        "M|org.jsoup.parser.Parser|addChildToParent|org.jsoup.nodes.Element,boolean|new:org.jsoup.parser.Parser:java.lang.String,java.lang.String,boolean",
        "M|org.jsoup.parser.Parser|parseBodyFragmentRelaxed|java.lang.String,java.lang.String|static",
        "M|org.jsoup.parser.Parser|stackHasValidParent|org.jsoup.parser.Tag|new:org.jsoup.parser.Parser:java.lang.String,java.lang.String,boolean",
        "M|org.jsoup.parser.Tag|canContain|org.jsoup.parser.Tag|new:org.jsoup.parser.Tag:java.lang.String",
        "M|org.jsoup.parser.Tag|isValidAncestor|org.jsoup.parser.Tag|new:org.jsoup.parser.Tag:java.lang.String",
        "M|org.jsoup.parser.Tag|isValidParent|org.jsoup.parser.Tag|new:org.jsoup.parser.Tag:java.lang.String",
        "M|org.jsoup.parser.Tag|requiresSpecificParent||new:org.jsoup.parser.Tag:java.lang.String",
        "M|org.jsoup.parser.Tag|setParent|java.lang.String|new:org.jsoup.parser.Tag:java.lang.String",
        "M|org.jsoup.nodes.Element|accumulateParents|org.jsoup.nodes.Element,org.jsoup.select.Elements|static",
        "M|org.jsoup.nodes.Element|addClass|java.lang.String|new:org.jsoup.nodes.Element:org.jsoup.parser.Tag,java.lang.String",
        "M|org.jsoup.nodes.Element|appendChild|org.jsoup.nodes.Node|new:org.jsoup.nodes.Element:org.jsoup.parser.Tag,java.lang.String",
        "M|org.jsoup.nodes.Element|appendElement|java.lang.String|new:org.jsoup.nodes.Element:org.jsoup.parser.Tag,java.lang.String",
        "M|org.jsoup.nodes.Element|appendText|java.lang.String|new:org.jsoup.nodes.Element:org.jsoup.parser.Tag,java.lang.String",
        "M|org.jsoup.nodes.Element|append|java.lang.String|new:org.jsoup.nodes.Element:org.jsoup.parser.Tag,java.lang.String",
        "M|org.jsoup.nodes.Element|prepend|java.lang.String|new:org.jsoup.nodes.Element:org.jsoup.parser.Tag,java.lang.String",
        "M|org.jsoup.nodes.Element|wrap|java.lang.String|new:org.jsoup.nodes.Element:org.jsoup.parser.Tag,java.lang.String",
        "M|org.jsoup.parser.Parser|addChildToParent|org.jsoup.nodes.Element,boolean|new:org.jsoup.parser.Parser:java.lang.String,java.lang.String,boolean",
        "M|org.jsoup.parser.Parser|parseBodyFragmentRelaxed|java.lang.String,java.lang.String|static",
        "M|org.jsoup.parser.Parser|stackHasValidParent|org.jsoup.parser.Tag|new:org.jsoup.parser.Parser:java.lang.String,java.lang.String,boolean",
        "M|org.jsoup.parser.Tag|canContain|org.jsoup.parser.Tag|new:org.jsoup.parser.Tag:java.lang.String",
        "M|org.jsoup.parser.Tag|isValidAncestor|org.jsoup.parser.Tag|new:org.jsoup.parser.Tag:java.lang.String",
        "M|org.jsoup.parser.Tag|isValidParent|org.jsoup.parser.Tag|new:org.jsoup.parser.Tag:java.lang.String",
        "M|org.jsoup.parser.Tag|requiresSpecificParent||new:org.jsoup.parser.Tag:java.lang.String",
        "M|org.jsoup.parser.Tag|setParent|java.lang.String|new:org.jsoup.parser.Tag:java.lang.String",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 26) int w0, @InRange(minInt = 0, maxInt = 26) int w1, @InRange(minInt = 0, maxInt = 26) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
