package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 1 patched method(s), 17 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.apache.commons.lang.time.DateUtils|modify|java.util.Calendar,int,boolean|static",
        "M|org.apache.commons.lang.time.DateUtils|add|java.util.Date,int,int|static",
        "M|org.apache.commons.lang.time.DateUtils|addDays|java.util.Date,int|static",
        "M|org.apache.commons.lang.time.DateUtils|addHours|java.util.Date,int|static",
        "M|org.apache.commons.lang.time.DateUtils|addMilliseconds|java.util.Date,int|static",
        "M|org.apache.commons.lang.time.DateUtils|addMinutes|java.util.Date,int|static",
        "M|org.apache.commons.lang.time.DateUtils|addMonths|java.util.Date,int|static",
        "M|org.apache.commons.lang.time.DateUtils|addSeconds|java.util.Date,int|static",
        "M|org.apache.commons.lang.time.DateUtils|addWeeks|java.util.Date,int|static",
        "M|org.apache.commons.lang.time.DateUtils|addYears|java.util.Date,int|static",
        "M|org.apache.commons.lang.time.DateUtils|isSameDay|java.util.Calendar,java.util.Calendar|static",
        "M|org.apache.commons.lang.time.DateUtils|isSameDay|java.util.Date,java.util.Date|static",
        "M|org.apache.commons.lang.time.DateUtils|isSameInstant|java.util.Calendar,java.util.Calendar|static",
        "M|org.apache.commons.lang.time.DateUtils|isSameInstant|java.util.Date,java.util.Date|static",
        "M|org.apache.commons.lang.time.DateUtils|isSameLocalTime|java.util.Calendar,java.util.Calendar|static",
        "M|org.apache.commons.lang.time.DateUtils|iterator|java.lang.Object,int|static",
        "M|org.apache.commons.lang.time.DateUtils|modify|java.util.Calendar,int,boolean|static",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 16) int w0, @InRange(minInt = 0, maxInt = 16) int w1, @InRange(minInt = 0, maxInt = 16) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
