package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 3 patched method(s), 19 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector|findObjectReferenceInfo|com.fasterxml.jackson.databind.introspect.Annotated,com.fasterxml.jackson.databind.introspect.ObjectIdInfo|new:com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector:",
        "M|com.fasterxml.jackson.databind.introspect.ObjectIdInfo|empty||static",
        "M|com.fasterxml.jackson.databind.ser.std.BeanSerializerBase|createContextual|com.fasterxml.jackson.databind.SerializerProvider,com.fasterxml.jackson.databind.BeanProperty|new:com.fasterxml.jackson.databind.ser.BeanSerializer:com.fasterxml.jackson.databind.ser.std.BeanSerializerBase",
        "M|com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector|_classIfExplicit|java.lang.Class|new:com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector:",
        "M|com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector|_classIfExplicit|java.lang.Class,java.lang.Class|new:com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector:",
        "M|com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector|_constructNoTypeResolverBuilder||new:com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector:",
        "M|com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector|_constructStdTypeResolverBuilder||new:com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector:",
        "M|com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector|_constructVirtualProperty|com.fasterxml.jackson.databind.annotation.JsonAppend$Attr,com.fasterxml.jackson.databind.cfg.MapperConfig,com.fasterxml.jackson.databind.introspect.AnnotatedClass,com.fasterxml.jackson.databind.JavaType|new:com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector:",
        "M|com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector|_constructVirtualProperty|com.fasterxml.jackson.databind.annotation.JsonAppend$Prop,com.fasterxml.jackson.databind.cfg.MapperConfig,com.fasterxml.jackson.databind.introspect.AnnotatedClass|new:com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector:",
        "M|com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector|_findConstructorName|com.fasterxml.jackson.databind.introspect.Annotated|new:com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector:",
        "M|com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector|_findSortAlpha|com.fasterxml.jackson.databind.introspect.Annotated|new:com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector:",
        "M|com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector|_findTypeResolver|com.fasterxml.jackson.databind.cfg.MapperConfig,com.fasterxml.jackson.databind.introspect.Annotated,com.fasterxml.jackson.databind.JavaType|new:com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector:",
        "M|com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector|_isIgnorable|com.fasterxml.jackson.databind.introspect.Annotated|new:com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector:",
        "M|com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector|_propertyName|java.lang.String,java.lang.String|new:com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector:",
        "M|com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector|findAndAddVirtualProperties|com.fasterxml.jackson.databind.cfg.MapperConfig,com.fasterxml.jackson.databind.introspect.AnnotatedClass,java.util.List|new:com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector:",
        "M|com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector|findAutoDetectVisibility|com.fasterxml.jackson.databind.introspect.AnnotatedClass,com.fasterxml.jackson.databind.introspect.VisibilityChecker|new:com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector:",
        "M|com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector|findObjectReferenceInfo|com.fasterxml.jackson.databind.introspect.Annotated,com.fasterxml.jackson.databind.introspect.ObjectIdInfo|new:com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector:",
        "M|com.fasterxml.jackson.databind.introspect.ObjectIdInfo|empty||static",
        "M|com.fasterxml.jackson.databind.ser.std.BeanSerializerBase|createContextual|com.fasterxml.jackson.databind.SerializerProvider,com.fasterxml.jackson.databind.BeanProperty|new:com.fasterxml.jackson.databind.ser.BeanSerializer:com.fasterxml.jackson.databind.ser.std.BeanSerializerBase",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 18) int w0, @InRange(minInt = 0, maxInt = 18) int w1, @InRange(minInt = 0, maxInt = 18) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
