package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 2 patched method(s), 13 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.jfree.chart.renderer.category.StatisticalBarRenderer|drawHorizontalItem|java.awt.Graphics2D,org.jfree.chart.renderer.category.CategoryItemRendererState,java.awt.geom.Rectangle2D,org.jfree.chart.plot.CategoryPlot,org.jfree.chart.axis.CategoryAxis,org.jfree.chart.axis.ValueAxis,org.jfree.data.statistics.StatisticalCategoryDataset,int,int|new:org.jfree.chart.renderer.category.StatisticalBarRenderer:",
        "M|org.jfree.chart.renderer.category.StatisticalBarRenderer|drawVerticalItem|java.awt.Graphics2D,org.jfree.chart.renderer.category.CategoryItemRendererState,java.awt.geom.Rectangle2D,org.jfree.chart.plot.CategoryPlot,org.jfree.chart.axis.CategoryAxis,org.jfree.chart.axis.ValueAxis,org.jfree.data.statistics.StatisticalCategoryDataset,int,int|new:org.jfree.chart.renderer.category.StatisticalBarRenderer:",
        "M|org.jfree.chart.renderer.category.StatisticalBarRenderer|drawItem|java.awt.Graphics2D,org.jfree.chart.renderer.category.CategoryItemRendererState,java.awt.geom.Rectangle2D,org.jfree.chart.plot.CategoryPlot,org.jfree.chart.axis.CategoryAxis,org.jfree.chart.axis.ValueAxis,org.jfree.data.category.CategoryDataset,int,int,int|new:org.jfree.chart.renderer.category.StatisticalBarRenderer:",
        "M|org.jfree.chart.renderer.category.StatisticalBarRenderer|equals|java.lang.Object|new:org.jfree.chart.renderer.category.StatisticalBarRenderer:",
        "M|org.jfree.chart.renderer.category.StatisticalBarRenderer|getErrorIndicatorPaint||new:org.jfree.chart.renderer.category.StatisticalBarRenderer:",
        "M|org.jfree.chart.renderer.category.StatisticalBarRenderer|getErrorIndicatorStroke||new:org.jfree.chart.renderer.category.StatisticalBarRenderer:",
        "M|org.jfree.chart.renderer.category.StatisticalBarRenderer|readObject|java.io.ObjectInputStream|new:org.jfree.chart.renderer.category.StatisticalBarRenderer:",
        "M|org.jfree.chart.renderer.category.StatisticalBarRenderer|setErrorIndicatorPaint|java.awt.Paint|new:org.jfree.chart.renderer.category.StatisticalBarRenderer:",
        "M|org.jfree.chart.renderer.category.StatisticalBarRenderer|setErrorIndicatorStroke|java.awt.Stroke|new:org.jfree.chart.renderer.category.StatisticalBarRenderer:",
        "M|org.jfree.chart.renderer.category.StatisticalBarRenderer|writeObject|java.io.ObjectOutputStream|new:org.jfree.chart.renderer.category.StatisticalBarRenderer:",
        "C|org.jfree.chart.renderer.category.StatisticalBarRenderer|<init>|",
        "M|org.jfree.chart.renderer.category.StatisticalBarRenderer|drawHorizontalItem|java.awt.Graphics2D,org.jfree.chart.renderer.category.CategoryItemRendererState,java.awt.geom.Rectangle2D,org.jfree.chart.plot.CategoryPlot,org.jfree.chart.axis.CategoryAxis,org.jfree.chart.axis.ValueAxis,org.jfree.data.statistics.StatisticalCategoryDataset,int,int|new:org.jfree.chart.renderer.category.StatisticalBarRenderer:",
        "M|org.jfree.chart.renderer.category.StatisticalBarRenderer|drawVerticalItem|java.awt.Graphics2D,org.jfree.chart.renderer.category.CategoryItemRendererState,java.awt.geom.Rectangle2D,org.jfree.chart.plot.CategoryPlot,org.jfree.chart.axis.CategoryAxis,org.jfree.chart.axis.ValueAxis,org.jfree.data.statistics.StatisticalCategoryDataset,int,int|new:org.jfree.chart.renderer.category.StatisticalBarRenderer:",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 12) int w0, @InRange(minInt = 0, maxInt = 12) int w1, @InRange(minInt = 0, maxInt = 12) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
