package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 5 patched method(s), 21 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.jsoup.Jsoup|isValid|java.lang.String,org.jsoup.safety.Whitelist|static",
        "M|org.jsoup.parser.Parser|parseFragment|java.lang.String,org.jsoup.nodes.Element,java.lang.String|static",
        "M|org.jsoup.parser.Parser|parseFragment|java.lang.String,org.jsoup.nodes.Element,java.lang.String,org.jsoup.parser.ParseErrorList|static",
        "M|org.jsoup.safety.Cleaner|isValid|org.jsoup.nodes.Document|new:org.jsoup.safety.Cleaner:org.jsoup.safety.Whitelist",
        "M|org.jsoup.safety.Cleaner|isValidBodyHtml|java.lang.String|new:org.jsoup.safety.Cleaner:org.jsoup.safety.Whitelist",
        "M|org.jsoup.Jsoup|clean|java.lang.String,java.lang.String,org.jsoup.safety.Whitelist|static",
        "M|org.jsoup.Jsoup|clean|java.lang.String,java.lang.String,org.jsoup.safety.Whitelist,org.jsoup.nodes.Document$OutputSettings|static",
        "M|org.jsoup.Jsoup|clean|java.lang.String,org.jsoup.safety.Whitelist|static",
        "M|org.jsoup.Jsoup|connect|java.lang.String|static",
        "M|org.jsoup.Jsoup|parse|java.io.File,java.lang.String|static",
        "M|org.jsoup.Jsoup|parse|java.io.File,java.lang.String,java.lang.String|static",
        "M|org.jsoup.Jsoup|parse|java.io.InputStream,java.lang.String,java.lang.String|static",
        "M|org.jsoup.Jsoup|parse|java.io.InputStream,java.lang.String,java.lang.String,org.jsoup.parser.Parser|static",
        "M|org.jsoup.Jsoup|parse|java.lang.String|static",
        "M|org.jsoup.Jsoup|parse|java.lang.String,java.lang.String|static",
        "M|org.jsoup.Jsoup|parse|java.lang.String,java.lang.String,org.jsoup.parser.Parser|static",
        "M|org.jsoup.Jsoup|isValid|java.lang.String,org.jsoup.safety.Whitelist|static",
        "M|org.jsoup.parser.Parser|parseFragment|java.lang.String,org.jsoup.nodes.Element,java.lang.String|static",
        "M|org.jsoup.parser.Parser|parseFragment|java.lang.String,org.jsoup.nodes.Element,java.lang.String,org.jsoup.parser.ParseErrorList|static",
        "M|org.jsoup.safety.Cleaner|isValid|org.jsoup.nodes.Document|new:org.jsoup.safety.Cleaner:org.jsoup.safety.Whitelist",
        "M|org.jsoup.safety.Cleaner|isValidBodyHtml|java.lang.String|new:org.jsoup.safety.Cleaner:org.jsoup.safety.Whitelist",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 20) int w0, @InRange(minInt = 0, maxInt = 20) int w1, @InRange(minInt = 0, maxInt = 20) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
