#!/usr/bin/env bash
# Auto-create the fuzz driver + config for a Defects4J bug (no manual work).
#   ./auto_bug.sh <PID> <BID>        -> src/<PID>_<BID>/AutoFuzz.java + bugs/<PID>_<BID>.env
# exit 0 = ready, 2 = nothing fuzzable (no public static String method), 1 = error
set -uo pipefail
[ $# -lt 2 ] && { echo "Usage: $0 <PID> <BID>"; exit 1; }
PID=$1; BID=$2; KEY=${PID}_${BID}
WORK=${WORK:-$HOME/zest-d4j}
export TZ=America/Los_Angeles
F=$HOME/d4j/${KEY}f; B=$HOME/d4j/${KEY}b

for v in b f; do
  dir=$HOME/d4j/${KEY}$v
  [ -d "$dir" ] || timeout 600 defects4j checkout -p "$PID" -v "${BID}$v" -w "$dir" >/dev/null 2>&1 \
    || { echo "checkout ${BID}$v failed"; exit 1; }
  (cd "$dir" && timeout 900 defects4j compile >/dev/null 2>&1) || { echo "compile ${BID}$v failed"; exit 1; }
done

cd "$F"
CLASSES=$(defects4j export -p classes.modified 2>/dev/null | tr '\n' ',' | sed 's/,$//')
SRC_F=$F/$(defects4j export -p dir.src.classes 2>/dev/null)
SRC_B=$B/$(cd "$B" && defects4j export -p dir.src.classes 2>/dev/null)
CP_F=$(defects4j export -p cp.compile 2>/dev/null)
BIN_F=$F/$(defects4j export -p dir.bin.classes 2>/dev/null)
[ -n "$CLASSES" ] || { echo "no modified classes"; exit 1; }

# changed line numbers in the FIXED source, per modified class
CHG=$(mktemp)
for c in ${CLASSES//,/ }; do
  rel=${c%%\$*}; rel=${rel//.//}.java
  [ -f "$SRC_F/$rel" ] && [ -f "$SRC_B/$rel" ] || continue
  diff "$SRC_B/$rel" "$SRC_F/$rel" | grep -E '^[0-9]' | while read -r h; do
    right=${h#*[acd]}; s=${right%,*}; e=${right#*,}
    for ((l=s; l<=e; l++)); do echo "$c $l"; done
    [ "${h//[0-9,]/}" = "d" ] && echo "$c $((s+1))"   # pure deletion: mark the next line
  done
done > "$CHG"

TOOLS=$WORK/bin/_tools
if [ ! -f "$TOOLS/zestd4j/DriverGen2.class" ] || [ "$WORK/src/common/DriverGen2.java" -nt "$TOOLS/zestd4j/DriverGen2.class" ]; then
  mkdir -p "$TOOLS" && javac -nowarn -d "$TOOLS" "$WORK/src/common/DriverGen.java" "$WORK/src/common/DriverGen2.java" || exit 1
fi

mkdir -p "$WORK/src/$KEY" "$WORK/bugs"
NT=$(java -cp "$TOOLS:$CP_F" zestd4j.DriverGen2 "$WORK/src/$KEY" "$SRC_F" "$CHG" "$CLASSES" "$BIN_F")
rc=$?; rm -f "$CHG"
if [ $rc -ne 0 ] || [ -z "$NT" ]; then rm -rf "$WORK/src/$KEY"; exit 2; fi
FIRST=${CLASSES%%,*}; FIRST=${FIRST%%\$*}

cat > "$WORK/bugs/$KEY.env" <<CFG
# $PID-$BID  (auto-generated by auto_bug.sh; modified: $CLASSES)
PID=$PID
BID=$BID
DRIVER=zestd4j.AutoFuzz
METHOD=fuzz
WRITER=harness
TEST_PKG=${FIRST%.*}
TEST_CLS=${FIRST##*.}_Zest_Test
CFG
echo "ready: $NT targets ($(head -3 "$WORK/src/$KEY/targets.txt" | cut -d'|' -f3 | tr '\n' ' '))"
