package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 1 patched method(s), 17 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.fasterxml.jackson.databind.type.ReferenceType|getGenericSignature|java.lang.StringBuilder|new:com.fasterxml.jackson.databind.type.ReferenceType:java.lang.Class,com.fasterxml.jackson.databind.JavaType,java.lang.Object,java.lang.Object,boolean",
        "M|com.fasterxml.jackson.databind.type.ReferenceType|_narrow|java.lang.Class|new:com.fasterxml.jackson.databind.type.ReferenceType:java.lang.Class,com.fasterxml.jackson.databind.JavaType,java.lang.Object,java.lang.Object,boolean",
        "M|com.fasterxml.jackson.databind.type.ReferenceType|buildCanonicalName||new:com.fasterxml.jackson.databind.type.ReferenceType:java.lang.Class,com.fasterxml.jackson.databind.JavaType,java.lang.Object,java.lang.Object,boolean",
        "M|com.fasterxml.jackson.databind.type.ReferenceType|construct|java.lang.Class,com.fasterxml.jackson.databind.JavaType,java.lang.Object,java.lang.Object|static",
        "M|com.fasterxml.jackson.databind.type.ReferenceType|containedType|int|new:com.fasterxml.jackson.databind.type.ReferenceType:java.lang.Class,com.fasterxml.jackson.databind.JavaType,java.lang.Object,java.lang.Object,boolean",
        "M|com.fasterxml.jackson.databind.type.ReferenceType|containedTypeCount||new:com.fasterxml.jackson.databind.type.ReferenceType:java.lang.Class,com.fasterxml.jackson.databind.JavaType,java.lang.Object,java.lang.Object,boolean",
        "M|com.fasterxml.jackson.databind.type.ReferenceType|containedTypeName|int|new:com.fasterxml.jackson.databind.type.ReferenceType:java.lang.Class,com.fasterxml.jackson.databind.JavaType,java.lang.Object,java.lang.Object,boolean",
        "M|com.fasterxml.jackson.databind.type.ReferenceType|equals|java.lang.Object|new:com.fasterxml.jackson.databind.type.ReferenceType:java.lang.Class,com.fasterxml.jackson.databind.JavaType,java.lang.Object,java.lang.Object,boolean",
        "M|com.fasterxml.jackson.databind.type.ReferenceType|getErasedSignature|java.lang.StringBuilder|new:com.fasterxml.jackson.databind.type.ReferenceType:java.lang.Class,com.fasterxml.jackson.databind.JavaType,java.lang.Object,java.lang.Object,boolean",
        "M|com.fasterxml.jackson.databind.type.ReferenceType|getParameterSource||new:com.fasterxml.jackson.databind.type.ReferenceType:java.lang.Class,com.fasterxml.jackson.databind.JavaType,java.lang.Object,java.lang.Object,boolean",
        "M|com.fasterxml.jackson.databind.type.ReferenceType|getReferencedType||new:com.fasterxml.jackson.databind.type.ReferenceType:java.lang.Class,com.fasterxml.jackson.databind.JavaType,java.lang.Object,java.lang.Object,boolean",
        "M|com.fasterxml.jackson.databind.type.ReferenceType|isReferenceType||new:com.fasterxml.jackson.databind.type.ReferenceType:java.lang.Class,com.fasterxml.jackson.databind.JavaType,java.lang.Object,java.lang.Object,boolean",
        "M|com.fasterxml.jackson.databind.type.ReferenceType|toString||new:com.fasterxml.jackson.databind.type.ReferenceType:java.lang.Class,com.fasterxml.jackson.databind.JavaType,java.lang.Object,java.lang.Object,boolean",
        "M|com.fasterxml.jackson.databind.type.ReferenceType|withContentTypeHandler|java.lang.Object|new:com.fasterxml.jackson.databind.type.ReferenceType:java.lang.Class,com.fasterxml.jackson.databind.JavaType,java.lang.Object,java.lang.Object,boolean",
        "M|com.fasterxml.jackson.databind.type.ReferenceType|withContentValueHandler|java.lang.Object|new:com.fasterxml.jackson.databind.type.ReferenceType:java.lang.Class,com.fasterxml.jackson.databind.JavaType,java.lang.Object,java.lang.Object,boolean",
        "M|com.fasterxml.jackson.databind.type.ReferenceType|withStaticTyping||new:com.fasterxml.jackson.databind.type.ReferenceType:java.lang.Class,com.fasterxml.jackson.databind.JavaType,java.lang.Object,java.lang.Object,boolean",
        "M|com.fasterxml.jackson.databind.type.ReferenceType|getGenericSignature|java.lang.StringBuilder|new:com.fasterxml.jackson.databind.type.ReferenceType:java.lang.Class,com.fasterxml.jackson.databind.JavaType,java.lang.Object,java.lang.Object,boolean",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 16) int w0, @InRange(minInt = 0, maxInt = 16) int w1, @InRange(minInt = 0, maxInt = 16) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
