package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 1 patched method(s), 17 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.google.javascript.rhino.jstype.UnionType|meet|com.google.javascript.rhino.jstype.JSType|new:com.google.javascript.rhino.jstype.UnionType:com.google.javascript.rhino.jstype.JSTypeRegistry,java.util.Set",
        "M|com.google.javascript.rhino.jstype.UnionType|canAssignTo|com.google.javascript.rhino.jstype.JSType|new:com.google.javascript.rhino.jstype.UnionType:com.google.javascript.rhino.jstype.JSTypeRegistry,java.util.Set",
        "M|com.google.javascript.rhino.jstype.UnionType|canBeCalled||new:com.google.javascript.rhino.jstype.UnionType:com.google.javascript.rhino.jstype.JSTypeRegistry,java.util.Set",
        "M|com.google.javascript.rhino.jstype.UnionType|contains|com.google.javascript.rhino.jstype.JSType|new:com.google.javascript.rhino.jstype.UnionType:com.google.javascript.rhino.jstype.JSTypeRegistry,java.util.Set",
        "M|com.google.javascript.rhino.jstype.UnionType|equals|java.lang.Object|new:com.google.javascript.rhino.jstype.UnionType:com.google.javascript.rhino.jstype.JSTypeRegistry,java.util.Set",
        "M|com.google.javascript.rhino.jstype.UnionType|findPropertyType|java.lang.String|new:com.google.javascript.rhino.jstype.UnionType:com.google.javascript.rhino.jstype.JSTypeRegistry,java.util.Set",
        "M|com.google.javascript.rhino.jstype.UnionType|forgiveUnknownNames||new:com.google.javascript.rhino.jstype.UnionType:com.google.javascript.rhino.jstype.JSTypeRegistry,java.util.Set",
        "M|com.google.javascript.rhino.jstype.UnionType|getAlternates||new:com.google.javascript.rhino.jstype.UnionType:com.google.javascript.rhino.jstype.JSTypeRegistry,java.util.Set",
        "M|com.google.javascript.rhino.jstype.UnionType|getLeastSupertype|com.google.javascript.rhino.jstype.JSType|new:com.google.javascript.rhino.jstype.UnionType:com.google.javascript.rhino.jstype.JSTypeRegistry,java.util.Set",
        "M|com.google.javascript.rhino.jstype.UnionType|getPossibleToBooleanOutcomes||new:com.google.javascript.rhino.jstype.UnionType:com.google.javascript.rhino.jstype.JSTypeRegistry,java.util.Set",
        "M|com.google.javascript.rhino.jstype.UnionType|getRestrictedTypeGivenToBooleanOutcome|boolean|new:com.google.javascript.rhino.jstype.UnionType:com.google.javascript.rhino.jstype.JSTypeRegistry,java.util.Set",
        "M|com.google.javascript.rhino.jstype.UnionType|getRestrictedUnion|com.google.javascript.rhino.jstype.JSType|new:com.google.javascript.rhino.jstype.UnionType:com.google.javascript.rhino.jstype.JSTypeRegistry,java.util.Set",
        "M|com.google.javascript.rhino.jstype.UnionType|getTypesUnderEquality|com.google.javascript.rhino.jstype.JSType|new:com.google.javascript.rhino.jstype.UnionType:com.google.javascript.rhino.jstype.JSTypeRegistry,java.util.Set",
        "M|com.google.javascript.rhino.jstype.UnionType|getTypesUnderInequality|com.google.javascript.rhino.jstype.JSType|new:com.google.javascript.rhino.jstype.UnionType:com.google.javascript.rhino.jstype.JSTypeRegistry,java.util.Set",
        "M|com.google.javascript.rhino.jstype.UnionType|getTypesUnderShallowInequality|com.google.javascript.rhino.jstype.JSType|new:com.google.javascript.rhino.jstype.UnionType:com.google.javascript.rhino.jstype.JSTypeRegistry,java.util.Set",
        "M|com.google.javascript.rhino.jstype.UnionType|hashCode||new:com.google.javascript.rhino.jstype.UnionType:com.google.javascript.rhino.jstype.JSTypeRegistry,java.util.Set",
        "M|com.google.javascript.rhino.jstype.UnionType|meet|com.google.javascript.rhino.jstype.JSType|new:com.google.javascript.rhino.jstype.UnionType:com.google.javascript.rhino.jstype.JSTypeRegistry,java.util.Set",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 16) int w0, @InRange(minInt = 0, maxInt = 16) int w1, @InRange(minInt = 0, maxInt = 16) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
