package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 2 patched method(s), 18 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "C|org.jfree.chart.plot.MultiplePiePlot|<init>|",
        "C|org.jfree.chart.plot.MultiplePiePlot|<init>|org.jfree.data.category.CategoryDataset",
        "M|org.jfree.chart.plot.MultiplePiePlot|draw|java.awt.Graphics2D,java.awt.geom.Rectangle2D,java.awt.geom.Point2D,org.jfree.chart.plot.PlotState,org.jfree.chart.plot.PlotRenderingInfo|new:org.jfree.chart.plot.MultiplePiePlot:",
        "M|org.jfree.chart.plot.MultiplePiePlot|equals|java.lang.Object|new:org.jfree.chart.plot.MultiplePiePlot:",
        "M|org.jfree.chart.plot.MultiplePiePlot|getAggregatedItemsKey||new:org.jfree.chart.plot.MultiplePiePlot:",
        "M|org.jfree.chart.plot.MultiplePiePlot|getAggregatedItemsPaint||new:org.jfree.chart.plot.MultiplePiePlot:",
        "M|org.jfree.chart.plot.MultiplePiePlot|getDataExtractOrder||new:org.jfree.chart.plot.MultiplePiePlot:",
        "M|org.jfree.chart.plot.MultiplePiePlot|getDataset||new:org.jfree.chart.plot.MultiplePiePlot:",
        "M|org.jfree.chart.plot.MultiplePiePlot|getLegendItems||new:org.jfree.chart.plot.MultiplePiePlot:",
        "M|org.jfree.chart.plot.MultiplePiePlot|getLimit||new:org.jfree.chart.plot.MultiplePiePlot:",
        "M|org.jfree.chart.plot.MultiplePiePlot|getPieChart||new:org.jfree.chart.plot.MultiplePiePlot:",
        "M|org.jfree.chart.plot.MultiplePiePlot|getPlotType||new:org.jfree.chart.plot.MultiplePiePlot:",
        "M|org.jfree.chart.plot.MultiplePiePlot|prefetchSectionPaints||new:org.jfree.chart.plot.MultiplePiePlot:",
        "M|org.jfree.chart.plot.MultiplePiePlot|readObject|java.io.ObjectInputStream|new:org.jfree.chart.plot.MultiplePiePlot:",
        "M|org.jfree.chart.plot.MultiplePiePlot|setAggregatedItemsKey|java.lang.Comparable|new:org.jfree.chart.plot.MultiplePiePlot:",
        "M|org.jfree.chart.plot.MultiplePiePlot|setAggregatedItemsPaint|java.awt.Paint|new:org.jfree.chart.plot.MultiplePiePlot:",
        "C|org.jfree.chart.plot.MultiplePiePlot|<init>|",
        "C|org.jfree.chart.plot.MultiplePiePlot|<init>|org.jfree.data.category.CategoryDataset",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 17) int w0, @InRange(minInt = 0, maxInt = 17) int w1, @InRange(minInt = 0, maxInt = 17) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
