package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 5 patched method(s), 21 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.jfree.data.category.DefaultIntervalCategoryDataset|setCategoryKeys|[Ljava.lang.Comparable;|new:org.jfree.data.category.DefaultIntervalCategoryDataset:[[D,[[D",
        "C|org.jfree.data.category.DefaultIntervalCategoryDataset|<init>|[[D,[[D",
        "C|org.jfree.data.category.DefaultIntervalCategoryDataset|<init>|[Ljava.lang.Comparable;,[Ljava.lang.Comparable;,[[Ljava.lang.Number;,[[Ljava.lang.Number;",
        "C|org.jfree.data.category.DefaultIntervalCategoryDataset|<init>|[Ljava.lang.String;,[[Ljava.lang.Number;,[[Ljava.lang.Number;",
        "C|org.jfree.data.category.DefaultIntervalCategoryDataset|<init>|[[Ljava.lang.Number;,[[Ljava.lang.Number;",
        "M|org.jfree.data.category.DefaultIntervalCategoryDataset|clone|[[Ljava.lang.Number;|static",
        "M|org.jfree.data.category.DefaultIntervalCategoryDataset|clone||new:org.jfree.data.category.DefaultIntervalCategoryDataset:[[D,[[D",
        "M|org.jfree.data.category.DefaultIntervalCategoryDataset|equal|[[Ljava.lang.Number;,[[Ljava.lang.Number;|static",
        "M|org.jfree.data.category.DefaultIntervalCategoryDataset|equals|java.lang.Object|new:org.jfree.data.category.DefaultIntervalCategoryDataset:[[D,[[D",
        "M|org.jfree.data.category.DefaultIntervalCategoryDataset|generateKeys|int,java.lang.String|new:org.jfree.data.category.DefaultIntervalCategoryDataset:[[D,[[D",
        "M|org.jfree.data.category.DefaultIntervalCategoryDataset|getCategoryCount||new:org.jfree.data.category.DefaultIntervalCategoryDataset:[[D,[[D",
        "M|org.jfree.data.category.DefaultIntervalCategoryDataset|getCategoryIndex|java.lang.Comparable|new:org.jfree.data.category.DefaultIntervalCategoryDataset:[[D,[[D",
        "M|org.jfree.data.category.DefaultIntervalCategoryDataset|getColumnCount||new:org.jfree.data.category.DefaultIntervalCategoryDataset:[[D,[[D",
        "M|org.jfree.data.category.DefaultIntervalCategoryDataset|getColumnIndex|java.lang.Comparable|new:org.jfree.data.category.DefaultIntervalCategoryDataset:[[D,[[D",
        "M|org.jfree.data.category.DefaultIntervalCategoryDataset|getColumnKey|int|new:org.jfree.data.category.DefaultIntervalCategoryDataset:[[D,[[D",
        "M|org.jfree.data.category.DefaultIntervalCategoryDataset|getColumnKeys||new:org.jfree.data.category.DefaultIntervalCategoryDataset:[[D,[[D",
        "M|org.jfree.data.category.DefaultIntervalCategoryDataset|setCategoryKeys|[Ljava.lang.Comparable;|new:org.jfree.data.category.DefaultIntervalCategoryDataset:[[D,[[D",
        "C|org.jfree.data.category.DefaultIntervalCategoryDataset|<init>|[[D,[[D",
        "C|org.jfree.data.category.DefaultIntervalCategoryDataset|<init>|[Ljava.lang.Comparable;,[Ljava.lang.Comparable;,[[Ljava.lang.Number;,[[Ljava.lang.Number;",
        "C|org.jfree.data.category.DefaultIntervalCategoryDataset|<init>|[Ljava.lang.String;,[[Ljava.lang.Number;,[[Ljava.lang.Number;",
        "C|org.jfree.data.category.DefaultIntervalCategoryDataset|<init>|[[Ljava.lang.Number;,[[Ljava.lang.Number;",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 20) int w0, @InRange(minInt = 0, maxInt = 20) int w1, @InRange(minInt = 0, maxInt = 20) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
