package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 2 patched method(s), 18 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "C|org.jsoup.nodes.Attribute|<init>|java.lang.String,java.lang.String",
        "C|org.jsoup.nodes.Attribute|<init>|java.lang.String,java.lang.String,org.jsoup.nodes.Attributes",
        "M|org.jsoup.nodes.Attribute|clone||new:org.jsoup.nodes.Attribute:java.lang.String,java.lang.String",
        "M|org.jsoup.nodes.Attribute|createFromEncoded|java.lang.String,java.lang.String|static",
        "M|org.jsoup.nodes.Attribute|equals|java.lang.Object|new:org.jsoup.nodes.Attribute:java.lang.String,java.lang.String",
        "M|org.jsoup.nodes.Attribute|getKey||new:org.jsoup.nodes.Attribute:java.lang.String,java.lang.String",
        "M|org.jsoup.nodes.Attribute|getValue||new:org.jsoup.nodes.Attribute:java.lang.String,java.lang.String",
        "M|org.jsoup.nodes.Attribute|hashCode||new:org.jsoup.nodes.Attribute:java.lang.String,java.lang.String",
        "M|org.jsoup.nodes.Attribute|html|java.lang.String,java.lang.String,java.lang.Appendable,org.jsoup.nodes.Document$OutputSettings|static",
        "M|org.jsoup.nodes.Attribute|html|java.lang.Appendable,org.jsoup.nodes.Document$OutputSettings|new:org.jsoup.nodes.Attribute:java.lang.String,java.lang.String",
        "M|org.jsoup.nodes.Attribute|html||new:org.jsoup.nodes.Attribute:java.lang.String,java.lang.String",
        "M|org.jsoup.nodes.Attribute|isBooleanAttribute||new:org.jsoup.nodes.Attribute:java.lang.String,java.lang.String",
        "M|org.jsoup.nodes.Attribute|isBooleanAttribute|java.lang.String|static",
        "M|org.jsoup.nodes.Attribute|isDataAttribute||new:org.jsoup.nodes.Attribute:java.lang.String,java.lang.String",
        "M|org.jsoup.nodes.Attribute|isDataAttribute|java.lang.String|static",
        "M|org.jsoup.nodes.Attribute|setKey|java.lang.String|new:org.jsoup.nodes.Attribute:java.lang.String,java.lang.String",
        "C|org.jsoup.nodes.Attribute|<init>|java.lang.String,java.lang.String",
        "C|org.jsoup.nodes.Attribute|<init>|java.lang.String,java.lang.String,org.jsoup.nodes.Attributes",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 17) int w0, @InRange(minInt = 0, maxInt = 17) int w1, @InRange(minInt = 0, maxInt = 17) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
