package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 1 patched method(s), 17 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.apache.commons.jxpath.ri.model.beans.PropertyPointer|getLength||new:org.apache.commons.jxpath.ri.model.beans.BeanPropertyPointer:org.apache.commons.jxpath.ri.model.NodePointer,org.apache.commons.jxpath.JXPathBeanInfo",
        "M|org.apache.commons.jxpath.ri.model.beans.PropertyPointer|compareChildNodePointers|org.apache.commons.jxpath.ri.model.NodePointer,org.apache.commons.jxpath.ri.model.NodePointer|new:org.apache.commons.jxpath.ri.model.beans.BeanPropertyPointer:org.apache.commons.jxpath.ri.model.NodePointer,org.apache.commons.jxpath.JXPathBeanInfo",
        "M|org.apache.commons.jxpath.ri.model.beans.PropertyPointer|createChild|org.apache.commons.jxpath.JXPathContext,org.apache.commons.jxpath.ri.QName,int|new:org.apache.commons.jxpath.ri.model.beans.BeanPropertyPointer:org.apache.commons.jxpath.ri.model.NodePointer,org.apache.commons.jxpath.JXPathBeanInfo",
        "M|org.apache.commons.jxpath.ri.model.beans.PropertyPointer|createChild|org.apache.commons.jxpath.JXPathContext,org.apache.commons.jxpath.ri.QName,int,java.lang.Object|new:org.apache.commons.jxpath.ri.model.beans.BeanPropertyPointer:org.apache.commons.jxpath.ri.model.NodePointer,org.apache.commons.jxpath.JXPathBeanInfo",
        "M|org.apache.commons.jxpath.ri.model.beans.PropertyPointer|createPath|org.apache.commons.jxpath.JXPathContext|new:org.apache.commons.jxpath.ri.model.beans.BeanPropertyPointer:org.apache.commons.jxpath.ri.model.NodePointer,org.apache.commons.jxpath.JXPathBeanInfo",
        "M|org.apache.commons.jxpath.ri.model.beans.PropertyPointer|createPath|org.apache.commons.jxpath.JXPathContext,java.lang.Object|new:org.apache.commons.jxpath.ri.model.beans.BeanPropertyPointer:org.apache.commons.jxpath.ri.model.NodePointer,org.apache.commons.jxpath.JXPathBeanInfo",
        "M|org.apache.commons.jxpath.ri.model.beans.PropertyPointer|equals|java.lang.Object|new:org.apache.commons.jxpath.ri.model.beans.BeanPropertyPointer:org.apache.commons.jxpath.ri.model.NodePointer,org.apache.commons.jxpath.JXPathBeanInfo",
        "M|org.apache.commons.jxpath.ri.model.beans.PropertyPointer|getBean||new:org.apache.commons.jxpath.ri.model.beans.BeanPropertyPointer:org.apache.commons.jxpath.ri.model.NodePointer,org.apache.commons.jxpath.JXPathBeanInfo",
        "M|org.apache.commons.jxpath.ri.model.beans.PropertyPointer|getImmediateNode||new:org.apache.commons.jxpath.ri.model.beans.BeanPropertyPointer:org.apache.commons.jxpath.ri.model.NodePointer,org.apache.commons.jxpath.JXPathBeanInfo",
        "M|org.apache.commons.jxpath.ri.model.beans.PropertyPointer|getImmediateValuePointer||new:org.apache.commons.jxpath.ri.model.beans.BeanPropertyPointer:org.apache.commons.jxpath.ri.model.NodePointer,org.apache.commons.jxpath.JXPathBeanInfo",
        "M|org.apache.commons.jxpath.ri.model.beans.PropertyPointer|getName||new:org.apache.commons.jxpath.ri.model.beans.BeanPropertyPointer:org.apache.commons.jxpath.ri.model.NodePointer,org.apache.commons.jxpath.JXPathBeanInfo",
        "M|org.apache.commons.jxpath.ri.model.beans.PropertyPointer|getPropertyCount||new:org.apache.commons.jxpath.ri.model.beans.BeanPropertyPointer:org.apache.commons.jxpath.ri.model.NodePointer,org.apache.commons.jxpath.JXPathBeanInfo",
        "M|org.apache.commons.jxpath.ri.model.beans.PropertyPointer|getPropertyIndex||new:org.apache.commons.jxpath.ri.model.beans.BeanPropertyPointer:org.apache.commons.jxpath.ri.model.NodePointer,org.apache.commons.jxpath.JXPathBeanInfo",
        "M|org.apache.commons.jxpath.ri.model.beans.PropertyPointer|getPropertyName||new:org.apache.commons.jxpath.ri.model.beans.BeanPropertyPointer:org.apache.commons.jxpath.ri.model.NodePointer,org.apache.commons.jxpath.JXPathBeanInfo",
        "M|org.apache.commons.jxpath.ri.model.beans.PropertyPointer|getPropertyNames||new:org.apache.commons.jxpath.ri.model.beans.BeanPropertyPointer:org.apache.commons.jxpath.ri.model.NodePointer,org.apache.commons.jxpath.JXPathBeanInfo",
        "M|org.apache.commons.jxpath.ri.model.beans.PropertyPointer|hashCode||new:org.apache.commons.jxpath.ri.model.beans.BeanPropertyPointer:org.apache.commons.jxpath.ri.model.NodePointer,org.apache.commons.jxpath.JXPathBeanInfo",
        "M|org.apache.commons.jxpath.ri.model.beans.PropertyPointer|getLength||new:org.apache.commons.jxpath.ri.model.beans.BeanPropertyPointer:org.apache.commons.jxpath.ri.model.NodePointer,org.apache.commons.jxpath.JXPathBeanInfo",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 16) int w0, @InRange(minInt = 0, maxInt = 16) int w1, @InRange(minInt = 0, maxInt = 16) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
