package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 12 patched method(s), 28 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.jsoup.nodes.Attributes|add|java.lang.String,java.lang.String|new:org.jsoup.nodes.Attributes:",
        "M|org.jsoup.nodes.Attributes|deduplicate|org.jsoup.parser.ParseSettings|new:org.jsoup.nodes.Attributes:",
        "M|org.jsoup.nodes.Attributes|isEmpty||new:org.jsoup.nodes.Attributes:",
        "M|org.jsoup.parser.HtmlTreeBuilder|insert|org.jsoup.parser.Token$StartTag|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|insert|org.jsoup.nodes.Element|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|insert|org.jsoup.parser.Token$Character|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|insert|org.jsoup.parser.Token$Comment|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.ParseSettings|preserveAttributeCase||new:org.jsoup.parser.ParseSettings:boolean,boolean",
        "M|org.jsoup.parser.XmlTreeBuilder|insert|org.jsoup.parser.Token$StartTag|new:org.jsoup.parser.XmlTreeBuilder:",
        "M|org.jsoup.parser.XmlTreeBuilder|insert|org.jsoup.parser.Token$Character|new:org.jsoup.parser.XmlTreeBuilder:",
        "M|org.jsoup.parser.XmlTreeBuilder|insert|org.jsoup.parser.Token$Comment|new:org.jsoup.parser.XmlTreeBuilder:",
        "M|org.jsoup.parser.XmlTreeBuilder|insert|org.jsoup.parser.Token$Doctype|new:org.jsoup.parser.XmlTreeBuilder:",
        "M|org.jsoup.nodes.Attributes|addAll|org.jsoup.nodes.Attributes|new:org.jsoup.nodes.Attributes:",
        "M|org.jsoup.nodes.Attributes|asList||new:org.jsoup.nodes.Attributes:",
        "M|org.jsoup.nodes.Attributes|checkCapacity|int|new:org.jsoup.nodes.Attributes:",
        "M|org.jsoup.nodes.Attributes|checkNotNull|java.lang.String|static",
        "M|org.jsoup.nodes.Attributes|add|java.lang.String,java.lang.String|new:org.jsoup.nodes.Attributes:",
        "M|org.jsoup.nodes.Attributes|deduplicate|org.jsoup.parser.ParseSettings|new:org.jsoup.nodes.Attributes:",
        "M|org.jsoup.nodes.Attributes|isEmpty||new:org.jsoup.nodes.Attributes:",
        "M|org.jsoup.parser.HtmlTreeBuilder|insert|org.jsoup.parser.Token$StartTag|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|insert|org.jsoup.nodes.Element|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|insert|org.jsoup.parser.Token$Character|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|insert|org.jsoup.parser.Token$Comment|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.ParseSettings|preserveAttributeCase||new:org.jsoup.parser.ParseSettings:boolean,boolean",
        "M|org.jsoup.parser.XmlTreeBuilder|insert|org.jsoup.parser.Token$StartTag|new:org.jsoup.parser.XmlTreeBuilder:",
        "M|org.jsoup.parser.XmlTreeBuilder|insert|org.jsoup.parser.Token$Character|new:org.jsoup.parser.XmlTreeBuilder:",
        "M|org.jsoup.parser.XmlTreeBuilder|insert|org.jsoup.parser.Token$Comment|new:org.jsoup.parser.XmlTreeBuilder:",
        "M|org.jsoup.parser.XmlTreeBuilder|insert|org.jsoup.parser.Token$Doctype|new:org.jsoup.parser.XmlTreeBuilder:",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 27) int w0, @InRange(minInt = 0, maxInt = 27) int w1, @InRange(minInt = 0, maxInt = 27) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
