package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 4 patched method(s), 17 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.mockito.internal.configuration.injection.filter.FinalMockCandidateFilter|filterCandidate|java.util.Collection,java.lang.reflect.Field,java.util.List,java.lang.Object|new:org.mockito.internal.configuration.injection.filter.FinalMockCandidateFilter:",
        "M|org.mockito.internal.configuration.injection.filter.NameBasedCandidateFilter|filterCandidate|java.util.Collection,java.lang.reflect.Field,java.util.List,java.lang.Object|new:org.mockito.internal.configuration.injection.filter.NameBasedCandidateFilter:org.mockito.internal.configuration.injection.filter.MockCandidateFilter",
        "M|org.mockito.internal.configuration.injection.filter.TypeBasedCandidateFilter|filterCandidate|java.util.Collection,java.lang.reflect.Field,java.util.List,java.lang.Object|new:org.mockito.internal.configuration.injection.filter.TypeBasedCandidateFilter:org.mockito.internal.configuration.injection.filter.MockCandidateFilter",
        "M|org.mockito.internal.configuration.injection.PropertyAndSetterInjection|injectMockCandidatesOnFields|java.util.Set,java.lang.Object,boolean,java.util.List|new:org.mockito.internal.configuration.injection.PropertyAndSetterInjection:",
        "C|org.mockito.internal.configuration.injection.filter.FinalMockCandidateFilter|<init>|",
        "M|org.mockito.internal.configuration.injection.filter.MockCandidateFilter|filterCandidate|java.util.Collection,java.lang.reflect.Field,java.util.List,java.lang.Object|new:org.mockito.internal.configuration.injection.filter.FinalMockCandidateFilter:",
        "C|org.mockito.internal.configuration.injection.filter.NameBasedCandidateFilter|<init>|org.mockito.internal.configuration.injection.filter.MockCandidateFilter",
        "C|org.mockito.internal.configuration.injection.filter.TypeBasedCandidateFilter|<init>|org.mockito.internal.configuration.injection.filter.MockCandidateFilter",
        "M|org.mockito.internal.configuration.injection.PropertyAndSetterInjection|initializeInjectMocksField|java.lang.reflect.Field,java.lang.Object|new:org.mockito.internal.configuration.injection.PropertyAndSetterInjection:",
        "M|org.mockito.internal.configuration.injection.PropertyAndSetterInjection|injectMockCandidates|java.lang.Class,java.util.Set,java.lang.Object|new:org.mockito.internal.configuration.injection.PropertyAndSetterInjection:",
        "M|org.mockito.internal.configuration.injection.PropertyAndSetterInjection|orderedInstanceFieldsFrom|java.lang.Class|new:org.mockito.internal.configuration.injection.PropertyAndSetterInjection:",
        "M|org.mockito.internal.configuration.injection.PropertyAndSetterInjection|processInjection|java.lang.reflect.Field,java.lang.Object,java.util.Set|new:org.mockito.internal.configuration.injection.PropertyAndSetterInjection:",
        "C|org.mockito.internal.configuration.injection.PropertyAndSetterInjection|<init>|",
        "M|org.mockito.internal.configuration.injection.filter.FinalMockCandidateFilter|filterCandidate|java.util.Collection,java.lang.reflect.Field,java.util.List,java.lang.Object|new:org.mockito.internal.configuration.injection.filter.FinalMockCandidateFilter:",
        "M|org.mockito.internal.configuration.injection.filter.NameBasedCandidateFilter|filterCandidate|java.util.Collection,java.lang.reflect.Field,java.util.List,java.lang.Object|new:org.mockito.internal.configuration.injection.filter.NameBasedCandidateFilter:org.mockito.internal.configuration.injection.filter.MockCandidateFilter",
        "M|org.mockito.internal.configuration.injection.filter.TypeBasedCandidateFilter|filterCandidate|java.util.Collection,java.lang.reflect.Field,java.util.List,java.lang.Object|new:org.mockito.internal.configuration.injection.filter.TypeBasedCandidateFilter:org.mockito.internal.configuration.injection.filter.MockCandidateFilter",
        "M|org.mockito.internal.configuration.injection.PropertyAndSetterInjection|injectMockCandidatesOnFields|java.util.Set,java.lang.Object,boolean,java.util.List|new:org.mockito.internal.configuration.injection.PropertyAndSetterInjection:",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 16) int w0, @InRange(minInt = 0, maxInt = 16) int w1, @InRange(minInt = 0, maxInt = 16) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
