package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 19 patched method(s), 35 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.jsoup.nodes.Element|normalName||new:org.jsoup.nodes.Element:java.lang.String",
        "M|org.jsoup.parser.HtmlTreeBuilder|clearStackToContext|[Ljava.lang.String;|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|generateImpliedEndTags||new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|generateImpliedEndTags|java.lang.String|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|getActiveFormattingElement|java.lang.String|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|getFromStack|java.lang.String|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|inSelectScope|java.lang.String|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|inSpecificScope|java.lang.String,[Ljava.lang.String;,[Ljava.lang.String;|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|inSpecificScope|[Ljava.lang.String;,[Ljava.lang.String;,[Ljava.lang.String;|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|isSameFormattingElement|org.jsoup.nodes.Element,org.jsoup.nodes.Element|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|isSpecial|org.jsoup.nodes.Element|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|popStackToBefore|java.lang.String|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|popStackToClose|java.lang.String|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|popStackToClose|[Ljava.lang.String;|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|reconstructFormattingElements||new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|resetInsertionMode||new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.nodes.Element|normalName||new:org.jsoup.nodes.Element:java.lang.String",
        "M|org.jsoup.parser.HtmlTreeBuilder|clearStackToContext|[Ljava.lang.String;|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|generateImpliedEndTags||new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|generateImpliedEndTags|java.lang.String|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|getActiveFormattingElement|java.lang.String|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|getFromStack|java.lang.String|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|inSelectScope|java.lang.String|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|inSpecificScope|java.lang.String,[Ljava.lang.String;,[Ljava.lang.String;|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|inSpecificScope|[Ljava.lang.String;,[Ljava.lang.String;,[Ljava.lang.String;|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|isSameFormattingElement|org.jsoup.nodes.Element,org.jsoup.nodes.Element|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|isSpecial|org.jsoup.nodes.Element|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|popStackToBefore|java.lang.String|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|popStackToClose|java.lang.String|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|popStackToClose|[Ljava.lang.String;|new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|reconstructFormattingElements||new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilder|resetInsertionMode||new:org.jsoup.parser.HtmlTreeBuilder:",
        "M|org.jsoup.parser.HtmlTreeBuilderState|process|org.jsoup.parser.Token,org.jsoup.parser.HtmlTreeBuilder|fac:org.jsoup.parser.HtmlTreeBuilderState:valueOf:java.lang.String",
        "M|org.jsoup.parser.Tag|normalName||new:org.jsoup.parser.Tag:java.lang.String",
        "C|org.jsoup.parser.Tag|<init>|java.lang.String",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 34) int w0, @InRange(minInt = 0, maxInt = 34) int w1, @InRange(minInt = 0, maxInt = 34) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
