package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 12 patched method(s), 28 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.apache.commons.lang3.reflect.TypeUtils|getTypeArguments|java.lang.Class,java.lang.Class,java.util.Map|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|getTypeArguments|java.lang.reflect.ParameterizedType,java.lang.Class,java.util.Map|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|getTypeArguments|java.lang.reflect.Type,java.lang.Class,java.util.Map|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|getTypeArguments|java.lang.reflect.ParameterizedType|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|getTypeArguments|java.lang.reflect.Type,java.lang.Class|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|isAssignable|java.lang.reflect.Type,java.lang.Class|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|isAssignable|java.lang.reflect.Type,java.lang.reflect.GenericArrayType,java.util.Map|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|isAssignable|java.lang.reflect.Type,java.lang.reflect.ParameterizedType,java.util.Map|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|isAssignable|java.lang.reflect.Type,java.lang.reflect.Type,java.util.Map|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|isAssignable|java.lang.reflect.Type,java.lang.reflect.TypeVariable,java.util.Map|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|isAssignable|java.lang.reflect.Type,java.lang.reflect.WildcardType,java.util.Map|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|isAssignable|java.lang.reflect.Type,java.lang.reflect.Type|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|determineTypeArguments|java.lang.Class,java.lang.reflect.ParameterizedType|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|getArrayComponentType|java.lang.reflect.Type|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|getClosestParentType|java.lang.Class,java.lang.Class|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|getImplicitBounds|java.lang.reflect.TypeVariable|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|getTypeArguments|java.lang.Class,java.lang.Class,java.util.Map|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|getTypeArguments|java.lang.reflect.ParameterizedType,java.lang.Class,java.util.Map|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|getTypeArguments|java.lang.reflect.Type,java.lang.Class,java.util.Map|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|getTypeArguments|java.lang.reflect.ParameterizedType|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|getTypeArguments|java.lang.reflect.Type,java.lang.Class|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|isAssignable|java.lang.reflect.Type,java.lang.Class|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|isAssignable|java.lang.reflect.Type,java.lang.reflect.GenericArrayType,java.util.Map|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|isAssignable|java.lang.reflect.Type,java.lang.reflect.ParameterizedType,java.util.Map|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|isAssignable|java.lang.reflect.Type,java.lang.reflect.Type,java.util.Map|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|isAssignable|java.lang.reflect.Type,java.lang.reflect.TypeVariable,java.util.Map|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|isAssignable|java.lang.reflect.Type,java.lang.reflect.WildcardType,java.util.Map|static",
        "M|org.apache.commons.lang3.reflect.TypeUtils|isAssignable|java.lang.reflect.Type,java.lang.reflect.Type|static",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 27) int w0, @InRange(minInt = 0, maxInt = 27) int w1, @InRange(minInt = 0, maxInt = 27) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
