package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 1 patched method(s), 17 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.google.javascript.jscomp.TypeValidator|getReadableJSTypeName|com.google.javascript.rhino.Node,boolean|new:com.google.javascript.jscomp.TypeValidator:com.google.javascript.jscomp.AbstractCompiler",
        "M|com.google.javascript.jscomp.TypeValidator|containsForwardDeclaredUnresolvedName|com.google.javascript.rhino.jstype.JSType|new:com.google.javascript.jscomp.TypeValidator:com.google.javascript.jscomp.AbstractCompiler",
        "M|com.google.javascript.jscomp.TypeValidator|expectActualObject|com.google.javascript.jscomp.NodeTraversal,com.google.javascript.rhino.Node,com.google.javascript.rhino.jstype.JSType,java.lang.String|new:com.google.javascript.jscomp.TypeValidator:com.google.javascript.jscomp.AbstractCompiler",
        "M|com.google.javascript.jscomp.TypeValidator|expectAllInterfaceProperties|com.google.javascript.jscomp.NodeTraversal,com.google.javascript.rhino.Node,com.google.javascript.rhino.jstype.FunctionType|new:com.google.javascript.jscomp.TypeValidator:com.google.javascript.jscomp.AbstractCompiler",
        "M|com.google.javascript.jscomp.TypeValidator|expectAnyObject|com.google.javascript.jscomp.NodeTraversal,com.google.javascript.rhino.Node,com.google.javascript.rhino.jstype.JSType,java.lang.String|new:com.google.javascript.jscomp.TypeValidator:com.google.javascript.jscomp.AbstractCompiler",
        "M|com.google.javascript.jscomp.TypeValidator|expectArgumentMatchesParameter|com.google.javascript.jscomp.NodeTraversal,com.google.javascript.rhino.Node,com.google.javascript.rhino.jstype.JSType,com.google.javascript.rhino.jstype.JSType,com.google.javascript.rhino.Node,int|new:com.google.javascript.jscomp.TypeValidator:com.google.javascript.jscomp.AbstractCompiler",
        "M|com.google.javascript.jscomp.TypeValidator|expectBitwiseable|com.google.javascript.jscomp.NodeTraversal,com.google.javascript.rhino.Node,com.google.javascript.rhino.jstype.JSType,java.lang.String|new:com.google.javascript.jscomp.TypeValidator:com.google.javascript.jscomp.AbstractCompiler",
        "M|com.google.javascript.jscomp.TypeValidator|expectCanAssignTo|com.google.javascript.jscomp.NodeTraversal,com.google.javascript.rhino.Node,com.google.javascript.rhino.jstype.JSType,com.google.javascript.rhino.jstype.JSType,java.lang.String|new:com.google.javascript.jscomp.TypeValidator:com.google.javascript.jscomp.AbstractCompiler",
        "M|com.google.javascript.jscomp.TypeValidator|expectCanAssignToPropertyOf|com.google.javascript.jscomp.NodeTraversal,com.google.javascript.rhino.Node,com.google.javascript.rhino.jstype.JSType,com.google.javascript.rhino.jstype.JSType,com.google.javascript.rhino.Node,java.lang.String|new:com.google.javascript.jscomp.TypeValidator:com.google.javascript.jscomp.AbstractCompiler",
        "M|com.google.javascript.jscomp.TypeValidator|expectCanCast|com.google.javascript.jscomp.NodeTraversal,com.google.javascript.rhino.Node,com.google.javascript.rhino.jstype.JSType,com.google.javascript.rhino.jstype.JSType|new:com.google.javascript.jscomp.TypeValidator:com.google.javascript.jscomp.AbstractCompiler",
        "M|com.google.javascript.jscomp.TypeValidator|expectCanOverride|com.google.javascript.jscomp.NodeTraversal,com.google.javascript.rhino.Node,com.google.javascript.rhino.jstype.JSType,com.google.javascript.rhino.jstype.JSType,java.lang.String,com.google.javascript.rhino.jstype.JSType|new:com.google.javascript.jscomp.TypeValidator:com.google.javascript.jscomp.AbstractCompiler",
        "M|com.google.javascript.jscomp.TypeValidator|expectIndexMatch|com.google.javascript.jscomp.NodeTraversal,com.google.javascript.rhino.Node,com.google.javascript.rhino.jstype.JSType,com.google.javascript.rhino.jstype.JSType|new:com.google.javascript.jscomp.TypeValidator:com.google.javascript.jscomp.AbstractCompiler",
        "M|com.google.javascript.jscomp.TypeValidator|expectInterfaceProperty|com.google.javascript.jscomp.NodeTraversal,com.google.javascript.rhino.Node,com.google.javascript.rhino.jstype.ObjectType,com.google.javascript.rhino.jstype.ObjectType,java.lang.String|new:com.google.javascript.jscomp.TypeValidator:com.google.javascript.jscomp.AbstractCompiler",
        "M|com.google.javascript.jscomp.TypeValidator|expectNotNullOrUndefined|com.google.javascript.jscomp.NodeTraversal,com.google.javascript.rhino.Node,com.google.javascript.rhino.jstype.JSType,java.lang.String,com.google.javascript.rhino.jstype.JSType|new:com.google.javascript.jscomp.TypeValidator:com.google.javascript.jscomp.AbstractCompiler",
        "M|com.google.javascript.jscomp.TypeValidator|expectNumber|com.google.javascript.jscomp.NodeTraversal,com.google.javascript.rhino.Node,com.google.javascript.rhino.jstype.JSType,java.lang.String|new:com.google.javascript.jscomp.TypeValidator:com.google.javascript.jscomp.AbstractCompiler",
        "M|com.google.javascript.jscomp.TypeValidator|expectObject|com.google.javascript.jscomp.NodeTraversal,com.google.javascript.rhino.Node,com.google.javascript.rhino.jstype.JSType,java.lang.String|new:com.google.javascript.jscomp.TypeValidator:com.google.javascript.jscomp.AbstractCompiler",
        "M|com.google.javascript.jscomp.TypeValidator|getReadableJSTypeName|com.google.javascript.rhino.Node,boolean|new:com.google.javascript.jscomp.TypeValidator:com.google.javascript.jscomp.AbstractCompiler",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 16) int w0, @InRange(minInt = 0, maxInt = 16) int w1, @InRange(minInt = 0, maxInt = 16) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
