package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 1 patched method(s), 17 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.google.javascript.jscomp.FunctionToBlockMutator|makeLocalNamesUnique|com.google.javascript.rhino.Node,boolean|new:com.google.javascript.jscomp.FunctionToBlockMutator:com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier",
        "M|com.google.javascript.jscomp.FunctionToBlockMutator|addDummyAssignment|com.google.javascript.rhino.Node,java.lang.String|static",
        "M|com.google.javascript.jscomp.FunctionToBlockMutator|aliasAndInlineArguments|com.google.javascript.rhino.Node,java.util.LinkedHashMap,java.util.Set|new:com.google.javascript.jscomp.FunctionToBlockMutator:com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier",
        "M|com.google.javascript.jscomp.FunctionToBlockMutator|convertLastReturnToStatement|com.google.javascript.rhino.Node,java.lang.String|static",
        "M|com.google.javascript.jscomp.FunctionToBlockMutator|createAssignStatementNode|java.lang.String,com.google.javascript.rhino.Node|static",
        "M|com.google.javascript.jscomp.FunctionToBlockMutator|fixUnitializedVarDeclarations|com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.FunctionToBlockMutator:com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier",
        "M|com.google.javascript.jscomp.FunctionToBlockMutator|getLabelNameForFunction|java.lang.String|new:com.google.javascript.jscomp.FunctionToBlockMutator:com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier",
        "M|com.google.javascript.jscomp.FunctionToBlockMutator|getReplacementReturnStatement|com.google.javascript.rhino.Node,java.lang.String|static",
        "M|com.google.javascript.jscomp.FunctionToBlockMutator|hasReturnAtExit|com.google.javascript.rhino.Node|static",
        "M|com.google.javascript.jscomp.FunctionToBlockMutator|mutate|java.lang.String,com.google.javascript.rhino.Node,com.google.javascript.rhino.Node,java.lang.String,boolean,boolean|new:com.google.javascript.jscomp.FunctionToBlockMutator:com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier",
        "M|com.google.javascript.jscomp.FunctionToBlockMutator|replaceReturnWithBreak|com.google.javascript.rhino.Node,com.google.javascript.rhino.Node,java.lang.String,java.lang.String|static",
        "M|com.google.javascript.jscomp.FunctionToBlockMutator|replaceReturns|com.google.javascript.rhino.Node,java.lang.String,java.lang.String,boolean|static",
        "C|com.google.javascript.jscomp.FunctionToBlockMutator|<init>|com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier",
        "M|com.google.javascript.jscomp.RenameLabels|process|com.google.javascript.rhino.Node,com.google.javascript.rhino.Node|new:com.google.javascript.jscomp.RenameLabels:com.google.javascript.jscomp.AbstractCompiler",
        "C|com.google.javascript.jscomp.RenameLabels|<init>|com.google.javascript.jscomp.AbstractCompiler",
        "C|com.google.javascript.jscomp.RenameLabels|<init>|com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier,boolean",
        "M|com.google.javascript.jscomp.FunctionToBlockMutator|makeLocalNamesUnique|com.google.javascript.rhino.Node,boolean|new:com.google.javascript.jscomp.FunctionToBlockMutator:com.google.javascript.jscomp.AbstractCompiler,com.google.common.base.Supplier",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 16) int w0, @InRange(minInt = 0, maxInt = 16) int w1, @InRange(minInt = 0, maxInt = 16) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
