package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 6 patched method(s), 22 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.apache.commons.math3.optim.nonlinear.scalar.gradient.NonLinearConjugateGradientOptimizer|doOptimize||new:org.apache.commons.math3.optim.nonlinear.scalar.gradient.NonLinearConjugateGradientOptimizer:org.apache.commons.math3.optim.nonlinear.scalar.gradient.NonLinearConjugateGradientOptimizer$Formula,org.apache.commons.math3.optim.ConvergenceChecker",
        "M|org.apache.commons.math3.optim.nonlinear.scalar.noderiv.CMAESOptimizer|doOptimize||new:org.apache.commons.math3.optim.nonlinear.scalar.noderiv.CMAESOptimizer:int,double,boolean,int,int,org.apache.commons.math3.random.RandomGenerator,boolean,org.apache.commons.math3.optim.ConvergenceChecker",
        "M|org.apache.commons.math3.optim.nonlinear.scalar.noderiv.PowellOptimizer|doOptimize||new:org.apache.commons.math3.optim.nonlinear.scalar.noderiv.PowellOptimizer:double,double",
        "M|org.apache.commons.math3.optim.nonlinear.scalar.noderiv.SimplexOptimizer|doOptimize||new:org.apache.commons.math3.optim.nonlinear.scalar.noderiv.SimplexOptimizer:org.apache.commons.math3.optim.ConvergenceChecker",
        "M|org.apache.commons.math3.optim.nonlinear.vector.jacobian.GaussNewtonOptimizer|doOptimize||new:org.apache.commons.math3.optim.nonlinear.vector.jacobian.GaussNewtonOptimizer:org.apache.commons.math3.optim.ConvergenceChecker",
        "M|org.apache.commons.math3.optim.nonlinear.vector.jacobian.LevenbergMarquardtOptimizer|doOptimize||new:org.apache.commons.math3.optim.nonlinear.vector.jacobian.LevenbergMarquardtOptimizer:",
        "M|org.apache.commons.math3.optim.BaseOptimizer|doOptimize||new:org.apache.commons.math3.optim.linear.SimplexSolver:",
        "M|org.apache.commons.math3.optim.BaseOptimizer|getConvergenceChecker||new:org.apache.commons.math3.optim.linear.SimplexSolver:",
        "M|org.apache.commons.math3.optim.BaseOptimizer|getEvaluations||new:org.apache.commons.math3.optim.linear.SimplexSolver:",
        "M|org.apache.commons.math3.optim.BaseOptimizer|getIterations||new:org.apache.commons.math3.optim.linear.SimplexSolver:",
        "M|org.apache.commons.math3.optim.BaseOptimizer|getMaxEvaluations||new:org.apache.commons.math3.optim.linear.SimplexSolver:",
        "M|org.apache.commons.math3.optim.BaseOptimizer|getMaxIterations||new:org.apache.commons.math3.optim.linear.SimplexSolver:",
        "M|org.apache.commons.math3.optim.BaseOptimizer|incrementEvaluationCount||new:org.apache.commons.math3.optim.linear.SimplexSolver:",
        "M|org.apache.commons.math3.optim.BaseOptimizer|incrementIterationCount||new:org.apache.commons.math3.optim.linear.SimplexSolver:",
        "M|org.apache.commons.math3.optim.BaseOptimizer|optimize|[Lorg.apache.commons.math3.optim.OptimizationData;|new:org.apache.commons.math3.optim.linear.SimplexSolver:",
        "M|org.apache.commons.math3.optim.BaseOptimizer|parseOptimizationData|[Lorg.apache.commons.math3.optim.OptimizationData;|new:org.apache.commons.math3.optim.linear.SimplexSolver:",
        "M|org.apache.commons.math3.optim.nonlinear.scalar.gradient.NonLinearConjugateGradientOptimizer|doOptimize||new:org.apache.commons.math3.optim.nonlinear.scalar.gradient.NonLinearConjugateGradientOptimizer:org.apache.commons.math3.optim.nonlinear.scalar.gradient.NonLinearConjugateGradientOptimizer$Formula,org.apache.commons.math3.optim.ConvergenceChecker",
        "M|org.apache.commons.math3.optim.nonlinear.scalar.noderiv.CMAESOptimizer|doOptimize||new:org.apache.commons.math3.optim.nonlinear.scalar.noderiv.CMAESOptimizer:int,double,boolean,int,int,org.apache.commons.math3.random.RandomGenerator,boolean,org.apache.commons.math3.optim.ConvergenceChecker",
        "M|org.apache.commons.math3.optim.nonlinear.scalar.noderiv.PowellOptimizer|doOptimize||new:org.apache.commons.math3.optim.nonlinear.scalar.noderiv.PowellOptimizer:double,double",
        "M|org.apache.commons.math3.optim.nonlinear.scalar.noderiv.SimplexOptimizer|doOptimize||new:org.apache.commons.math3.optim.nonlinear.scalar.noderiv.SimplexOptimizer:org.apache.commons.math3.optim.ConvergenceChecker",
        "M|org.apache.commons.math3.optim.nonlinear.vector.jacobian.GaussNewtonOptimizer|doOptimize||new:org.apache.commons.math3.optim.nonlinear.vector.jacobian.GaussNewtonOptimizer:org.apache.commons.math3.optim.ConvergenceChecker",
        "M|org.apache.commons.math3.optim.nonlinear.vector.jacobian.LevenbergMarquardtOptimizer|doOptimize||new:org.apache.commons.math3.optim.nonlinear.vector.jacobian.LevenbergMarquardtOptimizer:",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 21) int w0, @InRange(minInt = 0, maxInt = 21) int w1, @InRange(minInt = 0, maxInt = 21) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
