package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 3 patched method(s), 19 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|com.fasterxml.jackson.databind.util.StdDateFormat|_format|java.util.TimeZone,java.util.Locale,java.util.Date,java.lang.StringBuffer|new:com.fasterxml.jackson.databind.util.StdDateFormat:",
        "M|com.fasterxml.jackson.databind.util.StdDateFormat|_formatBCEYear|java.lang.StringBuffer,int|new:com.fasterxml.jackson.databind.util.StdDateFormat:",
        "M|com.fasterxml.jackson.databind.util.StdDateFormat|pad4|java.lang.StringBuffer,int|static",
        "M|com.fasterxml.jackson.databind.util.StdDateFormat|_clearFormats||new:com.fasterxml.jackson.databind.util.StdDateFormat:",
        "M|com.fasterxml.jackson.databind.util.StdDateFormat|_cloneFormat|java.text.DateFormat,java.lang.String,java.util.TimeZone,java.util.Locale,java.lang.Boolean|static",
        "M|com.fasterxml.jackson.databind.util.StdDateFormat|_equals|java.lang.Object,java.lang.Object|static",
        "M|com.fasterxml.jackson.databind.util.StdDateFormat|_getCalendar|java.util.TimeZone|new:com.fasterxml.jackson.databind.util.StdDateFormat:",
        "M|com.fasterxml.jackson.databind.util.StdDateFormat|_parse2D|java.lang.String,int|static",
        "M|com.fasterxml.jackson.databind.util.StdDateFormat|_parse4D|java.lang.String,int|static",
        "M|com.fasterxml.jackson.databind.util.StdDateFormat|_parseAsISO8601|java.lang.String,java.text.ParsePosition|new:com.fasterxml.jackson.databind.util.StdDateFormat:",
        "M|com.fasterxml.jackson.databind.util.StdDateFormat|_parseDate|java.lang.String,java.text.ParsePosition|new:com.fasterxml.jackson.databind.util.StdDateFormat:",
        "M|com.fasterxml.jackson.databind.util.StdDateFormat|_parseDateFromLong|java.lang.String,java.text.ParsePosition|new:com.fasterxml.jackson.databind.util.StdDateFormat:",
        "M|com.fasterxml.jackson.databind.util.StdDateFormat|clone||new:com.fasterxml.jackson.databind.util.StdDateFormat:",
        "M|com.fasterxml.jackson.databind.util.StdDateFormat|equals|java.lang.Object|new:com.fasterxml.jackson.databind.util.StdDateFormat:",
        "M|com.fasterxml.jackson.databind.util.StdDateFormat|format|java.util.Date,java.lang.StringBuffer,java.text.FieldPosition|new:com.fasterxml.jackson.databind.util.StdDateFormat:",
        "M|com.fasterxml.jackson.databind.util.StdDateFormat|getDefaultTimeZone||static",
        "M|com.fasterxml.jackson.databind.util.StdDateFormat|_format|java.util.TimeZone,java.util.Locale,java.util.Date,java.lang.StringBuffer|new:com.fasterxml.jackson.databind.util.StdDateFormat:",
        "M|com.fasterxml.jackson.databind.util.StdDateFormat|_formatBCEYear|java.lang.StringBuffer,int|new:com.fasterxml.jackson.databind.util.StdDateFormat:",
        "M|com.fasterxml.jackson.databind.util.StdDateFormat|pad4|java.lang.StringBuffer,int|static",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 18) int w0, @InRange(minInt = 0, maxInt = 18) int w1, @InRange(minInt = 0, maxInt = 18) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
