package zestd4j;

import com.pholser.junit.quickcheck.generator.InRange;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;
import static org.junit.Assume.assumeTrue;

// AUTO-GENERATED by DriverGen2: 3 patched method(s), 19 target entries
@RunWith(JQF.class)
public class AutoFuzz {
    static final String[] T = {
        "M|org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream|readNewEntry|boolean|new:org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream:java.io.InputStream",
        "M|org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream|readOldAsciiEntry||new:org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream:java.io.InputStream",
        "M|org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream|readOldBinaryEntry|boolean|new:org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream:java.io.InputStream",
        "M|org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream|available||new:org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream:java.io.InputStream",
        "M|org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream|close||new:org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream:java.io.InputStream",
        "M|org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream|closeEntry||new:org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream:java.io.InputStream",
        "M|org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream|ensureOpen||new:org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream:java.io.InputStream",
        "M|org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream|getNextCPIOEntry||new:org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream:java.io.InputStream",
        "M|org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream|getNextEntry||new:org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream:java.io.InputStream",
        "M|org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream|matches|[B,int|static",
        "M|org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream|read|[B,int,int|new:org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream:java.io.InputStream",
        "M|org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream|readAsciiLong|int,int|new:org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream:java.io.InputStream",
        "M|org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream|readBinaryLong|int,boolean|new:org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream:java.io.InputStream",
        "M|org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream|readCString|int|new:org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream:java.io.InputStream",
        "M|org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream|readFully|[B,int,int|new:org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream:java.io.InputStream",
        "M|org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream|skip|int|new:org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream:java.io.InputStream",
        "M|org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream|readNewEntry|boolean|new:org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream:java.io.InputStream",
        "M|org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream|readOldAsciiEntry||new:org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream:java.io.InputStream",
        "M|org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream|readOldBinaryEntry|boolean|new:org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream:java.io.InputStream",
    };

    @Fuzz
    public void fuzz(@InRange(minInt = 1, maxInt = 3) int n,
            @InRange(minInt = 0, maxInt = 18) int w0, @InRange(minInt = 0, maxInt = 18) int w1, @InRange(minInt = 0, maxInt = 18) int w2,
            String s0, String s1, String s2,
            @InRange(minInt = -5, maxInt = 60) int i0, @InRange(minInt = -1000, maxInt = 100000) int i1, int i2,
            long l0, @InRange(minLong = -100000L, maxLong = 100000L) long l1,
            boolean b0, boolean b1, char c0, char c1, double d0, double d1) throws Throwable {
        InputLog.recordCall(n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        Harness.run(T, n, w0, w1, w2, s0, s1, s2, i0, i1, i2, l0, l1, b0, b1, c0, c1, d0, d1);
        assumeTrue(!Harness.invalid);
    }
}
